// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Screening/nls/strings":{_widgetLabel:"Screening",geometryServicesNotFound:"Geometritjeneste er ikke tilg\u00e6ngelig.",unableToDrawBuffer:"Kan ikke tegne buffer. Pr\u00f8v igen.",invalidConfiguration:"Ugyldig konfiguration.",clearAOIButtonLabel:"Start forfra",noGraphicsShapefile:"Den overf\u00f8rte shapefil indeholder ikke nogen grafik.",zoomToLocationTooltipText:"Zoom til position",noGraphicsToZoomMessage:"Ingen grafik fundet at zoome ind p\u00e5.",placenameWidget:{placenameLabel:"S\u00f8g efter en position"},
drawToolWidget:{useDrawToolForAOILabel:"V\u00e6lg tegnetilstand",toggleSelectability:"Klik for at skifte valgbarhed",chooseLayerTitle:"V\u00e6lg lag, der kan markeres",selectAllLayersText:"V\u00e6lg alle",layerSelectionWarningTooltip:"Mindst \u00e9t lag b\u00f8r v\u00e6lges for at oprette AOI",selectToolLabel:"V\u00e6lg v\u00e6rkt\u00f8j"},shapefileWidget:{shapefileLabel:"Overf\u00f8r en zip-komprimeret shapefil",uploadShapefileButtonText:"Overf\u00f8r",unableToUploadShapefileMessage:"Kan ikke overf\u00f8re shapefilen."},
coordinatesWidget:{selectStartPointFromSearchText:"Defin\u00e9r et startpunkt",addButtonTitle:"Tilf\u00f8j",deleteButtonTitle:"Fjern",mapTooltipForStartPoint:"Klik p\u00e5 kortet for at definere et startpunkt",mapTooltipForUpdateStartPoint:"Klik p\u00e5 kortet for at opdatere startpunktet",locateText:"Find",locateByMapClickText:"V\u00e6lg startkoordinater",enterBearingAndDistanceLabel:"Angiv pejling og afstand fra startpunkt",bearingTitle:"Pejling",distanceTitle:"Afstand",planSettingTooltip:"Planindstillinger",
invalidLatLongMessage:"Indtast gyldige v\u00e6rdier."},bufferDistanceAndUnit:{bufferInputTitle:"Bufferafstand (valgfri)",bufferInputLabel:"Viser resultater inden for",bufferDistanceLabel:"Bufferafstand",bufferUnitLabel:"Bufferenhed"},traverseSettings:{bearingLabel:"Pejling",lengthLabel:"L\u00e6ngde",addButtonTitle:"Tilf\u00f8j",deleteButtonTitle:"Fjern",deleteBearingAndLengthLabel:"Fjern pejlings- og l\u00e6ngder\u00e6kke",addButtonLabel:"Tilf\u00f8j pejling og l\u00e6ngde"},planSettings:{expandGridTooltipText:"Udvid gitter",
collapseGridTooltipText:"Skjul gitter",directionUnitLabelText:"Retningsenhed",distanceUnitLabelText:"Afstands- og l\u00e6ngdeenheder",planSettingsComingSoonText:"Kommer snart"},newTraverse:{invalidBearingMessage:"Ugyldig pejling.",invalidLengthMessage:"Ugyldig l\u00e6ngde.",negativeLengthMessage:"Negativ l\u00e6ngde"},reportsTab:{aoiAreaText:"AOI-omr\u00e5de",downloadButtonTooltip:"Hent",printButtonTooltip:"Udskriv",uploadShapefileForAnalysisText:"Overf\u00f8r shapefil, der skal medtages i analyse",
uploadShapefileForButtonText:"Gennemse",downloadLabelText:"V\u00e6lg format:",downloadBtnText:"Hent",noDetailsAvailableText:"Ingen resultater fundet",featureCountText:"T\u00e6lling",featureAreaText:"Omr\u00e5de",featureLengthText:"L\u00e6ngde",attributeChooserTooltip:"V\u00e6lg attributter, der skal vises",csv:"CSV",filegdb:"Filgeodatabase",shapefile:"Shapefil",noFeaturesFound:"Intet resultat fundet for det valgte filformat",selectReportFieldTitle:"V\u00e6lg felter",noFieldsSelected:"Ingen felter valgt",
intersectingFeatureExceedsMsgOnCompletion:"Det maksimale antal poster er n\u00e5et for et eller flere lag.",unableToAnalyzeText:"Kan ikke analysere, det maksimale antal poster er n\u00e5et.",errorInPrintingReport:"Kan ikke udskrive rapporten. Kontroll\u00e9r, om rapportindstillingerne er gyldige.",aoiInformationTitle:"Oplysninger om interesseomr\u00e5de (AOI)",summaryReportTitle:"Resum\u00e9",notApplicableText:"I/T",downloadReportConfirmTitle:"Bekr\u00e6ft download",downloadReportConfirmMessage:"Er du sikker p\u00e5, at du vil downloade?",
noDataText:"Ingen data",createReplicaFailedMessage:"Downloadhandling mislykkedes for f\u00f8lgende lag: \x3cbr/\x3e ${layerNames}",extractDataTaskFailedMessage:"Downloadhandling mislykkedes.",printLayoutLabelText:"Layout",printBtnText:"Udskriv",printDialogHint:"Bem\u00e6rk: Rapporttitel og kommentarer kan redigeres i forh\u00e5ndsvisningen af rapporten.",unableToDownloadFileGDBText:"Filgeodatabase kan ikke downloades for AOI, der indeholder punkt- eller linjepositioner",unableToDownloadShapefileText:"Shapefil kan ikke downloades for AOI, der indeholder punkt- eller linjepositioner",
analysisAreaUnitLabelText:"Vis omr\u00e5deresultater i:",analysisLengthUnitLabelText:"Vis l\u00e6ngderesultater i:",analysisUnitButtonTooltip:"V\u00e6lg enheder til analyse",analysisCloseBtnText:"Luk",areaSquareFeetUnit:"Kvadratfod",areaAcresUnit:"Acres",areaSquareMetersUnit:"Kvadratmeter",areaSquareKilometersUnit:"Kvadratkilometer",areaHectaresUnit:"Hektarer",areaSquareMilesUnit:"Kvadratmiles",lengthFeetUnit:"Fod",lengthMilesUnit:"Miles",lengthMetersUnit:"Meter",lengthKilometersUnit:"Kilometer",
hectaresAbbr:"hektarer",squareMilesAbbr:"Kvadratmiles",layerNotVisibleText:"Kan ikke analysere. Laget er sl\u00e5et fra eller ligger uden for m\u00e5lestokkens synlighedsomr\u00e5de.",refreshBtnTooltip:"Opdat\u00e9r rapport",featureCSVAreaText:"Gennemsk\u00e6ringsomr\u00e5de",featureCSVLengthText:"Gennemsk\u00e6ringsl\u00e6ngde",errorInFetchingPrintTask:"Der opstod et problem under hentning af printopgavens oplysninger. Pr\u00f8v igen.",selectAllLabel:"V\u00e6lg alle",errorInLoadingProjectionModule:"Fejl under indl\u00e6sning af projektionsmodulets afh\u00e6ngigheder. Fors\u00f8g at downloade filen igen.",
expandCollapseIconLabel:"Objekter, der er gennemsk\u00e5ret",intersectedFeatureLabel:"Oplysninger om objekter, der er gennemsk\u00e5ret",valueAriaLabel:"V\u00e6rdi",countAriaLabel:"T\u00e6lling",layerNameWithFeatureCount:"${layerName} lag med ${featureCount} objekter, der gennemsk\u00e6rer hinanden"},_localized:{}}});