// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/DataAggregation/nls/strings":{_widgetLabel:"Agr\u00e9gation de donn\u00e9es",startPage:{defaultStartPageInstructions:"Ce widget vous aide \u00e0 traiter et \u00e0 envoyer des donn\u00e9es depuis un fichier vers la couche s\u00e9lectionn\u00e9e de la carte.\x3cbr/\x3e \x3cbr/\x3e Les valeurs au sein de ce fichier doivent \u00eatre d\u00e9limit\u00e9es par une virgule, une tabulation, un point-virgule ou une barre verticale.",dragDrop:"Glisser-d\u00e9poser",browse:"Acc\u00e9der au fichier",
or:"'OU'",userPrivilege:"Votre compte ne dispose pas des autorisations de cr\u00e9ation ou de modification des donn\u00e9es.",userCredits:"${widgetName} requiert des cr\u00e9dits pour l\u2019utilisation du localisateur ${locator}.",contactAdmin:"Contactez l\u2019administrateur de l\u2019organisation pour demander des cr\u00e9dits suppl\u00e9mentaires.",contactAdminEdit:"Contactez l\u2019administrateur de l\u2019organisation pour demander des privil\u00e8ges de mise \u00e0 jour.",canUseLocator:"Le localisateur ${locator} sera utilis\u00e9 pour localiser des entit\u00e9s.",
notEnoughCredits:"Cr\u00e9dits insuffisants.",locationAndField:"Informations de localisation et de champ",locationAndFieldHint:"S\u00e9lectionnez les valeurs \u00e0 partir du fichier \u00e0 employer pour mettre \u00e0 jour la couche cible.",cannotUseLocator:"Impossible d\u2019utiliser ${widgetName}",noAnonymousEdit:"La couche ${layerName} ne prend pas en charge la mise \u00e0 jour anonyme.",pleaseLogin:"Connectez-vous \u00e0 l\u2019organisation ${org} ou contactez l\u2019administrateur de l\u2019organisation pour demander l\u2019activation de la mise \u00e0 jour anonyme.",
invalidEdit:"Privil\u00e8ges non valides",unableToAccess:"Impossible d\u2019acc\u00e9der \u00e0 ${layerName}",appropriateCredentials:"V\u00e9rifiez que vous \u00eates connect\u00e9 avec les identifiants de connexion appropri\u00e9s.",shared:"Contactez l\u2019administrateur de l\u2019organisation pour demander l\u2019acc\u00e8s \u00e0 la couche ${layerName}.",targetLayerLabel:"Couche cible",homeButtonLabel:"Accueil",mappingErrorMsg:"Cliquez sur la fl\u00e8che Suivant pour d\u00e9finir les champs"},
mapping:{schemaMapping:"Informations de champ",schemaMappingHint:"Choisissez les champs du fichier qui sont en corr\u00e9lation avec les champs de la couche.",locationMapping:"Informations d\u2019emplacement",locationMappingHint:"Choisissez le type d\u2019adresse ou les informations de coordonn\u00e9es \u00e0 attendre du fichier."},locationMapping:{locationMappingPageHint:"Choisir le type d'emplacement",useAddress:"Localiser \u00e0 l\u2019aide d\u2019une adresse",useAddressHint:"Les donn\u00e9es contiennent des informations d\u2019adresses",
useCoordinates:"Localiser \u00e0 l\u2019aide des coordonn\u00e9es",useCoordinatesHint:"Les donn\u00e9es contiennent les valeurs de coordonn\u00e9es X/Y"},address:{addressPageHint:"Choisir le type d\u2019adresse",singleField:"Champ unique",singleFieldHint:"S\u00e9lectionner le champ contenant les informations d\u2019adresse",multiField:"Champs multiples",multiFieldHint:"S\u00e9lectionner les champs qui contiennent les informations d\u2019adresse"},coordinates:{coordinatesPageHint:"S\u00e9lectionner les champs qui contiennent les donn\u00e9es de coordonn\u00e9es"},
fieldMapping:{fieldMappingPageHint:"Choisir le champ source mapp\u00e9 sur le champ cible",sourceField:"Champ source correspondant",targetField:"Champ cible"},buttons:{addToMap:"Ajouter \u00e0 la carte",submit:"Envoyer",download:"T\u00e9l\u00e9charger"},review:{matched:"Trouv\u00e9",reviewMatched:"Localisations trouv\u00e9es",reviewMatchedHint:"Examinez les localisations trouv\u00e9es.",unMatched:"introuvable",reviewUnMatched:"Emplacements introuvables",reviewUnMatchedHint:"Examinez les localisations introuvables. Les \u00e9l\u00e9ments non corrig\u00e9s ne seront pas envoy\u00e9s.",
duplicate:"Dupliquer",reviewDuplicate:"Dupliquer les localisations",reviewDuplicateHint:"Examinez les localisations d\u00e9j\u00e0 trouv\u00e9es dans la couche. Les \u00e9l\u00e9ments non r\u00e9solus ne seront pas envoy\u00e9s.",reviewLabelWithCount:"${totalMatchedFeatures} ${headerString} ${headerStringHint}",use:"Utiliser :",fromLayer:"Informations sur la cible",target:"Cible",source:"Source",fromFile:"Informations sur la source",locationControlHint:"Examiner les informations d\u2019adresse",duplicateAction:"S\u00e9lectionner une action",
item:"Enregistrement :",locateFeature:"Localiser une entit\u00e9",removeFeature:"Remove Feature (Supprimer l\u2019entit\u00e9)",featureLocated:"Localisation trouv\u00e9e",valuesDoNotMatch:"Ne correspond pas \u00e0 la valeur existante",sync:"Synchroniser les informations d\u2019adresse avec les informations de champ",noFeaturesSaved:"Aucune entit\u00e9 enregistr\u00e9e avec succ\u00e8s",someFeaturesSaved:"${num} entit\u00e9(s) a/ont \u00e9t\u00e9 enregistr\u00e9e(s) avec succ\u00e8s.",someFeaturesNotSaved:"${num} entit\u00e9(s) n\u2019a/n\u2019ont pas \u00e9t\u00e9 enregistr\u00e9e(s).",
feature:"Examiner les informations sur l\u2019entit\u00e9",locationInfo:"Examiner les informations sur la localisation",selectValue:"S\u00e9lectionner une valeur",reviewData:"Examiner les donn\u00e9es",reviewDataHint:"Examinez vos donn\u00e9es avant de les envoyer \u00e0 la couche.",reviewFeatureHint:"Examinez ou mettez \u00e0 jour vos informations sur l\u2019entit\u00e9 et la localisation.",duplicateModify:"Doublon, requiert une modification",duplicateSave:"Enregistrer en tant que nouvelle entit\u00e9"},
warningsAndErrors:{invalidCSV:"Erreur lors de la r\u00e9cup\u00e9ration d\u2019\u00e9l\u00e9ments \u00e0 partir du fichier\u00a0CSV\u00a0; v\u00e9rifiez qu\u2019un fichier\u00a0CSV valide est s\u00e9lectionn\u00e9.",noLayersWarning:"Aucune couche cible valide n\u2019est s\u00e9lectionn\u00e9e, v\u00e9rifiez la configuration.",loadWarning:"Ce widget requiert une source de donn\u00e9es Service d\u2019entit\u00e9s. Configurez le widget pour d\u00e9finir une source de donn\u00e9es.",saveError:"Erreur d\u2019enregistrement des entit\u00e9s.",
consumesCredits:"Cet outil consomme des cr\u00e9dits lorsqu\u2019il est utilis\u00e9 avec le service de g\u00e9ocodage mondial ArcGIS Online.",noValue:"S\u00e9lectionner un champ",mappingTitle:"",locationMappingComplete:"Appariement d\u2019emplacements termin\u00e9",fieldMappingComplete:"Appariement de champs termin\u00e9",settingsCleared:"Les param\u00e8tres seront effac\u00e9s.",proceed:"Voulez-vous continuer\u00a0?",itemMoveMatch:"L\u2019\u00e9l\u00e9ment a \u00e9t\u00e9 localis\u00e9 et d\u00e9plac\u00e9 vers la liste des localisations trouv\u00e9es",
itemMoveUnMatched:"Impossible de localiser l\u2019\u00e9l\u00e9ment. D\u00e9plac\u00e9 vers la liste des localisations introuvables.",itemWillBeLocated:"L\u2019\u00e9l\u00e9ment sera retir\u00e9 de la liste des localisations en double.",cannotLocate:"Impossible de localiser l\u2019\u00e9l\u00e9ment. V\u00e9rifiez les informations de localisation.",invalidMessage:"Valeur non valide.",rangeMessage:"La valeur doit comporter moins de ${num}\u00a0caract\u00e8res.",locatorError:"Localisateur non valide ou inaccessible.",
notConfigured:"localisateur non configur\u00e9 pour les options de localisation actuelles",noMoreLocators:"aucun localisateur suppl\u00e9mentaire configur\u00e9"},featureToolbar:{locate:"Localiser",save:"Enregistrer l\u2019enregistrement",cancel:"Annuler les mises \u00e0 jour",cancelTitle:"Annuler les mises \u00e0 jour",cancelMessage:"Annuler les mises \u00e0 jour apport\u00e9es \u00e0 l\u2019enregistrement actuel\u00a0?"},_localized:{}}});