// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/json ./constants ./geometry-utils ./labeling-utils ./mgrs ./NonPolarGridZone ./VisibleGridZone ./GridPolygon esri/geometry/geometryEngine esri/graphic esri/geometry/Point esri/geometry/Polyline esri/geometry/Polygon esri/symbols/SimpleLineSymbol esri/symbols/TextSymbol esri/symbols/Font esri/Color".split(" "),function(N,q,v,E,x,Q,R,S,I,F,J,M,O,G,K,H,L){return{_ZonesDictionary:function(){var a,d,b,n="CDEFGHJKLMNPQRSTUVWX".split(""),e={};for(a=1;60>=a;a++)for(d=0;d<n.length;d++){var l=
b=void 0,f=void 0,u=void 0;b=void 0;var h=a+n[d];"32X"===h||"34X"===h||"36X"===h?b=null:("31V"===h?b={xmin:0,ymin:56,xmax:3,ymax:64,id:h}:"32V"===h?b={xmin:3,ymin:56,xmax:12,ymax:64,id:h}:"31X"===h?b={xmin:0,ymin:72,xmax:9,ymax:84,id:h}:"33X"===h?b={xmin:9,ymin:72,xmax:21,ymax:84,id:h}:"35X"===h?b={xmin:21,ymin:72,xmax:33,ymax:84,id:h}:"37X"===h?b={xmin:33,ymin:72,xmax:42,ymax:84,id:h}:(u=(a-1)*q.ZONE_WIDTH_DEGREES-180,f=a*q.ZONE_WIDTH_DEGREES-180,l=d*q.ZONE_HEIGHT_DEGREES+q.MIN_MGRS_LATITUDE,b=(d+
1)*q.ZONE_HEIGHT_DEGREES+q.MIN_MGRS_LATITUDE,u=180===u?q.POSITIVE_180:u,u=-180===u?q.NEGATIVE_180:u,f=180===f?q.POSITIVE_180:f,f=-180===f?q.NEGATIVE_180:f,80===b&&(b=q.MAX_MGRS_LATITUDE),b={xmin:u,ymin:l,xmax:f,ymax:b,id:h}),b=new Q(b));b&&(e[b.id]=b)}return e}(),getInterval:function(a,d,b){var n=0;var e=d.getResolutionInMeters()*a;var l=d.extent.getCenter();var f=d.toMap(d.toScreen(l).offset(0,a/2));for(e=d.toMap(d.toScreen(l).offset(0,-a/2));84<=f.getLatitude()||84<=e.getLatitude();)n++,f=d.toMap(d.toScreen(l).offset(0,
a/2+n*a)),e=d.toMap(d.toScreen(l).offset(0,-a/2+n*a));for(;-80>=f.getLatitude()||-80>=e.getLatitude();)n++,f=d.toMap(d.toScreen(l).offset(0,a/2-n*a)),e=d.toMap(d.toScreen(l).offset(0,-a/2-n*a));a=f.getLatitude();d=f.getLongitude();f=e.getLatitude();n=e.getLongitude();e=x.getZoneNumber(a,d);e=Math.abs(x.LLtoUTM(a,d,e)[1]-x.LLtoUTM(f,n,e)[1]);a=Math.log10(e);switch(b){case "more":b=Math.floor(a);break;case "less":case "strict":b=Math.ceil(a);break;default:b=Math.round(a)}b=Math.pow(10,b);e>2*b&&(b*=
10);return 1E5<b?!1:b},zonesFromExtent:function(a){var d;var b=a.map.extent;var n=b.spatialReference.isWebMercator()?q.WEBMERCATOR_360:q.GEOGRAPHIC_360,e={xOffset:a.getCornerLabelXOffset(),yOffset:a.getCornerLabelYOffset(),rotation:0,color:a.getColor(0),fontFamily:a.getFontFamily(),fontSize:a.getFontSize(0)},l="CDEFGHJKLMNPQRSTUVWX".split(""),f=[];if(b.xmax-b.xmin>n)return f;n=v.extentToPolygon(b);n=v.toWebMercator(n);var u=v.pointToGeographic(new J([b.xmin,b.ymin],b.spatialReference)),h=v.pointToGeographic(new J([b.xmax,
b.ymax],b.spatialReference));b=u.y;var t=h.y;var A=u.offsetX;var p=h.offsetX;for(var g=A;g<=p;g++){var r=g>A?q.NEGATIVE_180:u.x;var m=g<p?q.POSITIVE_180:h.x;var k=Math.min(Math.max(Math.floor((b+80)/q.ZONE_HEIGHT_DEGREES),0),19);var y=Math.min(Math.floor((t+80)/q.ZONE_HEIGHT_DEGREES),19);r=Math.floor((r+180)/q.ZONE_WIDTH_DEGREES);for(m=Math.min(Math.floor((m+180)/q.ZONE_WIDTH_DEGREES)+2,60);r<=m;r++)for(var C=k;C<=y;C++){var z=l[C];z=r+z;if(this._ZonesDictionary[z]){var B=N.parse(N.stringify(this._ZonesDictionary[z]._rings));
for(d=0;d<B[0].length;d++)B[0][d][0]+=g*q.GEOGRAPHIC_360;d=new O({rings:B});var c=new M({paths:B});if(B=I.intersect(v.toWebMercator(d),n))d=I.intersect(v.toWebMercator(c),n),f.push(new R({map:a.map,polyline:d,polygon:B,offset:g,nonPolarGridZone:this._ZonesDictionary[z],labelParameters:e}))}}}return f},processZonePolygons:function(a,d){for(var b={},n=d.getInterval(),e=0;e<a.length;e++){var l=a[e];l&&(this.handleZonePolygon(l,d),n&&(b[l.nonPolarGridZone.utmZone]?b[l.nonPolarGridZone.utmZone].polygon=
I.union([v.toWebMercator(l.polygon),b[l.nonPolarGridZone.utmZone].polygon]):b[l.nonPolarGridZone.utmZone]={polygon:v.toWebMercator(l.polygon),offset:l.offset}))}if(n)for(a=Object.keys(b),e=0;e<a.length;e++){l=a[e];var f=b[l].polygon,u=b[l].offset,h=v.toGeographic(f.getExtent()),t=x.LLtoUTM(h.ymin,h.xmin,l),A=x.LLtoUTM(h.ymin,h.xmax,l),p=x.LLtoUTM(h.ymax,h.xmax,l);h=x.LLtoUTM(h.ymax,h.xmin,l);l={minE:Math.min(t[0],A[0],p[0],h[0]),maxE:Math.max(t[0],A[0],p[0],h[0]),minN:Math.min(t[1],A[1],p[1],h[1]),
maxN:Math.max(t[1],A[1],p[1],h[1]),utmZone:l,polygon:f,offset:u,grid:d};this.handle100kGrids(l);1E5>n&&this.handleIntervals(l)}},handleZonePolygon:function(a,d){var b=a.polyline;var n=d.getColor(0);var e=d.getLineWidth(0);d._lineGraphics0.push(new F(b,new G(G.STYLE_SOLID,new L(n),e)));36978596<d.map.getScale()||d._labelGraphics.push(a.getCenterLabel(!0))},handle100kGrids:function(a){var d=a.polygon,b=a.offset,n=a.utmZone,e=a.minE,l=a.maxE,f=a.minN,u=a.maxN;a=a.grid;var h=a.getColor(1),t=a.getLineWidth(1),
A=a.getMap(),p,g;for(f=1E5*Math.floor(f/1E5);f<u;f+=1E5)for(p=1E5*Math.floor(e/1E5);p<l;p+=1E5){var r=x.findGridLetters(n,0>f+5E4?1E7+(f+5E4):f+5E4,p+5E4);var m=[];for(g=p;g<=p+1E5;g+=1E4){var k=x.UTMtoLL(f,g,n);m.push([k.lon,k.lat])}for(g=f;g<f+1E5;g+=1E4)k=x.UTMtoLL(g,p+1E5,n),m.push([k.lon,k.lat]);for(g=p+1E5;g>=p;g-=1E4)k=x.UTMtoLL(f+1E5,g,n),m.push([k.lon,k.lat]);for(g=f+1E5;g>=f;g-=1E4)k=x.UTMtoLL(g,p,n),m.push([k.lon,k.lat]);for(g=0;g<m.length;g++)m[g][0]+=b*q.GEOGRAPHIC_360;m=new O([m]);g=
v.polygonToPolyline(m);k=I.intersect(v.toWebMercator(m),v.toWebMercator(d));g=I.intersect(v.toWebMercator(g),v.toWebMercator(d));if(k&&(r={clippedPolygon:k,unclippedPolygon:m,map:A,xmin:p%1E6,ymin:f%1E6,xmax:(p+1E5)%1E6,ymax:(f+1E5)%1E6,minMaxType:"utm",utmZone:n,text:r,labelParameters:{xOffset:10,yOffset:10,rotation:0,color:a.getColor(1),fontFamily:a.getFontFamily(),fontSize:a.getFontSize(1)}},r=new S(r),!(4622324<a.map.getScale())))for(r=[r.getCenterLabel(!0)],g&&a._lineGraphics1.push(new F(g,new G(G.STYLE_SOLID,
new L(h),t))),g=0;g<r.length;g++)a._labelGraphics.push(r[g])}},handleIntervals:function(a){var d=a.polygon,b=a.utmZone,n=a.offset,e=a.minE,l=a.maxE,f=a.minN,u=a.maxN;a=a.grid;var h=a.getFontFamily(),t=a.getIntervalLabelXOffset(),A=a.getIntervalLabelYOffset(),p=a.getInterval(),g=a.getMap(),r=a.getVerticalLabels(),m;for(m=Math.floor(f/p)*p;m<=u;m+=p)if(0!==m%1E5){if(0===m%1E4){var k=2;var y=a._lineGraphics2}else 0===m%1E3?(k=3,y=a._lineGraphics3):0===m%100?(k=4,y=a._lineGraphics4):(k=5,y=a._lineGraphics5);
var C=a.getColor(k);var z=a.getLineWidth(k);k=a.getFontSize(k);var B=new H(k,H.STYLE_NORMAL,H.VARIANT_NORMAL,H.WEIGHT_BOLD,h);var c=[];var w=x.UTMtoLL(m,e,b);var D=x.UTMtoLL(m,l,b);for(w=0;w<l;w+=1E4){var P=x.UTMtoLL(m,e+w,b);c.push([P.lon,P.lat])}c.push([D.lon,D.lat]);for(w=0;w<c.length;w++)c[w][0]+=n*q.GEOGRAPHIC_360;if(D=I.intersect(v.toWebMercator(new M([c])),v.toWebMercator(d))){z=new F(D,new G(G.STYLE_SOLID,new L(C),z));y.push(z);y=E.padZero((0>f?1E7+m:m)%1E5/p,5-Math.log10(p));c=D.paths[0];
w=new J({x:c[0][0]+.001,y:c[0][1],spatialReference:D.spatialReference});D=new J({x:c[c.length-1][0]-.001,y:c[c.length-1][1],spatialReference:D.spatialReference});z=E.screenDistanceBetweenPoints(w,D,g).horizontal;c=E.distanceFromMapEdge(w,g).horizontal;if(2>c||200<c&&300<z)c=(new K(y)).setAngle(0).setColor(C).setOffset(t,-(k/1.333)/2).setAlign("start").setFont(B),c=new F(w,c),a._labelGraphics.push(c);c=E.distanceFromMapEdge(D,g).horizontal;if(2>c||200<c&&300<z)c=(new K(y)).setAngle(0).setColor(C).setOffset(-t,
-(k/1.333)/2).setAlign("end").setFont(B),c=new F(D,c),a._labelGraphics.push(c)}}for(e=Math.floor(e/p)*p;e<=l;e+=p)if(0!==e%1E5){0===e%1E4?(k=2,y=a._lineGraphics2):0===e%1E3?(k=3,y=a._lineGraphics3):0===e%100?(k=4,y=a._lineGraphics4):(k=5,y=a._lineGraphics5);C=a.getColor(k);z=a.getLineWidth(k);k=a.getFontSize(k);B=new H(k,H.STYLE_NORMAL,H.VARIANT_NORMAL,H.WEIGHT_BOLD,h);c=[];m=x.UTMtoLL(f-1E4,e,b);t=x.UTMtoLL(u+1E4,e,b);c.push([m.lon,m.lat]);c.push([t.lon,t.lat]);for(w=0;w<c.length;w++)c[w][0]+=n*
q.GEOGRAPHIC_360;if(t=I.intersect(v.toWebMercator(new M([c])),v.toWebMercator(d))){m=new F(t,new G(G.STYLE_SOLID,new L(C),z));y.push(m);y=E.padZero(e%1E5/p,5-Math.log10(p));c=t.paths[0];m=new J({x:c[0][0],y:c[0][1]+.001,spatialReference:{wkid:102100}});t=new J({x:c[c.length-1][0],y:c[c.length-1][1]-.001,spatialReference:{wkid:102100}});z=E.screenDistanceBetweenPoints(m,t,g).vertical;c=E.distanceFromMapEdge(m,g).vertical;if(2>c||200<c&&300<z)c=(new K(y)).setAngle(r?90:0).setColor(C).setOffset(r?-(k/
1.333)/2:0,A).setAlign(r?"end":"middle").setFont(B),c=new F(m,c),a._labelGraphics.push(c);c=E.distanceFromMapEdge(t,g).vertical;if(2>c||200<c&&300<z)c=(new K(y)).setAngle(r?90:0).setColor(C).setOffset(r?-(k/1.333)/2:0,r?-A:-A-k/1.333).setAlign(r?"start":"middle").setFont(B),c=new F(t,c),a._labelGraphics.push(c)}}}}});