// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/CostAnalysis/setting/ManageScenarios.html":'\x3cdiv class\x3d"esriCTMainConfigurationContainer"\x3e\r\n    \x3cdiv\x3e\r\n        \x3cdiv class\x3d"esriCTPopupFields esriCTEllipsis"\x3e ${nls.costingInfo.scenarioNameLabel}\x3c/div\x3e\r\n        \x3cdiv style\x3d"width:180px" data-dojo-attach-point\x3d"scenarioNameNode" required\x3d"true" data-dojo-type\x3d"dijit/form/ValidationTextBox"\x3e\x3c/div\x3e\r\n        \x3cdiv style\x3d"width:120px" class\x3d"jimu-btn jimu-float-trailing jimu-leading-margin1" data-dojo-attach-point\x3d"addBtnNode" title\x3d"${nls.costingInfo.addBtnLabel}"\x3e${nls.costingInfo.addBtnLabel}\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\r\n    \x3cdiv\x3e\r\n        \x3cdiv class\x3d"esriCTAddScenarioNameTable" data-dojo-attach-point\x3d"addScenarioNameTableNode"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\r\n\x3c/div\x3e'}});
define("dojo/_base/declare jimu/dijit/Popup jimu/dijit/SimpleTable jimu/BaseWidget dojo/Evented dijit/_WidgetsInTemplateMixin dojo/text!./ManageScenarios.html dojo/_base/array dojo/_base/lang dojo/on dojo/query dojo/dom-attr".split(" "),function(k,l,m,n,p,q,r,e,c,t,f,g){return k([n,p,q],{templateString:r,popup:null,_addScenarioTable:null,baseClass:"jimu-widget-cost-analysis-manage-scenarios",constructor:function(a){c.mixin(this,a)},postMixInProperties:function(){this.nls.common={};c.mixin(this.nls.common,
window.jimuNls.common)},postCreate:function(){this._addScenarioTable=this.popup=null;this.inherited(arguments);this._init()},_init:function(){this._createManageScenarioTable();this._createManageScenarioPopup();this.own(t(this.addBtnNode,"click",c.hitch(this,function(){this.scenarioNameNode.set("value",this.scenarioNameNode.get("value").trim());this.scenarioNameNode.validate()?(this._addNewScenario(this._addScenarioTable.getRows().length+1,this.scenarioNameNode.get("value")),this.scenarioNameNode.set("value",
" ")):this.scenarioNameNode.focus()})));this.scenarioNameNode.validator=c.hitch(this,this._scenarioNameValidator);this.scenarioNameNode.focus()},_createManageScenarioPopup:function(){this.popup=new l({titleLabel:this.nls.costingInfo.manageScenarioLabel,content:this.domNode,width:500,height:400,autoHeight:!0,"class":this.baseClass,buttons:[{label:this.nls.common.ok,onClick:c.hitch(this,"onOkButtonClicked")}]})},onOkButtonClicked:function(){this.emit("okButtonClicked",this._addScenarioTable.getData());
this.popup.close()},_createManageScenarioTable:function(){this._addScenarioTable=new m({fields:[{name:"id",title:this.nls.costingInfo.srNoLabel,type:"text",editable:!1,width:"100px"},{name:"field",title:this.nls.costingInfo.scenarioNameLabel,type:"text",editable:!1,width:"200px"},{name:"actions",title:this.nls.costingInfo.deleteLabel,width:"100px",type:"actions",actions:["delete"]}],selectable:!1});this._addScenarioTable.placeAt(this.addScenarioNameTableNode);this._addScenarioTable.startup();this._populateExistingScenarios();
this._addScenarioTable.onBeforeRowDelete=c.hitch(this,function(a){var b,d;this._addScenarioTable.deleteRow(a);a=this._addScenarioTable.getRows();e.forEach(a,function(u,h){b=u.cells[0];d=f("div",b)[0];g.set(d,"innerHTML",h+1);g.set(d,"title",h+1)})})},_populateExistingScenarios:function(){e.forEach(this.existingScenarios,c.hitch(this,function(a,b){this._addNewScenario(b+1,a)}))},_addNewScenario:function(a,b){this._createRow(a,b)},_createRow:function(a,b){this._addScenarioTable.addRow({id:a,field:b})},
_scenarioNameValidator:function(a){return""===a?!1:0<this._addScenarioTable.getRowDataArrayByFieldValue("field",a).length?(this.scenarioNameNode.invalidMessage=this.nls.costingInfo.duplicateScenarioName,!1):!0},getUpdatedManageScenarios:function(){this._addScenarioTable.getRows();f(".simple-table-row",this._addScenarioTable);return[]}})});