// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/Evented dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/_base/lang dojo/_base/html dojo/on dojo/_base/Color dojo/query jimu/dijit/ColorChooser jimu/dijit/CustomColorPicker jimu/dijit/ColorRecords dijit/popup jimu/utils dijit/a11yclick".split(" "),function(g,h,k,l,m,e,b,f,c,n,p,q,r,t,u,v){return h([k,m,l,g],{templateString:"\x3cdiv\x3e\x3c/div\x3e",baseClass:"jimu-color-palette",declaredClass:"jimu.dijit.ColorPalette",_TRANSPARENT_STR:"rgba(0, 0, 0, 0)",
value:"",_defaultAppearance:{showTransparent:!0,showColorPalette:!0,showCoustom:!0,showColorPickerOK:!1,showColorPickerApply:!0,showCoustomRecord:!0,closeDialogWhenChange:!1},recordUID:"",postMixInProperties:function(){this.nls=window.jimuNls.colorPalette},postCreate:function(){this.inherited(arguments);this.value=this.value?new c(this.value):new c("#fff");this._createContent()},initUI:function(){this._toggleCustomColorPicker("init",!1)},_createContent:function(){this.appearance=e.mixin(this._defaultAppearance,
this.appearance);var a=b.create("div",{"class":"jimu-colorpalette"},this.domNode);this.initPanel=b.create("div",{"class":"init-panel"},a);this.customPanel=b.create("div",{"class":"custom-panel hide"},a);this.appearance.showTransparent&&this._createSpecialColors(this.initPanel);this.appearance.showColorPalette&&this._createColorChooser(this.initPanel);this.appearance.showCoustom&&this._createCustomColorPicker(this.initPanel);this.appearance.showCoustom&&this.appearance.showCoustomRecord&&this._createCoustomRecord(this.initPanel)},
setColor:function(a){this._isColorEqual(a)||(this.value=new c(a),this._setSpatialColor(this.value),"undefined"!==typeof this.value.a&&0===this.value.a?(this.colorChooser.setColor(new c("transparent"),!1),this.picker.setColor(new c("#fff"),!1)):(this.colorChooser.setColor(this.value.toHex(),!1),this.picker.setColor(this.value,!1)),this.colorRecords&&this.colorRecords.selecteColor(this.value))},getColor:function(){return this.value},changeColor:function(a){if("undefined"!==typeof this.value.a&&0===
this.value.a)this.onChange(this.value);else this.onChange(this.value.toHex());this.emit("change",this.value);!0===this.appearance.closeDialogWhenChange&&!1!==a&&this._closeDialog()},refreshRecords:function(){this.colorRecords&&this.colorRecords.refresh()},destroy:function(){t.close(this.tooltipDialog);this.picker.destroy();this.inherited(arguments)},_createSpecialColors:function(a){a=b.create("div",{"class":"special-color"},a);this.transparentBtn=b.create("div",{"class":"transparent btn",innerHTML:'\x3cdiv class\x3d"btn-wapper"\x3e\x3cdiv class\x3d"transparent icon jimu-float-leading"\x3e\x3c/div\x3e\x3cdiv class\x3d"transparent text jimu-float-leading"\x3e'+
this.nls.transparent+"\x3c/div\x3e\x3c/div\x3e"},a);this.own(f(this.transparentBtn,v,e.hitch(this,this._onTransparentClick)))},_onTransparentClick:function(){this.setColor(new c("transparent"));this.changeColor()},_setSpatialColor:function(a){if(this.transparentBtn){var d=n(".btn-wapper",this.transparentBtn)[0];b.removeClass(d,"selected");a&&a.toString&&a.toString()===this._TRANSPARENT_STR&&b.addClass(d,"selected")}},_createColorChooser:function(a){this.colorChooser=new p({});this.colorChooser.placeAt(a);
this.own(f(this.colorChooser,"change",e.hitch(this,function(d){d=new c(d);this.setColor(d);this.changeColor()})))},_createCustomColorPicker:function(){this.coustomtBtn=b.create("div",{"class":"coustom btn",innerHTML:'\x3cdiv class\x3d"btn-wapper"\x3e\x3cdiv class\x3d"custom icon jimu-float-leading"\x3e\x3c/div\x3e\x3cdiv class\x3d"custom text jimu-float-leading"\x3e'+this.nls.custom+"\x3c/div\x3e\x3c/div\x3e"},this.initPanel);this.own(f(this.coustomtBtn,"click",e.hitch(this,function(){this._toggleCustomColorPicker("custom")})));
this.picker=new q({showOk:this.appearance.showColorPickerOK,showApply:this.appearance.showColorPickerApply,value:this.value.toHex()});this.picker.placeAt(this.customPanel);this.picker.setColor(this.value);this.own(f(this.picker,"ok",e.hitch(this,function(a){this.setColor(new c(a));this.changeColor();this._addAColorRecord(a);this._toggleCustomColorPicker("init");this._closeDialog()})));this.own(f(this.picker,"apply",e.hitch(this,function(a){this.setColor(new c(a));this.changeColor(!1);this._addAColorRecord(a)})));
this.own(f(this.picker,"cancel",e.hitch(this,function(){this._toggleCustomColorPicker("init");this._closeDialog()})))},_toggleCustomColorPicker:function(a,d){"custom"===a?(b.removeClass(this.customPanel,"hide"),b.addClass(this.initPanel,"hide")):(b.addClass(this.customPanel,"hide"),b.removeClass(this.initPanel,"hide"));"undefined"!==typeof d&&!1===d||this.emit("change-style")},_createCoustomRecord:function(a){this.colorRecords=new r({recordsLength:10,uid:this.recordUID||""});this.colorRecords.placeAt(a);
this.own(f(this.colorRecords,"choose",e.hitch(this,function(d){this.setColor(new c(d));this.changeColor()})))},_addAColorRecord:function(a){this.colorRecords&&this.colorRecords.push&&this.colorRecords.push(a)},_isColorEqual:function(a){return this.value.toString()===(new c(a)).toString()?!0:!1},_changeLabel:function(a){b.empty(this.domNode);b.create("span",{innerHTML:a.toHex(),className:"color-label",style:{color:u.invertColor(a.toHex())}},this.domNode)},onOpen:function(){this.openDialog()},openDialog:function(){this.initUI()},
_closeDialog:function(){this.emit("close")},onClose:function(){this._closeDialog()}})});