// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:jimu/dijit/templates/FeatureSetChooserForMultipleLayers.html":'\x3cdiv class\x3d"jimu-not-selectable"\x3e\r\n  \x3cdiv class\x3d"draw-item-btn" tabindex\x3d"0"\x3e\r\n    \x3cdiv class\x3d"current-draw-item" data-dojo-attach-point\x3d"currentDrawItem"\x3e\r\n      \x3cdiv class\x3d"btn-select" data-dojo-attach-point\x3d"btnSelect"\x3e\r\n        \x3cdiv class\x3d"labels"\x3e\r\n            \x3cdiv class\x3d"feature-action" data-dojo-attach-point\x3d"geoTypeIcon"\x3e\x3c/div\x3e\r\n            \x3cdiv class\x3d"select-text"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv class\x3d"arrow feature-action icon-drop-down" data-dojo-attach-event\x3d"click:_onArrowClicked"\x3e\x3c/div\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"btn-clear" data-dojo-attach-point\x3d"btnClear" tabindex\x3d"0"\x3e\r\n    \x3cdiv class\x3d"feature-action icon-clear-selection"\x3e\x3c/div\x3e\x3cdiv class\x3d"clear-text"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/on dojo/sniff dojo/mouse dojo/query dojo/Evented dojo/_base/html dojo/_base/lang dojo/_base/array dojo/promise/all dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./templates/FeatureSetChooserForMultipleLayers.html dijit/popup dijit/TooltipDialog jimu/utils jimu/dijit/DrawBox jimu/dijit/_FeatureSetChooserCore jimu/SelectionManager jimu/dijit/FeatureActionPopupMenu".split(" "),function(g,z,q,m,A,c,b,h,B,C,D,E,F,G,r,v,p,H,I,J,K){return C([D,
E,F,A],{baseClass:"jimu-multiple-layers-featureset-chooser",declaredClass:"jimu.dijit.FeatureSetChooserForMultipleLayers",templateString:G,drawBox:null,_instances:null,_tooltipDialogTimeoutId1:-1,_tooltipDialogClientX1:-1,_tooltipDialogTimeoutId2:-1,_tooltipDialogClientX2:-1,_tooltipTimeout:1E3,_currentGeoTypeInfo:null,_geoTypeInfos:null,map:null,updateSelection:!1,fullyWithin:!1,geoTypes:null,actions:null,postMixInProperties:function(){this.inherited(arguments);this.nls=window.jimuNls.featureSetChooser;
var a="POINT EXTENT POLYGON CIRCLE POLYLINE FREEHAND_POLYGON".split(" ");this.geoTypes&&0<this.geoTypes.length&&(this.geoTypes=h.filter(this.geoTypes,b.hitch(this,function(d){return 0<=a.indexOf(d)})));this.geoTypes&&0!==this.geoTypes.length||(this.geoTypes=["EXTENT"])},postCreate:function(){this.inherited(arguments);this._instances=[];this.popupMenu=K.getInstance();m(".select-text",this.domNode)[0].innerHTML=this.nls.select;m(".clear-text",this.domNode)[0].innerHTML=window.jimuNls.common.clear;this._initTooltipDialogs();
this._initDrawBox();this._geoTypeInfos=[];this.actions=[];0===this.geoTypes.length&&this.geoTypes.push("EXTENT");1===this.geoTypes.length?c.addClass(this.domNode,"single-geotype"):c.addClass(this.domNode,"multiple-geotypes");var a={POINT:["icon-select-by-point",this.nls.selectByPoint,this.drawBox.pointIcon],EXTENT:["icon-select-by-rect",this.nls.selectByRectangle,this.drawBox.extentIcon],POLYGON:["icon-select-by-polygon",this.nls.selectByPolygon,this.drawBox.polygonIcon],CIRCLE:["icon-select-by-circle",
this.nls.selectByCircle,this.drawBox.circleIcon],POLYLINE:["icon-select-by-line",this.nls.selectByLine,this.drawBox.polylineIcon],FREEHAND_POLYGON:["icon-select-by-freehand-polygon",this.nls.selectByFreehandPolygon,this.drawBox.freehandPolygonIcon]},d=-1;h.forEach("POINT EXTENT POLYGON CIRCLE POLYLINE FREEHAND_POLYGON".split(" "),b.hitch(this,function(f){var e=a[f];if(0<=this.geoTypes.indexOf(f)){var n={geoType:f,action:{iconClass:e[0],label:e[1],data:{}},dom:e[2]};e={iconClass:e[0],label:e[1],data:{},
onExecute:b.hitch(this,this._onDrawItemClicked,n)};this._geoTypeInfos.push(n);this.actions.push(e);"EXTENT"===f&&(d=this._geoTypeInfos.length-1)}}));this.own(g(this.btnSelect,"click",b.hitch(this,function(){p.simulateClickEvent(this._currentGeoTypeInfo.dom);this._hideDrawItems()})));0<=d?(this._setCurrentGeoInfo(this._geoTypeInfos[d]),c.addClass(this.geoTypeIcon,"icon-select-by-rect")):(this._setCurrentGeoInfo(this._geoTypeInfos[0]),c.addClass(this.geoTypeIcon,this._geoTypeInfos[0].action.iconClass));
this.deactivate()},_initTooltipDialogs:function(){var a=z("mac")?"\u2318":"Ctrl",d="- "+this.nls.newSelectionTip+" ("+this.nls.dragMouse+")",f="- "+this.nls.addSelectionTip+" (Shift+"+this.nls.dragBox+")",e="- "+this.nls.removeSelectionTip+" ("+a+"+"+this.nls.dragBox+")",n="- "+this.nls.newSelectionTip+" ("+this.nls.drawShap+")",t="- "+this.nls.addSelectionTip+" (Shift+"+this.nls.darw+")",u="- "+this.nls.removeSelectionTip+" ("+a+"+"+this.nls.darw+")";a=c.create("div",{innerHTML:'\x3cdiv class\x3d"title"\x3e\x3c/div\x3e\x3cdiv class\x3d"item new-selection-item"\x3e\x3c/div\x3e\x3cdiv class\x3d"item add-selection-item"\x3e\x3c/div\x3e\x3cdiv class\x3d"item remove-selection-item"\x3e\x3c/div\x3e',
"class":"dialog-content"});var l=m(".title",a)[0],w=m(".new-selection-item",a)[0],x=m(".add-selection-item",a)[0],y=m(".remove-selection-item",a)[0];this.tooltipDialog1=new v({content:a});c.addClass(this.tooltipDialog1.domNode,"jimu-multiple-layers-featureset-chooser-tooltipdialog");this.own(g(this.btnSelect,"mousemove",b.hitch(this,function(k){this._tooltipDialogClientX1=k.clientX})));this.own(g(this.btnSelect,q.enter,b.hitch(this,function(){clearTimeout(this._tooltipDialogTimeoutId1);this._tooltipDialogTimeoutId1=
-1;this._tooltipDialogTimeoutId1=setTimeout(b.hitch(this,function(){if(this.tooltipDialog1){var k=this._currentGeoTypeInfo.geoType;"EXTENT"===k?(w.innerHTML=d,x.innerHTML=f,y.innerHTML=e,l.innerHTML=this.nls.selectByRectangle):(w.innerHTML=n,x.innerHTML=t,y.innerHTML=u,"POLYGON"===k?l.innerHTML=this.nls.selectByPolygon:"CIRCLE"===k?l.innerHTML=this.nls.selectByCircle:"POLYLINE"===k?l.innerHTML=this.nls.selectByLine:"FREEHAND_POLYGON"===k?l.innerHTML=this.nls.selectByFreehandPolygon:"POINT"===k&&(l.innerHTML=
this.nls.selectByPoint));r.open({parent:this.getParent(),popup:this.tooltipDialog1,around:this.btnSelect,position:["below"]});0<=this._tooltipDialogClientX1&&(this.tooltipDialog1.domNode.parentNode.style.left=this._tooltipDialogClientX1+"px")}}),this._tooltipTimeout)})));this.own(g(this.btnSelect,q.leave,b.hitch(this,function(){clearTimeout(this._tooltipDialogTimeoutId1);this._tooltipDialogTimeoutId1=-1;this._hideTooltipDialog(this.tooltipDialog1)})));a=c.create("div",{innerHTML:this.nls.unselectAllSelectionTip,
"class":"dialog-content"});this.tooltipDialog2=new v({content:a});c.addClass(this.tooltipDialog2.domNode,"jimu-multiple-layers-featureset-chooser-tooltipdialog");this.own(g(this.btnClear,"mousemove",b.hitch(this,function(k){this._tooltipDialogClientX2=k.clientX})));this.own(g(this.btnClear,q.enter,b.hitch(this,function(){clearTimeout(this._tooltipDialogTimeoutId2);this._tooltipDialogTimeoutId2=-1;this._tooltipDialogTimeoutId2=setTimeout(b.hitch(this,function(){this.tooltipDialog2&&(r.open({parent:this.getParent(),
popup:this.tooltipDialog2,around:this.btnClear,position:["below"]}),0<=this._tooltipDialogClientX2&&(this.tooltipDialog2.domNode.parentNode.style.left=this._tooltipDialogClientX2+"px"))}),this._tooltipTimeout)})));this.own(g(this.btnClear,q.leave,b.hitch(this,function(){clearTimeout(this._tooltipDialogTimeoutId2);this._tooltipDialogTimeoutId2=-1;this._hideTooltipDialog(this.tooltipDialog2)})))},_onArrowClicked:function(a){a.stopPropagation();a=c.position(a.target);this._showDrawItems(a)},_setCurrentGeoInfo:function(a){var d=
this._currentGeoTypeInfo&&this._currentGeoTypeInfo.geoType;this._currentGeoTypeInfo&&c.removeClass(this.currentDrawItem,this._currentGeoTypeInfo.geoType);this._currentGeoTypeInfo=a;c.addClass(this.currentDrawItem,this._currentGeoTypeInfo.geoType);this.isActive()?d!==this._currentGeoTypeInfo.geoType&&p.simulateClickEvent(this._currentGeoTypeInfo.dom):p.simulateClickEvent(this._currentGeoTypeInfo.dom)},_showDrawItems:function(a){this.popupMenu.setActions(this.actions);this.popupMenu.markAsSelected(this._currentGeoTypeInfo.action);
this.popupMenu.show(a)},_hideDrawItems:function(){this.popupMenu.hide()},_onDrawItemClicked:function(a){this._hideDrawItems();this._setCurrentGeoInfo(a);c.removeClass(this.geoTypeIcon,"icon-select-by-point icon-select-by-circle icon-select-by-rect icon-select-by-polygon icon-select-by-line icon-select-by-freehand-polygon".split(" "));switch(a.geoType){case "POLYGON":c.addClass(this.geoTypeIcon,"icon-select-by-polygon");break;case "CIRCLE":c.addClass(this.geoTypeIcon,"icon-select-by-circle");break;
case "POLYLINE":c.addClass(this.geoTypeIcon,"icon-select-by-line");break;case "FREEHAND_POLYGON":c.addClass(this.geoTypeIcon,"icon-select-by-freehand-polygon");break;case "POINT":c.addClass(this.geoTypeIcon,"icon-select-by-point");break;default:c.addClass(this.geoTypeIcon,"icon-select-by-rect")}},_initDrawBox:function(){this.drawBox=new H({map:this.map,showClear:!0,keepOneGraphic:!0,deactivateAfterDrawing:!1,geoTypes:this.geoTypes});this.own(g(this.drawBox,"user-clear",b.hitch(this,this._onDrawBoxUserClear)));
this.own(g(this.drawBox,"draw-end",b.hitch(this,this._onDrawEnd)));this.own(g(this.drawBox,"draw-activate",b.hitch(this,function(){this.map.infoWindow.hide();c.addClass(this.currentDrawItem,"pressed");c.addClass(this.btnSelect,"selected")})));this.own(g(this.drawBox,"draw-deactivate",b.hitch(this,function(){c.removeClass(this.currentDrawItem,"pressed");c.removeClass(this.btnSelect,"selected")})));this.own(g(this.btnClear,"click",b.hitch(this,function(){p.simulateClickEvent(this.drawBox.btnClear)})))},
disable:function(){this.drawBox.disable();c.addClass(this.domNode,"disabled")},enable:function(){this.drawBox.enable();c.removeClass(this.domNode,"disabled")},isActive:function(){return this.drawBox.isActive()},activate:function(){if(!this.isActive()){var a=this._currentGeoTypeInfo;a||(a=this._geoTypeInfos[0]);this._setCurrentGeoInfo(a)}},deactivate:function(){this.drawBox.deactivate()},setFeatureLayers:function(a){var d=h.filter(this._instances,b.hitch(this,function(e){return 0>a.indexOf(e.featureLayer)}));
h.forEach(d,b.hitch(this,function(e){this._removeInstance(e)}));var f=h.map(this._instances,b.hitch(this,function(e){return e.featureLayer}));h.forEach(a,b.hitch(this,function(e){0>f.indexOf(e)&&this.addFeatureLayer(e)}))},addFeatureLayer:function(a){"esri.layers.FeatureLayer"!==a.declaredClass||this._findInstanceByLayer(a)||(a=new I({map:this.map,featureLayer:a,drawBox:this.drawBox,updateSelection:this.updateSelection,fullyWithin:this.fullyWithin}),this._instances.push(a))},removeFeatureLayer:function(a){"esri.layers.FeatureLayer"===
a.declaredClass&&(a=this._findInstanceByLayer(a))&&this._removeInstance(a)},setDisplayLayerVisibility:function(a,d){(a=J.getInstance().getDisplayLayer(a.id))&&(d?a.show():a.hide())},_removeInstance:function(a){if(a){var d=this._instances.indexOf(a);0<=d&&(a.destroy(),this._instances.splice(d,1))}},_findInstanceByLayer:function(a){var d=null;h.some(this._instances,b.hitch(this,function(f){return f.featureLayer===a?(d=f,!0):!1}));return d},clear:function(a){h.forEach(this._instances,b.hitch(this,function(d){d.clear(a)}))},
destroy:function(){this._hideTooltipDialog(this.tooltipDialog1);this._hideTooltipDialog(this.tooltipDialog2);h.forEach(this._instances,b.hitch(this,function(a){a.destroy()}));this._instances=[];this.drawBox&&this.drawBox.destroy();this.drawBox=null;this.inherited(arguments)},_hideTooltipDialog:function(a){a&&r.close(a)},_onDrawBoxUserClear:function(){this.clear(!0);this.emit("user-clear")},_onDrawEnd:function(a,d,f,e,n,t){this.drawBox.clear();0<this._instances.length&&setTimeout(b.hitch(this,function(){if(0<
this._instances.length){this.emit("loading");this.disable();var u=h.map(this._instances,b.hitch(this,function(l){return l.getFeatures()}));B(u).always(b.hitch(this,function(){this.enable();this._currentGeoTypeInfo&&p.simulateClickEvent(this._currentGeoTypeInfo.dom);this.emit("unloading",a,d,f,e,n,t)}))}}),50)}})});