// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Analysis/setting/SingleToolSetting.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"control-section jimu-leading-margin3"\x3e\r\n    \x3clabel class\x3d"jimu-widget-normal"\x3e${nls.toolLabel}\x26nbsp;:\x3c/label\x3e\r\n    \x3cinput data-dojo-attach-point\x3d"labelEditor" data-dojo-type\x3d"dijit/form/ValidationTextBox"\r\n           data-dojo-props\x3d\'required:true,trim:true\'/\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"control-section jimu-leading-margin3"\x3e\r\n    \x3cdiv class\x3d"control-option" data-dojo-attach-point\x3d"helpTipOption"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"control-option" data-dojo-attach-point\x3d"mapExtentOption"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"control-option" data-dojo-attach-point\x3d"creditsOption"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"control-option" data-dojo-attach-point\x3d"resultOption"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"control-option" data-dojo-attach-point\x3d"readyToUseLayersOption"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"control-option" data-dojo-attach-point\x3d"allowToExportOption"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"control-option" data-dojo-attach-point\x3d"showOutputTypeOption"\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dojo/text!./SingleToolSetting.html dojo/dom-style dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin jimu/portalUrlUtils jimu/dijit/CheckBox dijit/form/ValidationTextBox".split(" "),function(f,g,b,h,k,l,d,c){return f([h,k,l],{baseClass:"jimu-widget-analysis-singleToolSetting",templateString:g,toolLabel:null,nls:null,config:null,rowData:null,livingAtlasConfigEnabled:!1,postCreate:function(){this.inherited(arguments);this.labelEditor.set("value",this.toolLabel);
"extractData"===this.rowData.title&&b.set(this.resultOption,"display","none");"planRoutes"!==this.rowData.title&&"findNearest"!==this.rowData.title&&"connectOriginsToDestinations"!==this.rowData.title&&b.set(this.showOutputTypeOption,"display","none");this.helptipChk=new c({checked:!0,label:this.nls.showHelpTip});this.helptipChk.placeAt(this.helpTipOption);this.mapExtentChk=new c({checked:!0,label:this.nls.showCurrentMapExtent});this.mapExtentChk.placeAt(this.mapExtentOption);this.creditsChk=new c({checked:!0,
label:this.nls.showCredits});this.creditsChk.placeAt(this.creditsOption);this.resultChk=new c({checked:!0,label:this.nls.saveAsFeatureService});this.resultChk.placeAt(this.resultOption);this.livingAtlasConfigEnabled?(this.readyToUseLayersChk=new c({checked:!0,label:this.nls.showReadyToUseLayers}),this.readyToUseLayersChk.placeAt(this.readyToUseLayersOption),b.set(this.readyToUseLayersOption,"display","block")):b.set(this.readyToUseLayersOption,"display","none");this.allowToExportChk=new c({checked:!1,
label:this.nls.allowToExport});this.allowToExportChk.placeAt(this.allowToExportOption);this.showOutputTypeChk=new c({checked:!1,label:this.nls.includeRouteLayer});this.showOutputTypeChk.placeAt(this.showOutputTypeOption);var a=d.getStandardPortalUrl(this.appConfig.portalUrl);if(!d.isOnline(a)||0<=["createViewshed","createWatershed","traceDownstream"].indexOf(this.rowData.title))b.set(this.creditsOption,"display","none"),this.creditsChk.setValue(!1);"geocodeLocations"===this.rowData.title&&(b.set(this.mapExtentOption,
"display","none"),this.mapExtentChk.setValue(!1),b.set(this.resultOption,"display","none"),this.resultChk.setValue(!1))},getConfig:function(){var a={showHelp:this.helptipChk.getValue(),showCredits:this.creditsChk.getValue(),showChooseExtent:this.mapExtentChk.getValue(),showReadyToUseLayers:this.livingAtlasConfigEnabled?this.readyToUseLayersChk.getValue():!1,allowToExport:this.allowToExportChk.getValue()};"extractData"!==this.rowData.title&&(a.returnFeatureCollection=!this.resultChk.getValue());if("planRoutes"===
this.rowData.title||"findNearest"===this.rowData.title||"connectOriginsToDestinations"===this.rowData.title)a.showOutputType=this.showOutputTypeChk.getValue();if(this.labelEditor.validate()){var e=this.labelEditor.get("value");e!==this.toolLabel&&(a.toolLabel=e)}return a},setConfig:function(a){this.config=a;a.toolLabel&&this.labelEditor.set("value",a.toolLabel);this.helptipChk.setValue(!!a.showHelp);this.creditsChk.setValue(!!a.showCredits);this.mapExtentChk.setValue(!!a.showChooseExtent);this.livingAtlasConfigEnabled&&
this.readyToUseLayersChk.setValue(!!a.showReadyToUseLayers);this.allowToExportChk.setValue(!!a.allowToExport);"returnFeatureCollection"in a&&this.resultChk.setValue(!a.returnFeatureCollection);"showOutputType"in a&&this.showOutputTypeChk.setValue(!!a.showOutputType)}})});