// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ParcelDrafter/setting/nls/strings":{setBtnLabel:"Set",selectLabel:"Select",selectLayerLabel:"Select Parcel Layers",selectLayerHintText:"Hint: Use set button to select the parcel polygon and its related line layer",layerSelector:{selectedLayerNotHavingRelatedLayer:"Selected polygon layer doesn't have a valid related layer."},parcelLineLayer:{selectLayerLabel:"Select Related Line Layer",layerSettingTabLabel:"Parcel Layers",attributeSettingTabLabel:"Attribute Settings",advancedSettingTabLabel:"Advanced Settings",
selectLayerHintText:"Hint: Use to store COGO values in parcel line layer",selectFieldLegendLabel:"Select fields to store COGO values in parcel line layer",bearingFieldLabel:"Bearing",chordLengthFieldLabel:"Chord Length",distanceFieldLabel:"Distance",sequenceIdFieldLabel:"Sequence ID",radiusFieldLabel:"Radius",foreignKeyFieldLabel:"Foreign Key",arcLengthFieldLabel:"Arc Length",lineTypeFieldLabel:"Line Type",parcelPointSymbolLabel:"Parcel Point Symbol",parcelPointSymbolHintText:"Hint: Used to display point symbol for the origin of the line.",
startOrRotationSymbolLabel:"Start and Rotate Point Symbol",startOrRotationSymbolHintText:"Hint: Used to display start and rotate point symbol.",symbolPickerPreviewText:"Preview",selectLineLayerLabel:"Select Line Layer"},parcelPolygonLayer:{selectPolygonLayerLabel:"Select Polygon Layer",selectPolygonLayerHintText:"Hint: Use the select parcel polygon layer",selectFieldLegendLabel:"Select fields to store coordinate geometry information",parcelNameLabel:"Parcel Name",rotationLabel:"Rotation",planNameLabel:"Plan Name",
scalingLabel:"Scaling",documentTypeLabel:"Document Type",miscloseRatioLabel:"Misclose Ratio",statedAreaLabel:"Stated Area",miscloseDistanceLabel:"Misclose Distance",selectPolygonLayerLabelPopUp:"Select a Polygon Layer",honorSettingRbLabel:"Webmap Popup Settings",customSettingsRbLabel:"Custom Settings",display:"Display",edit:"Edit",editpageName:"Name",actions:"Actions",editpageAlias:"Alias",titleLabel:"Section Title"},lineTypesTable:{lineTypeLabel:"Line Type",valueLabel:"Value",symbolLabel:"Symbol",
connectionLineLabel:"Connection Line",boundaryLineLabel:"Boundary Line"},closureSetting:{snappingLayerLabel:"Snapping Layers",snappingBtnLabel:"Set",snappingLayerHintText:"Hint: Select layers to which the parcel lines will snap.",miscloseDistanceLabel:"Misclose Distance",miscloseDistanceHintText:"Hint: Specify misclose distance and its units.",miscloseRatioLabel:"Misclose Ratio",miscloseRatioHintText:"Hint: Specify misclose ratio.",snappingToleranceLabel:"Snapping Tolerance",pixelLabel:"Pixels",snappingToleranceHintText:"Hint: Specify snapping tolerance.",
selectLayerLabel:"Select layer"},errorMsg:{bearingFieldErrMsg:"Invalid Bearing Field",chordLengthErrMsg:"Invalid ChordLength",distanceFieldErrMsg:"Invalid Distance",sequenceIdFieldErrMsg:"Invalid sequenceId",radiusFieldErrMsg:"Invalid Radius",foreignKeyFieldErrMsg:"Invalid Foreign Key",arcLengthFieldErrMsg:"Invalid Arc Length",lineTypeFieldErrMsg:"Invalid Line Type",parcelNameFieldErrMsg:"Invalid Parcel Name Field",planNameFieldErrMsg:"Invalid Plan Name Field",scaleFieldErrMsg:"Invalid Scale Field",
documentTypeFieldErrMsg:"Invalid Document Type Field",miscloseRatioFieldErrMsg:"Invalid Misclose Ratio Field",statedAreaFieldErrMsg:"Invalid Stated Area Field",miscloseDistanceFieldErrMsg:"Invalid Misclose Distance Field",globalIdFieldErrMsg:"Selected polygon layer doesn't have valid 'esriFieldTypeGlobalID' field.",invalidPolylineLayer:"Please select valid parcel polyline layer",invalidPolygonLayer:"Please select valid parcel polygon layer",invalidMiscloseDistance:"Please enter valid misclose distance",
invalidSnappingTolerance:"Please enter valid snapping tolerance",invalidMiscloseRatio:"Please enter valid misclose ratio",selectDistinctLineTypes:"Please select distinct value in each line type",invalidConnectionLineType:"Invalid connection line value",invalidBoundaryLineType:"Invalid boundary line value",selectDistinctPolylineFields:"Please select distinct field for each COGO value.",selectDistinctPolygonFields:"Please select distinct field for each coordinate geometry information."},_localized:{}}});