// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Lihavointi",copy:"Kopioi",cut:"Leikkaa","delete":"Poista",indent:"Sisenn\u00e4",insertHorizontalRule:"Vaakasuuntainen viiva",insertOrderedList:"Numeroitu luettelo",insertUnorderedList:"Numeroimaton luettelo",italic:"Kursivointi",justifyCenter:"Tasaus keskelle",justifyFull:"Tasaus",justifyLeft:"Tasaus vasemmalle",justifyRight:"Tasaus oikealle",outdent:"Ulonna",paste:"Liit\u00e4",redo:"Tee uudelleen",removeFormat:"Poista muotoilu",selectAll:"Valitse kaikki",
strikethrough:"Yliviivaus",subscript:"Alennettu",superscript:"Korotettu",underline:"Alleviivaus",undo:"Kumoa",unlink:"Poista linkki",createLink:"Luo linkki",toggleDir:"Vaihda suuntaa",insertImage:"Lis\u00e4\u00e4 kuva",insertTable:"Lis\u00e4\u00e4 taulukko/muokkaa taulukkoa",toggleTableBorder:"Ota taulukon kehys k\u00e4ytt\u00f6\u00f6n/poista kehys k\u00e4yt\u00f6st\u00e4",deleteTable:"Poista taulukko",tableProp:"Taulukon ominaisuudet",htmlToggle:"HTML-l\u00e4hde",foreColor:"Edustav\u00e4ri",hiliteColor:"Taustav\u00e4ri",
plainFormatBlock:"Kappaletyyli",formatBlock:"Kappaletyyli",fontSize:"Fonttikoko",fontName:"Fontin nimi",tabIndent:"Sarkainsisennys",fullScreen:"Vaihda koko n\u00e4ytt\u00f6",viewSource:"N\u00e4yt\u00e4 HTML-l\u00e4hde",print:"Tulosta",newPage:"Uusi sivu",systemShortcut:'Toiminto "${0}" on k\u00e4ytett\u00e4viss\u00e4 selaimessa vain n\u00e4pp\u00e4imist\u00f6n pikatoiminnolla. K\u00e4yt\u00e4 seuraavaa: ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Koko",
fontName:"Fontti",formatBlock:"Muotoile",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Ei mit\u00e4\u00e4n",p:"Kappale",h1:"Otsikko",h2:"Alatason otsikko",h3:"Alimman tason otsikko",pre:"Esimuotoiltu",1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Esikatselu",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Etsi:",findTooltip:"Anna etsitt\u00e4v\u00e4 teksti",
replaceLabel:"Korvaa seuraavalla:",replaceTooltip:"Anna korvaava teksti",findReplace:"Etsi ja korvaa",matchCase:"Sama kirjainkoko",matchCaseTooltip:"Sama kirjainkoko",backwards:"Taaksep\u00e4in",backwardsTooltip:"Etsi teksti\u00e4 taaksep\u00e4in",replaceAllButton:"Korvaa kaikki",replaceAllButtonTooltip:"Korvaa kaikki teksti",findButton:"Etsi",findButtonTooltip:"Etsi teksti",replaceButton:"Korvaa",replaceButtonTooltip:"Korvaa teksti",replaceDialogText:"Korvattu ${0} esiintym\u00e4\u00e4.",eofDialogText:"Viimeinen esiintym\u00e4 ${0}",
eofDialogTextFind:"l\u00f6ytynyt",eofDialogTextReplace:"korvattu",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Liit\u00e4 Word-ohjelmasta",instructions:"Liit\u00e4 sis\u00e4lt\u00f6 Word-tiedostosta alla olevaan tekstikentt\u00e4\u00e4n. Kun lis\u00e4tt\u00e4v\u00e4 sis\u00e4lt\u00f6 on mielest\u00e4si valmis, napsauta Liit\u00e4-painiketta. Voit peruuttaa lis\u00e4yksen napsauttamalla Peruuta-painiketta.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Lis\u00e4\u00e4 ankkuri",
title:"Ankkurin ominaisuudet",anchor:"Nimi:",text:"Kuvaus:",set:"Aseta",cancel:"Peruuta",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Valitse menetelm\u00e4, jolla joukkop\u00e4ivitett\u00e4v\u00e4t tietueet valitaan.",selectToolDesc:"T\u00e4m\u00e4 pienoisohjelma tukee kolmea eri menetelm\u00e4\u00e4, joilla p\u00e4ivitett\u00e4vien tietueiden joukko voidaan luoda. Voit valita vain yhden menetelmist\u00e4. Jos tarvitset useamman kuin yhden n\u00e4ist\u00e4 kolmesta menetelm\u00e4st\u00e4, luo pienoisohjelmasta uusi ilmentym\u00e4.",
selectByShape:"Valitse alueen mukaan",shapeTypeSelector:"Napsauta ty\u00f6kaluja, jotka haluat sallia",shapeType:{point:"Piste",line:"Viiva",polyline:"Taiteviiva",freehandPolyline:"Vapaak\u00e4denpiirto, viiva",extent:"Laajuus",polygon:"Aluekohde",freehandPolygon:"Vapaank\u00e4den alue"},freehandPolygon:"Vapaank\u00e4den alue",selectBySpatQuery:"Valitse kohteen mukaan",selectByAttQuery:"Valitse kohteen ja liittyvien kohteiden mukaan",selectByQuery:"Valitse kyselyn mukaan",toolNotSelected:"Valitse valintamenetelm\u00e4",
noDrawToolSelected:"Valitse v\u00e4hint\u00e4\u00e4n yksi piirtoty\u00f6kalu"},page2:{layersToolHeader:"Valitse p\u00e4ivitett\u00e4v\u00e4t karttatasot ja mahdolliset valintaty\u00f6kalut.",layersToolDesc:"Ensimm\u00e4isell\u00e4 sivulla valitsemaasi valintamenetelm\u00e4\u00e4 k\u00e4ytet\u00e4\u00e4n alla lueteltujen karttatasojen valitsemiseen ja p\u00e4ivitt\u00e4miseen. Jos valitset useita karttatasoja, vain yleiset muokattavat kent\u00e4t voidaan p\u00e4ivitt\u00e4\u00e4. Valitsemasi valintaty\u00f6kalun mukaan joudut ehk\u00e4 valitsemaan lis\u00e4asetuksia.",
layerTable:{colUpdate:"P\u00e4ivit\u00e4",colLabel:"Karttataso",colSelectByLayer:"Valitse karttatason mukaan",colSelectByField:"Kyselykentt\u00e4",colhighlightSymbol:"Korostussymboli"},toggleLayers:"Vaihda karttatasojen n\u00e4kyvyytt\u00e4 avattaessa ja suljettaessa",noEditableLayers:"Ei muokattavia karttatasoja",noLayersSelected:"Valitse v\u00e4hint\u00e4\u00e4n yksi karttataso ennen jatkamista."},page3:{commonFieldsHeader:"Valitse joukkop\u00e4ivitett\u00e4v\u00e4t kent\u00e4t.",commonFieldsDesc:"Alla n\u00e4kyv\u00e4t vain yleiset muokattavat kent\u00e4t. Valitse p\u00e4ivitett\u00e4v\u00e4t kent\u00e4t. Jos eri karttatasojen samalla kent\u00e4ll\u00e4 on eri domain, n\u00e4ytet\u00e4\u00e4n ja k\u00e4ytet\u00e4\u00e4n vain yht\u00e4 domainia.",
noCommonFields:"Ei yleisi\u00e4 kentti\u00e4",fieldTable:{colEdit:"Muokattavissa",colName:"Nimi",colAlias:"Alias",colAction:"Toimet"}},tabs:{selection:"M\u00e4\u00e4rit\u00e4 valintatyyppi",layers:"M\u00e4\u00e4rit\u00e4 p\u00e4ivitett\u00e4v\u00e4t karttatasot",fields:"M\u00e4\u00e4rit\u00e4 p\u00e4ivitett\u00e4v\u00e4t kent\u00e4t"},errorOnOk:"Anna kaikki parametrit ennen kokoonpanon tallentamista",next:"Seuraava",back:"Takaisin",save:"Tallenna symboli",cancel:"Peruuta",ok:"OK",symbolPopup:"Symbolin valitsin",
editHeaderText:"Pienoisohjelman yl\u00e4reunassa n\u00e4ytett\u00e4v\u00e4 teksti",widgetIntroSelectByArea:"K\u00e4yt\u00e4 jotakin alla olevista ty\u00f6kaluista p\u00e4ivitett\u00e4v\u00e4n, valitun kohdejoukon luontia varten. Jos rivi on \x3cfont class\x3d'maxRecordInIntro'\x3ekorostettu\x3c/font\x3e, tietueiden enimm\u00e4ism\u00e4\u00e4r\u00e4 on ylittynyt.",widgetIntroSelectByFeature:"K\u00e4yt\u00e4 alla olevaa ty\u00f6kalua kohteen valitsemiseen kohteesta \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. T\u00e4t\u00e4 kohdetta k\u00e4ytet\u00e4\u00e4n kaikkien leikkaavien kohteiden valitsemiseen ja p\u00e4ivitt\u00e4miseen. Jos rivi on \x3cfont class\x3d'maxRecordInIntro'\x3ekorostettu\x3c/font\x3e, tietueiden enimm\u00e4ism\u00e4\u00e4r\u00e4 on ylittynyt.",
widgetIntroSelectByFeatureQuery:"K\u00e4yt\u00e4 alla olevaa ty\u00f6kalua kohteen valitsemiseen kohteesta \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. T\u00e4m\u00e4n kohteen \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e ominaisuustietoa k\u00e4ytet\u00e4\u00e4n alla olevien karttatasojen kyselyyn ja tuloksena syntyvien kohteiden p\u00e4ivitt\u00e4miseen. Jos rivi on \x3cfont class\x3d'maxRecordInIntro'\x3ekorostettu\x3c/font\x3e, tietueiden enimm\u00e4ism\u00e4\u00e4r\u00e4 on ylittynyt.",
widgetIntroSelectByQuery:"Luo valintajoukko antamalla arvo. Jos rivi on \x3cfont class\x3d'maxRecordInIntro'\x3ekorostettu\x3c/font\x3e, tietueiden enimm\u00e4ism\u00e4\u00e4r\u00e4 on ylittynyt.",_localized:{}}});