// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Podebljano",copy:"Kopiraj",cut:"Iseci","delete":"Izbri\u0161i",indent:"Uvla\u010denje ",insertHorizontalRule:"Horizontalna linija vodilja",insertOrderedList:"Numerisana lista",insertUnorderedList:"Lista sa znakovima za nabrajanje",italic:"Kurzivno",justifyCenter:"Poravnaj po centru",justifyFull:"Poravnaj obostrano",justifyLeft:"Poravnaj levo",justifyRight:"Poravnaj desno",outdent:"Izvla\u010denje",paste:"Nalepi",redo:"Ponovi radnju",removeFormat:"Ukloni format",
selectAll:"Izaberi sve",strikethrough:"Precrtani tekst",subscript:"Indeksni tekst",superscript:"Eksponentni tekst",underline:"Podvu\u010deno",undo:"Opozovi radnju",unlink:"Ukloni link",createLink:"Kreiraj link",toggleDir:"Uklju\u010di/isklju\u010di smer",insertImage:"Umetni sliku",insertTable:"Umetni/uredi tabelu",toggleTableBorder:"Uklju\u010di/isklju\u010di ivicu tabele",deleteTable:"Izbri\u0161i tabelu",tableProp:"Svojstva tabele",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",
plainFormatBlock:"Stil pasusa",formatBlock:"Stil pasusa",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",tabIndent:"Uvla\u010denje kartice",fullScreen:"Uklju\u010di/isklju\u010di prikaz preko celog ekrana",viewSource:"Prika\u017ei HTML izvor",print:"\u0160tampaj",newPage:"Nova stranica",systemShortcut:"Radnja \u201e${0}\u201c je dostupna u pregleda\u010du samo pomo\u0107u tasterskih pre\u010dica. Koristite ${1}.",ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Veli\u010dina",
fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"jednorazma\u010dni",cursive:"kurziv",fantasy:"fantazija",noFormat:"Bez formata",p:"Pasus",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Preformatirano",1:"xx-malo",2:"x-malo",3:"malo",4:"srednje",5:"veliko",6:"x-veliko",7:"xx-veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Prona\u0111i:",findTooltip:"Unesite tekst koji treba prona\u0107i",
replaceLabel:"Zameni sa:",replaceTooltip:"Unesite zamenski tekst",findReplace:"Prona\u0111i i zameni",matchCase:"Podudaranje malih i velikih slova",matchCaseTooltip:"Podudaranje malih i velikih slova",backwards:"Unazad",backwardsTooltip:"Pretra\u017eite tekst unazad",replaceAllButton:"Zameni sve",replaceAllButtonTooltip:"Zamenjuje sav tekst",findButton:"Prona\u0111i",findButtonTooltip:"Prona\u0111ite tekst",replaceButton:"Zameni",replaceButtonTooltip:"Zamenite tekst",replaceDialogText:"Zamenjeno ${0} pojava.",
eofDialogText:"Poslednja pojava ${0}",eofDialogTextFind:"prona\u0111eno",eofDialogTextReplace:"zamenjeno",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Nalepi iz programa Word",instructions:"Nalepite sadr\u017eaj iz programa Word u okvir za tekst ispod.  Kada ste zadovoljni sa sadr\u017eajem za umetanje, kliknite na dugme Nalepi.  Da otka\u017eete umetanje teksta, kliknite na dugme Otka\u017ei.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",
title:"Svojstva sidra",anchor:"Ime:",text:"Opis:",set:"Podesi",cancel:"Otka\u017ei",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Citat pasusa",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Odaberite metod za izbor zapisa za grupno a\u017euriranje.",selectToolDesc:"Vid\u017eet podr\u017eava 3 metode za generisanje izabranog seta podataka za a\u017euriranje. Mo\u017eete da odaberete samo jednu od metoda. Ako zahtevate vi\u0161e od jedne, kreirajte novu instancu vid\u017eeta.",
selectByShape:"Selektuj po povr\u0161ini",shapeTypeSelector:"Kliknite na alatke koje \u017eelite da omogu\u0107ite",shapeType:{point:"Ta\u010dka",line:"Linija",polyline:"Poligon",freehandPolyline:"Poligon slobodnom rukom",extent:"Obuhvat",polygon:"Polilinija",freehandPolygon:"Polilinija slobodnom rukom"},freehandPolygon:"Poligon slobodnom rukom",selectBySpatQuery:"Selektuj po geoobjektu",selectByAttQuery:"Selektuj po geoobjektu i povezanim geoobjektima",selectByQuery:"Selektuj po upitu",toolNotSelected:"Izaberite metod selekcije",
noDrawToolSelected:"Odaberite barem jednu alatku za crtanje"},page2:{layersToolHeader:"Selektuj slojeve za a\u017euriranje i opcije alatki za selekciju, ako treba.",layersToolDesc:"Odabrani metod selekcije na prvoj stranici \u0107e biti kori\u0161\u0107en za selektovanje i a\u017euriranje seta slojeva navedenih ispod. Ako proveravate vi\u0161e od jednog sloja, samo zajedni\u010dka polja koja mogu da se menjaju \u0107e biti dostupna za a\u017euriranje. U zavisnosti od izbora alatke za selekciju, dodatne opcije \u0107e biti obavezne.",
layerTable:{colUpdate:"A\u017euriraj",colLabel:"Sloj",colSelectByLayer:"Selektuj po sloju",colSelectByField:"Polje upita",colhighlightSymbol:"Simbol za isticanje"},toggleLayers:"Uklju\u010di/isklju\u010di vidljivost slojeva na otvaranju i zatvaranju",noEditableLayers:"Nema slojeva koji mogu da se izmene",noLayersSelected:"Izaberite jedan ili vi\u0161e slojeva pre nastavka."},page3:{commonFieldsHeader:"Izaberite polja za grupno a\u017euriranje.",commonFieldsDesc:"Samo zajedni\u010dka polja koja mogu da se ure\u0111uju \u0107e biti prikazana ispod. Izaberite polja koja \u017eelite da a\u017eurirate. Ako je isto polje iz razli\u010ditih slojeva ima razli\u010dit domen, samo jedan domen \u0107e biti prikazan i kori\u0161\u0107en.",
noCommonFields:"Nema zajedni\u010dkih polja",fieldTable:{colEdit:"Mo\u017ee da se izmeni",colName:"Naziv",colAlias:"Pseudonim",colAction:"Radnje"}},tabs:{selection:"Defini\u0161i tip selekcije",layers:"Defini\u0161i sloj(eve) za a\u017euriranje",fields:"Defini\u0161i polje(-a) za a\u017euriranje"},errorOnOk:"Popunite sve parametre pre \u010duvanja konfiguracije",next:"Slede\u0107e",back:"Nazad",save:"Sa\u010duvaj simbol",cancel:"Otka\u017ei",ok:"U redu",symbolPopup:"Izbornik simbola",editHeaderText:"Tekst za prikaz u gornjem delu vid\u017eeta",
widgetIntroSelectByArea:"Koristite jedan od alata ispod za kreiranje selektovanog seta geoobjekata za a\u017euriranje.  Ako je red \x3cfont class\x3d'maxRecordInIntro'\x3eistaknut\x3c/font\x3e, maksimalan broj zapisa je prema\u0161en.",widgetIntroSelectByFeature:"Upotrebite alat ispod da biste izabrali komponentu iz \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e sloja. Ovaj geoobjekat \u0107e se koristiti da selektuje i a\u017eurira sve geoobjekte koji se presecaju. Ako je ovaj red \x3cfont class\x3d'maxRecordInIntro'\x3eozna\u010den\x3c/font\x3e, maksimalni broj zapisa je prekora\u010den.",
widgetIntroSelectByFeatureQuery:"Koristite alatku ispod da biste selektovali geoobjekat iz \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e.  Atribut \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e ovog geoobjekta \u0107e biti kori\u0161\u0107eni da vr\u0161e upit slojeva ispod i a\u017euriraju rezultiraju\u0107e geoobjekte.  Ako je red \x3cfont class\x3d'maxRecordInIntro'\x3eistaknut\x3c/font\x3e, maksimalan broj zapisa je prema\u0161en.",widgetIntroSelectByQuery:"Unesite vrednost da biste kreirali skup izbora.  Ako je red \x3cfont class\x3d'maxRecordInIntro'\x3eistaknut\x3c/font\x3e, maksimalan broj zapisa je prema\u0161en.",
_localized:{}}});