// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Halvfet",copy:"Kopiera",cut:"Klipp ut","delete":"Ta bort",indent:"Indrag",insertHorizontalRule:"Horisontell linje",insertOrderedList:"Numrerad lista",insertUnorderedList:"Punktlista",italic:"Kursiv",justifyCenter:"Centrera",justifyFull:"Marginaljustera",justifyLeft:"V\u00e4nsterjustera",justifyRight:"H\u00f6gerjustera",outdent:"Utdrag",paste:"Klistra in",redo:"G\u00f6r om",removeFormat:"Ta bort format",selectAll:"Markera allt",strikethrough:"Genomstruken",
subscript:"Neds\u00e4nkt",superscript:"Upph\u00f6jt",underline:"Understruken",undo:"\u00c5ngra",unlink:"Ta bort l\u00e4nk",createLink:"Skapa l\u00e4nk",toggleDir:"V\u00e4xla riktning",insertImage:"Infoga bild",insertTable:"Infoga/redigera tabell",toggleTableBorder:"V\u00e4xla tabellinjer",deleteTable:"Ta bort tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-k\u00e4llkod",foreColor:"F\u00f6rgrundsf\u00e4rg",hiliteColor:"Bakgrundsf\u00e4rg",plainFormatBlock:"Styckeformat",formatBlock:"Styckeformat",
fontSize:"Teckenstorlek",fontName:"Teckensnitt",tabIndent:"Tabbindrag",fullScreen:"V\u00e4xla helsk\u00e4rm",viewSource:"Visa HTML-kod",print:"Skriv ut",newPage:"Ny sida",systemShortcut:"\u00c5tg\u00e4rden ${0} \u00e4r endast tillg\u00e4nglig i webbl\u00e4saren via ett tangentbordskommando. Anv\u00e4nd ${1}.",ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Storlek ",fontName:"Teckensnitt",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",
monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Inget",p:"Stycke",h1:"Rubrik 1",h2:"Rubrik 2",h3:"Rubrik 3",pre:"F\u00f6rformaterad",1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"F\u00f6rhandsgranskning",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f6k: ",findTooltip:"Skriv s\u00f6ktexten",replaceLabel:"Ers\u00e4tt med:",replaceTooltip:"Skriv ers\u00e4ttningstexten",findReplace:"S\u00f6k och ers\u00e4tt",
matchCase:"Matcha gemener/versaler",matchCaseTooltip:"Matcha gemener/versaler",backwards:"Bak\u00e5t",backwardsTooltip:"S\u00f6k bak\u00e5t efter text",replaceAllButton:"Ers\u00e4tt alla",replaceAllButtonTooltip:"Ers\u00e4tt all text",findButton:"S\u00f6k",findButtonTooltip:"S\u00f6k efter texten",replaceButton:"Er\u00e4tt",replaceButtonTooltip:"Ers\u00e4tt texten",replaceDialogText:"${0} f\u00f6rekomster har ersatts.",eofDialogText:"Sista f\u00f6rekomsten ${0}",eofDialogTextFind:"hittades",eofDialogTextReplace:"ersattes",
_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Klistra in fr\u00e5n Word",instructions:"Klistra in inneh\u00e5llet fr\u00e5n Word i textrutan nedan. N\u00e4r du har valt inneh\u00e5ll klickar du p\u00e5 Klistra in. Klicka p\u00e5 Avbryt om du inte vill klistra in text. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Infoga ankare",title:"Ankaregenskaper",anchor:"Namn:",text:"Beskrivning:",set:"Anv\u00e4nd",cancel:"Avbryt",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockcitat",
_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"V\u00e4lj en metod f\u00f6r att markera poster som ska uppdateras i grupp.",selectToolDesc:"Denna widget st\u00f6der tre metoder som kan anv\u00e4ndas f\u00f6r att generera ett urval poster som ska uppdateras. Du kan bara v\u00e4lja en av metoderna. Om du vill anv\u00e4nda fler \u00e4n en av metoderna, m\u00e5ste du skapa en ny instans av widgeten.",selectByShape:"Markera efter omr\u00e5de",shapeTypeSelector:"Klicka p\u00e5 de verktyg du vill till\u00e5ta",
shapeType:{point:"Punkt",line:"Linje",polyline:"Polylinje",freehandPolyline:"Frihandspolylinje",extent:"Utbredning",polygon:"Polygon",freehandPolygon:"Frihandspolygon"},freehandPolygon:"Frihandspolygon",selectBySpatQuery:"Markera efter geoobjekt",selectByAttQuery:"Markera efter geoobjekt och relaterade geoobjekt",selectByQuery:"Markera efter fr\u00e5ga",toolNotSelected:"Markera en urvalsmetod",noDrawToolSelected:"V\u00e4lj minst ett ritverktyg"},page2:{layersToolHeader:"Markera de lager som ska uppdateras och v\u00e4lj eventuella urvalsverktyg.",
layersToolDesc:"Urvalsmetoden du valde p\u00e5 sidan ett anv\u00e4nds f\u00f6r att markera och uppdatera den upps\u00e4ttning lager som visas nedan. Om du markerar fler \u00e4n ett lager kommer bara de gemensamt redigerbara f\u00e4lten att vara tillg\u00e4ngliga f\u00f6r uppdatering. Beroende p\u00e5 vilket urvalsverktyg du v\u00e4ljer kan det kr\u00e4vas fler alternativ.",layerTable:{colUpdate:"Uppdatera",colLabel:"Lager",colSelectByLayer:"V\u00e4lj enligt lager",colSelectByField:"Fr\u00e5gef\u00e4lt",
colhighlightSymbol:"Markeringssymbol"},toggleLayers:"Sl\u00e5 p\u00e5/av lagersynlighet vid \u00f6ppning och st\u00e4ngning",noEditableLayers:"Inga redigerbara lager",noLayersSelected:"Markera ett eller flera lager innan du forts\u00e4tter."},page3:{commonFieldsHeader:"Markera f\u00e4lten som ska uppdateras i grupp.",commonFieldsDesc:"Bara de gemensamt redigerbara f\u00e4lten visas nedan. Markera de f\u00e4lt som du vill uppdatera. Om samma f\u00e4lt fr\u00e5n olika lager har olika dom\u00e4n, visas och anv\u00e4nds bara en dom\u00e4n.",
noCommonFields:"Inga gemensamma f\u00e4lt",fieldTable:{colEdit:"Redigerbar",colName:"Namn",colAlias:"Alias",colAction:"\u00c5tg\u00e4rder"}},tabs:{selection:"Definiera markeringstyp",layers:"Definiera lager som ska uppdateras",fields:"Definiera f\u00e4lt som ska uppdateras"},errorOnOk:"Fyll i alla parametrar innan du sparar konfigurationen",next:"N\u00e4sta",back:"Bakom",save:"Spara symbol",cancel:"Avbryt",ok:"OK",symbolPopup:"Symbolv\u00e4ljaren",editHeaderText:"Text som ska visas l\u00e4ngst upp i widgeten",
widgetIntroSelectByArea:"Anv\u00e4nd n\u00e5got av verktygen nedan f\u00f6r att skapa en markerad upps\u00e4ttning geoobjekt som ska uppdateras. Om raden \u00e4r \x3cfont class\x3d'maxRecordInIntro'\x3emarkerad\x3c/font\x3e har det maximala antalet poster uppn\u00e5tts.",widgetIntroSelectByFeature:"Anv\u00e4nd verktyget nedan f\u00f6r att v\u00e4lja ett geoobjekt fr\u00e5n \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e-lagret. Den h\u00e4r funktionen anv\u00e4nds f\u00f6r att markera och uppdatera alla korsande geoobjekt. Om raden \u00e4r \x3cfont class\x3d'maxRecordInIntro'\x3emarkerad\x3c/font\x3e har det maximala antalet poster uppn\u00e5tts.",
widgetIntroSelectByFeatureQuery:"Anv\u00e4nd verktyget nedan f\u00f6r att v\u00e4lja ett geoobjekt fr\u00e5n \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Det h\u00e4r geoobjektets \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e attribut anv\u00e4nds f\u00f6r att s\u00f6ka i lagren nedan och uppdatera de resulterande geoobjekten. Om raden \u00e4r \x3cfont class\x3d'maxRecordInIntro'\x3emarkerad\x3c/font\x3e har det maximala antalet poster uppn\u00e5tts.",widgetIntroSelectByQuery:"Ange ett v\u00e4rde f\u00f6r att skapa en markeringsupps\u00e4ttning. Om raden \u00e4r \x3cfont class\x3d'maxRecordInIntro'\x3emarkerad\x3c/font\x3e har det maximala antalet poster uppn\u00e5tts.",
_localized:{}}});