// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negrito",copy:"Copiar",cut:"Cortar","delete":"Eliminar",indent:"Indentar",insertHorizontalRule:"R\u00e9gua horizontal",insertOrderedList:"Lista numerada",insertUnorderedList:"Lista marcada",italic:"It\u00e1lico",justifyCenter:"Alinhar ao centro",justifyFull:"Justificar",justifyLeft:"Alinhar \u00e0 esquerda",justifyRight:"Alinhar \u00e0 direita",outdent:"Recuar",paste:"Colar",redo:"Repetir",removeFormat:"Remover formato",selectAll:"Seleccionar tudo",strikethrough:"Rasurado",
subscript:"Inferior \u00e0 linha",superscript:"Superior \u00e0 linha",underline:"Sublinhado",undo:"Anular",unlink:"Remover liga\u00e7\u00e3o",createLink:"Criar liga\u00e7\u00e3o",toggleDir:"Alternar direc\u00e7\u00e3o",insertImage:"Inserir imagem",insertTable:"Inserir/Editar tabela",toggleTableBorder:"Alternar contorno da tabela",deleteTable:"Eliminar tabela",tableProp:"Propriedades da tabela",htmlToggle:"Origem HTML",foreColor:"Cor de primeiro plano",hiliteColor:"Cor de segundo plano",plainFormatBlock:"Estilo de par\u00e1grafo",
formatBlock:"Estilo de par\u00e1grafo",fontSize:"Tamanho do tipo de letra",fontName:"Nome do tipo de letra",tabIndent:"Indentar com a tecla Tab",fullScreen:"Alternar ecr\u00e3 completo",viewSource:"Ver origem HTML",print:"Imprimir",newPage:"Nova p\u00e1gina",systemShortcut:'A ac\u00e7\u00e3o "${0}" apenas est\u00e1 dispon\u00edvel no navegador utilizando um atalho de teclado. Utilize ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Tamanho",
fontName:"Tipo de letra",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Nenhum",p:"Par\u00e1grafo",h1:"T\u00edtulo",h2:"Sub-t\u00edtulo",h3:"Sub-subt\u00edtulo",pre:"Pr\u00e9-formatado",1:"xxs",2:"xs",3:"small",4:"medium",5:"large",6:"xl",7:"xxl",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pr\u00e9-visualizar",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Localizar:",findTooltip:"Introduzir texto a localizar",
replaceLabel:"Substituir por:",replaceTooltip:"Introduzir texto de substitui\u00e7\u00e3o",findReplace:"Localizar e substituir",matchCase:"Correspond\u00eancia de mai\u00fasculas/min\u00fasculas",matchCaseTooltip:"Correspond\u00eancia de mai\u00fasculas/min\u00fasculas",backwards:"Para tr\u00e1s",backwardsTooltip:"Procura de texto para tr\u00e1s",replaceAllButton:"Substituir tudo",replaceAllButtonTooltip:"Substituir todo o texto",findButton:"Localizar",findButtonTooltip:"Localizar o texto",replaceButton:"Substituir",
replaceButtonTooltip:"Substituir o texto",replaceDialogText:"Foram substitu\u00eddas ${0} ocorr\u00eancias.",eofDialogText:"\u00daltima ocorr\u00eancia ${0}",eofDialogTextFind:"localizado",eofDialogTextReplace:"substitu\u00eddo",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Colar do Word",instructions:"Cole o conte\u00fado do Word na caixa de texto abaixo. Ap\u00f3s estar satisfeito com o conte\u00fado a inserir, prima o bot\u00e3o de colagem. Para cancelar a inser\u00e7\u00e3o de texto, prima o bot\u00e3o de cancelamento.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserir \u00e2ncora",title:"Propriedades da \u00e2ncora",anchor:"Nome:",text:"Descri\u00e7\u00e3o:",set:"Definir",cancel:"Cancelar",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Escolha um m\u00e9todo para selecionar registos para atualiza\u00e7\u00e3o em batch.",selectToolDesc:"O widget suporta 3 m\u00e9todos para gerar um conjunto selecionado de registos para atualizar. Pode escolher apenas um dos m\u00e9todos. Se necessitar de mais do que um destes m\u00e9todos, crie uma nova inst\u00e2ncia do widget.",
selectByShape:"Selecionar por \u00c1rea",shapeTypeSelector:"Clique nas ferramentas que deseja autorizar",shapeType:{point:"Ponto",line:"Linha",polyline:"Polilinha",freehandPolyline:"Polilinha \u00c0 M\u00e3o Livre",extent:"Extens\u00e3o:",polygon:"Pol\u00edgono",freehandPolygon:"Pol\u00edgono \u00c0 M\u00e3o Livre"},freehandPolygon:"Pol\u00edgono \u00c0 M\u00e3o Livre",selectBySpatQuery:"Selecionar por Elemento",selectByAttQuery:"Selecionar por Elemento \x26amp; Elementos Relacionados",selectByQuery:"Selecionar por Consulta",
toolNotSelected:"Por favor escolha um m\u00e9todo de sele\u00e7\u00e3o",noDrawToolSelected:"Escolha pelo menos uma ferramenta de desenho"},page2:{layersToolHeader:"Selecione as camadas a atualizar e as op\u00e7\u00f5es de ferramentas de sele\u00e7\u00e3o, se alguma.",layersToolDesc:"O m\u00e9todo de sele\u00e7\u00e3o que escolheu na p\u00e1gina um ser\u00e1 utilizado para escolher e atualizar um conjunto de camadas listadas abaixo.  Se selecionar mais do que uma camada, apenas os campos comuns edit\u00e1veis estar\u00e3o dispon\u00edveis para atualizar.  Dependendo da sua escolha de ferramenta de sele\u00e7\u00e3o, ser\u00e3o necess\u00e1rias op\u00e7\u00f5es adicionais.",
layerTable:{colUpdate:"Atualiza\u00e7\u00e3o",colLabel:"Camada",colSelectByLayer:"Selecionar por Camada",colSelectByField:"Consultar Campo",colhighlightSymbol:"Destacar S\u00edmbolo"},toggleLayers:"Alternar a visibilidade das camadas de abrir e fechar",noEditableLayers:"Sem Camadas Edit\u00e1veis",noLayersSelected:"Seleccionar uma ou mais camadas antes de prosseguir."},page3:{commonFieldsHeader:"Selecione os campos para atualiza\u00e7\u00e3o em batch.",commonFieldsDesc:"Apenas os campos edit\u00e1veis comuns ser\u00e3o exibidos abaixo.  Por favor, selecione os campos que pretende atualizar.  Se o mesmo campo de diferentes camadas tiver um dom\u00ednio diferente, apenas um dom\u00ednio ser\u00e1 exibido e utilizado.",
noCommonFields:"Sem Campos Comuns",fieldTable:{colEdit:"Edit\u00e1vel",colName:"Nome",colAlias:"Nome Alternativo",colAction:"Ac\u00e7\u00f5es"}},tabs:{selection:"Sefinir Tipo de Sele\u00e7\u00e3o",layers:"Definir Camada(s) a Atualizar",fields:"Definir Campo(s) a Atualizar"},errorOnOk:"Por favor, preencha todos os par\u00e2metros antes de guardar a configura\u00e7\u00e3o",next:"Seguinte",back:"Retroceder",save:"Guardar S\u00edmbolo",cancel:"Cancelar",ok:"OK",symbolPopup:"Seletor de S\u00edmbolos",
editHeaderText:"Texto a exibir na parte superior do widget",widgetIntroSelectByArea:"Utilize uma das ferramentas abaixo para criar um conjunto selecionado de elementos a atualizar. Se a linha estiver \x3cfont class\x3d'maxRecordInIntro'\x3ereal\u00e7ada\x3c/font\x3e, o n\u00famero m\u00e1ximo de registos foi excedido.",widgetIntroSelectByFeature:"Use a ferramenta abaixo para selecionar um elemento a partir da camada \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Este elemento ser\u00e1 utilizado para selecionar e atualizar todos os elementos de intersec\u00e7\u00e3o. Se a linha estiver \x3cfont class\x3d'maxRecordInIntro'\x3edestacada\x3c/font\x3e, o n\u00famero m\u00e1ximo de registos foi excedido.",
widgetIntroSelectByFeatureQuery:"Utilize a ferramenta abaixo para selecionar um elemento a partir de \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e . Este atributo \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e do elemento ser\u00e1 utilizado para consultar as camadas abaixo e atualizar os elementos resultantes. Se a linha estiver \x3cfont class\x3d'maxRecordInIntro'\x3ereal\u00e7ada\x3c/font\x3e, o n\u00famero m\u00e1ximo de registos foi excedido.",widgetIntroSelectByQuery:"Introduza um valor para criar um conjunto de sele\u00e7\u00f5es. Se a linha estiver \x3cfont class\x3d'maxRecordInIntro'\x3ereal\u00e7ada\x3c/font\x3e, o n\u00famero m\u00e1ximo de registos foi excedido.",
_localized:{}}});