// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Gras",copy:"Copier",cut:"Couper","delete":"Supprimer",indent:"Retrait",insertHorizontalRule:"R\u00e8gle horizontale",insertOrderedList:"Liste num\u00e9rot\u00e9e",insertUnorderedList:"Liste \u00e0 puces",italic:"Italique",justifyCenter:"Aligner au centre",justifyFull:"Justifier",justifyLeft:"Aligner \u00e0 gauche",justifyRight:"Aligner \u00e0 droite",outdent:"Retrait n\u00e9gatif",paste:"Coller",redo:"R\u00e9tablir",removeFormat:"Supprimer la mise en forme",
selectAll:"S\u00e9lectionner tout",strikethrough:"Barrer",subscript:"Indice",superscript:"Exposant",underline:"Souligner",undo:"Annuler",unlink:"Supprimer le lien",createLink:"Cr\u00e9er un lien",toggleDir:"Changer de sens",insertImage:"Ins\u00e9rer une image",insertTable:"Ins\u00e9rer/Modifier un tableau",toggleTableBorder:"Afficher/Masquer la bordure du tableau",deleteTable:"Supprimer le tableau",tableProp:"Propri\u00e9t\u00e9 du tableau",htmlToggle:"Source HTML",foreColor:"Couleur avant-plan",
hiliteColor:"Couleur arri\u00e8re-plan",plainFormatBlock:"Style de paragraphe",formatBlock:"Style de paragraphe",fontSize:"Taille de police",fontName:"Nom de police",tabIndent:"Retrait de tabulation",fullScreen:"Basculer en plein \u00e9cran",viewSource:"Afficher la source HTML",print:"Imprimer",newPage:"Nouvelle page",systemShortcut:'Action "${0}" uniquement disponible dans votre navigateur via un raccourci clavier. Utilisez ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Taille",
fontName:"Police",formatBlock:"Mise en forme",serif:"serif","sans-serif":"sans serif",monospace:"espacement fixe",cursive:"cursive",fantasy:"fantaisie",noFormat:"N\u00e9ant",p:"Paragraphe",h1:"En-t\u00eate",h2:"Sous-en-t\u00eate",h3:"Sous-sous-en-t\u00eate",pre:"Pr\u00e9-mise en forme",1:"tr\u00e8s tr\u00e8s petite",2:"tr\u00e8s petite",3:"petite",4:"moyenne",5:"grande",6:"tr\u00e8s grande",7:"tr\u00e8s tr\u00e8s grande",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Aper\u00e7u",_localized:{}},
"dojox/editor/plugins/nls/FindReplace":{findLabel:"Rechercher :",findTooltip:"Entrez le texte \u00e0 rechercher",replaceLabel:"Remplacer par :",replaceTooltip:"Entrez le texte de remplacement",findReplace:"Rechercher et remplacer",matchCase:"Respecter la casse",matchCaseTooltip:"Respecter la casse",backwards:"Vers l'arri\u00e8re",backwardsTooltip:"Recherchez le texte vers l'arri\u00e8re",replaceAllButton:"Remplacer tout",replaceAllButtonTooltip:"Remplacez tout le texte",findButton:"Rechercher",findButtonTooltip:"Recherchez le texte",
replaceButton:"Remplacer",replaceButtonTooltip:"Remplacez le texte",replaceDialogText:"${0} occurrence(s) remplac\u00e9e(s)",eofDialogText:"Derni\u00e8re occurrence ${0}",eofDialogTextFind:"trouv\u00e9",eofDialogTextReplace:"remplac\u00e9",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Coller depuis Word",instructions:"Collez le contenu Word dans la zone de texte ci-dessous. Quand le contenu \u00e0 ins\u00e9rer vous convient, appuyez sur le bouton Coller. Pour annuler l'insertion du texte, utilisez le bouton Annuler.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Ins\u00e9rer un point d'ancrage",title:"Propri\u00e9t\u00e9s du point d'ancrage",anchor:"Nom :",text:"Description :",set:"D\u00e9finir",cancel:"Annuler",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Bloc de citation",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Choisissez une m\u00e9thode de s\u00e9lection des enregistrements \u00e0 mettre \u00e0 jour par lots.",
selectToolDesc:"Le widget accepte 3\u00a0m\u00e9thodes pour g\u00e9n\u00e9rer un ensemble s\u00e9lectionn\u00e9 d'enregistrements \u00e0 mettre \u00e0 jour. Vous ne pouvez choisir qu'une m\u00e9thode. Si vous devez en choisir plusieurs, cr\u00e9ez une nouvelle instance du widget.",selectByShape:"S\u00e9lectionner par zone",shapeTypeSelector:"Cliquez sur les outils \u00e0 autoriser",shapeType:{point:"Point",line:"Ligne",polyline:"Polyligne",freehandPolyline:"Polyligne \u00e0 main lev\u00e9e",extent:"Etendue",
polygon:"Surface",freehandPolygon:"Polygone \u00e0 main lev\u00e9e"},freehandPolygon:"Polygone \u00e0 main lev\u00e9e",selectBySpatQuery:"S\u00e9lectionner par entit\u00e9",selectByAttQuery:"S\u00e9lectionner par entit\u00e9 et entit\u00e9s associ\u00e9es",selectByQuery:"S\u00e9lectionner par requ\u00eate",toolNotSelected:"Choisissez une m\u00e9thode de s\u00e9lection",noDrawToolSelected:"S\u00e9lectionnez au moins un outil de dessin"},page2:{layersToolHeader:"S\u00e9lectionnez les couches \u00e0 mettre \u00e0 jour et les options des outils de s\u00e9lection, le cas \u00e9ch\u00e9ant.",
layersToolDesc:"La m\u00e9thode de s\u00e9lection que vous avez choisie sur la page sera utilis\u00e9e pour s\u00e9lectionner et mettre \u00e0 jour le jeu de couches r\u00e9pertori\u00e9 ci-dessous.  Si vous s\u00e9lectionnez plusieurs couches, seuls les champs modifiables communs peuvent \u00eatre mis \u00e0 jour.  Selon l'outil de s\u00e9lection choisi, des options suppl\u00e9mentaires peuvent \u00eatre requises.",layerTable:{colUpdate:"Mise \u00e0 jour",colLabel:"Couche",colSelectByLayer:"S\u00e9lectionner par couche",
colSelectByField:"Champ de requ\u00eate",colhighlightSymbol:"Symbole de surbrillance\u00a0:"},toggleLayers:"Activer/d\u00e9sactiver la visibilit\u00e9 des couches lors de l\u2019ouverture et de la fermeture",noEditableLayers:"Aucune couche modifiable",noLayersSelected:"S\u00e9lectionnez une ou plusieurs couches avant de continuer."},page3:{commonFieldsHeader:"S\u00e9lectionnez les champs \u00e0 mettre \u00e0 jour par lots.",commonFieldsDesc:"Seuls les champs modifiables communs sont pr\u00e9sent\u00e9s ci-dessous.  S\u00e9lectionnez les champs que vous souhaitez mettre \u00e0 jour.  Si le m\u00eame champ issu de diff\u00e9rentes couches poss\u00e8de un domaine diff\u00e9rent, un seul domaine est affich\u00e9 et utilis\u00e9.",
noCommonFields:"Aucun champ commun",fieldTable:{colEdit:"Modifiable",colName:"Nom",colAlias:"Alias",colAction:"Actions"}},tabs:{selection:"D\u00e9finir le type de s\u00e9lection",layers:"D\u00e9finir les couches \u00e0 mettre \u00e0 jour",fields:"D\u00e9finir les champs \u00e0 mettre \u00e0 jour"},errorOnOk:"Renseignez tous les param\u00e8tres avant d'enregistrer la configuration",next:"Suivant",back:"Retour",save:"Enregistrer le symbole",cancel:"Annuler",ok:"OK",symbolPopup:"S\u00e9lecteur de symboles",
editHeaderText:"Texte \u00e0 afficher en haut du widget",widgetIntroSelectByArea:"Utilisez un des outils ci-dessous pour cr\u00e9er un ensemble de s\u00e9lection d\u2019entit\u00e9s \u00e0 mettre \u00e0 jour. Si la ligne est \x3cfont class\x3d'maxRecordInIntro'\x3emise en surbrillance\x3c/font\x3e, le nombre maximal d\u2019enregistrements autoris\u00e9s a \u00e9t\u00e9 d\u00e9pass\u00e9.",widgetIntroSelectByFeature:"Utilisez l\u2019outil ci-dessous pour s\u00e9lectionner une entit\u00e9 dans la couche \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Cette entit\u00e9 sera utilis\u00e9e pour s\u00e9lectionner et mettre \u00e0 jour toutes les entit\u00e9s d\u2019intersection. Si la ligne est \x3cfont class\x3d'maxRecordInIntro'\x3emise en surbrillance\x3c/font\x3e, le nombre maximal d\u2019enregistrements autoris\u00e9 a \u00e9t\u00e9 d\u00e9pass\u00e9.",
widgetIntroSelectByFeatureQuery:"Utilisez l\u2019outil ci-dessous pour s\u00e9lectionner une entit\u00e9 sur \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e . L\u2019attribut \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e de cette entit\u00e9 sera utilis\u00e9 pour interroger les couches ci-dessous et mettre \u00e0 jour les entit\u00e9s obtenues. Si la ligne est \x3cfont class\x3d'maxRecordInIntro'\x3emise en surbrillance\x3c/font\x3e, le nombre maximal d\u2019enregistrements autoris\u00e9s a \u00e9t\u00e9 d\u00e9pass\u00e9.",
widgetIntroSelectByQuery:"Saisissez une valeur pour cr\u00e9er un jeu de s\u00e9lection. Si la ligne est \x3cfont class\x3d'maxRecordInIntro'\x3emise en surbrillance\x3c/font\x3e, le nombre maximal d\u2019enregistrements autoris\u00e9s a \u00e9t\u00e9 d\u00e9pass\u00e9.",_localized:{}}});