// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Rasvane",copy:"Kopeeri",cut:"L\u00f5ika","delete":"Kustuta",indent:"Paremtaane",insertHorizontalRule:"Horisontaaljoon",insertOrderedList:"Nummerdatud loend",insertUnorderedList:"T\u00e4pploend",italic:"Kursiiv",justifyCenter:"Keskjoondus",justifyFull:"R\u00f6\u00f6pjoondus",justifyLeft:"Vasakjoondus",justifyRight:"Paremjoondus",outdent:"Vasaktaane",paste:"Kleebi",redo:"Tee uuesti",removeFormat:"Eemalda vorming",selectAll:"Vali k\u00f5ik",strikethrough:"L\u00e4bikriipsutus",
subscript:"Allindeks",superscript:"\u00dclaindeks",underline:"Allajoonitud",undo:"T\u00fchista",unlink:"Eemalda link",createLink:"Loo link",toggleDir:"Vaheta suund",insertImage:"Sisesta pilt",insertTable:"Lisa/muuda tabelit",toggleTableBorder:"L\u00fclita tabeli\u00e4\u00e4ris sisse/v\u00e4lja",deleteTable:"Kustuta tabel",tableProp:"Tabeli atribuut",htmlToggle:"HTML-l\u00e4htetekst",foreColor:"Esiv\u00e4rv",hiliteColor:"Taustav\u00e4rv",plainFormatBlock:"L\u00f5igu laad",formatBlock:"L\u00f5igu laad",
fontSize:"Fondi suurus",fontName:"Fondi nimi",tabIndent:"Tabeldustaane",fullScreen:"L\u00fclita t\u00e4isekraan sisse/v\u00e4lja",viewSource:"Kuva HTML-l\u00e4htetekst",print:"Prindi",newPage:"Uus leht",systemShortcut:"Seda toimingut ${0} saab Teie brauseris teha ainult kiirklahvi abil. Kasutage klahvikombinatsiooni ${1}.",ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Suurus",fontName:"Font",formatBlock:"Formaat",serif:"seriifidega","sans-serif":"groteskkiri",
monospace:"p\u00fcsisamm",cursive:"kursiiv",fantasy:"fantaasia",noFormat:"Puudub",p:"L\u00f5ik",h1:"Pealkiri",h2:"Alapealkiri",h3:"Ala-alapealkiri",pre:"Eelvormindatud",1:"eriti v\u00e4ike",2:"v\u00e4ga v\u00e4ike",3:"v\u00e4ike",4:"keskmine",5:"suur",6:"v\u00e4ga suur",7:"eriti suur",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",
findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},
"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",
_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Valige meetod, millega valida kirjed lausaliseks uuendamiseks.",selectToolDesc:"Vidin toetab 3 meetodit uuendatavate kirjete valitud komplekti loomiseks. Saate valida ainult \u00fche nendest meetoditest. Kui vajate mitut meetodit, looge uus vidina eksemplar.",selectByShape:"Vali ala j\u00e4rgi",shapeTypeSelector:"Klikkige t\u00f6\u00f6riistadel, mida soovite lubada",shapeType:{point:"Punkt",line:"Joon",polyline:"Murdjoon",
freehandPolyline:"Vabak\u00e4e joon",extent:"Kuvaulatus",polygon:"Pol\u00fcgoon",freehandPolygon:"Vabak\u00e4e pol\u00fcgoon"},freehandPolygon:"Vabak\u00e4e pol\u00fcgoon",selectBySpatQuery:"Vali objekti j\u00e4rgi",selectByAttQuery:"Vali objekti ja seotud objektide j\u00e4rgi",selectByQuery:"Vali p\u00e4ringu kaudu",toolNotSelected:"Valige sobilik meetod",noDrawToolSelected:"Valige v\u00e4hemalt \u00fcks joonistust\u00f6\u00f6riist"},page2:{layersToolHeader:"Valige v\u00e4rskendatavad kihid ja valikut\u00f6\u00f6riistade suvandid (kui neid leidub).",
layersToolDesc:"Esimesel lehel valitud meetodit kasutatakse allpool loetletud kihtide komplekti valimiseks ja v\u00e4rskendamiseks. Kui m\u00e4rgite mitu kihti, on v\u00e4rskendamiseks saadaval ainult \u00fchised muudetavad v\u00e4ljad. Olenevalt teie valitud valikut\u00f6\u00f6riistast v\u00f5idakse n\u00f5uda t\u00e4iendavaid suvandeid.",layerTable:{colUpdate:"Uuenda",colLabel:"Kiht",colSelectByLayer:"Vali kihi j\u00e4rgi",colSelectByField:"P\u00e4ringuv\u00e4li",colhighlightSymbol:"T\u00f5sta s\u00fcmbol esile"},
toggleLayers:"Saate kihtide n\u00e4htavuse sisse ja v\u00e4lja l\u00fclitada",noEditableLayers:"Muudetavaid kihte pole",noLayersSelected:"Enne j\u00e4tkamist valige v\u00e4hemalt \u00fcks kiht."},page3:{commonFieldsHeader:"Valige hulgiv\u00e4rskenduseks v\u00e4ljad.",commonFieldsDesc:"Allpool kuvatakse ainult \u00fchised muudetavad v\u00e4ljad. Valige v\u00e4ljad, mida soovite v\u00e4rskendada. Kui samal v\u00e4ljal on eri kihtides eri domeen, kuvatakse ja kasutatakse ainult \u00fcht domeeni.",noCommonFields:"\u00dchiseid v\u00e4lju pole",
fieldTable:{colEdit:"Muudetav",colName:"Nimi",colAlias:"Alias",colAction:"Toimingud"}},tabs:{selection:"M\u00e4\u00e4ratlege valiku t\u00fc\u00fcp",layers:"M\u00e4\u00e4ratlege v\u00e4rskendamiseks kiht (kihid)",fields:"M\u00e4\u00e4ratlege v\u00e4rskendamiseks v\u00e4li (v\u00e4ljad)"},errorOnOk:"Enne konfiguratsiooni salvestamist t\u00e4itke k\u00f5ik parameetrid",next:"J\u00e4rgmine",back:"Tagasi",save:"Salvesta s\u00fcmbol",cancel:"T\u00fchista",ok:"OK",symbolPopup:"S\u00fcmboli valija",editHeaderText:"Vidina \u00fclaosas kuvatav tekst",
widgetIntroSelectByArea:"Kasutage m\u00f5nda allolevatest t\u00f6\u00f6riistadest, et luua valitud uuendatavaid objekte. Kui rida on \x3cfont class\x3d'maxRecordInIntro'\x3eesile t\u00f5stetud\x3c/font\x3e, on maksimaalne kirjete arv \u00fcletatud.",widgetIntroSelectByFeature:"Kasutage allolevat t\u00f6\u00f6riista, et valida objekt kihist \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e . Seda objekti kasutatakse k\u00f5ikide l\u00f5ikuvate objektide valimiseks ja v\u00e4rskendamiseks. Kui rida on \x3cfont class\x3d'maxRecordInIntro'\x3eesile t\u00f5stetud\x3c/font\x3e, on maksimaalne kirjete arv \u00fcletatud.",
widgetIntroSelectByFeatureQuery:"Kasutage allolevat t\u00f6\u00f6riista, et valida objekti kihist \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Objekti \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e atribuuti kasutatakse allolevate kihtide otsinguks ja sellest tulenevate objektide v\u00e4rskendamiseks. Kui rida on \x3cfont class\x3d'maxRecordInIntro'\x3eesile t\u00f5stetud\x3c/font\x3e, on maksimaalne kirjete arv \u00fcletatud.",widgetIntroSelectByQuery:"Sisestage v\u00e4\u00e4rtus valikute loomiseks. Kui rida on \x3cfont class\x3d'maxRecordInIntro'\x3eesile t\u00f5stetud\x3c/font\x3e, on maksimaalne kirjete arv \u00fcletatud.",
_localized:{}}});