// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Bold",copy:"Copy",cut:"Cut","delete":"Delete",indent:"Indent",insertHorizontalRule:"Horizontal Rule",insertOrderedList:"Numbered List",insertUnorderedList:"Bullet List",italic:"Italic",justifyCenter:"Align Center",justifyFull:"Justify",justifyLeft:"Align Left",justifyRight:"Align Right",outdent:"Outdent",paste:"Paste",redo:"Redo",removeFormat:"Remove Format",selectAll:"Select All",strikethrough:"Strikethrough",subscript:"Subscript",superscript:"Superscript",
underline:"Underline",undo:"Undo",unlink:"Remove Link",createLink:"Create Link",toggleDir:"Toggle Direction",insertImage:"Insert Image",insertTable:"Insert/Edit Table",toggleTableBorder:"Toggle Table Border",deleteTable:"Delete Table",tableProp:"Table Property",htmlToggle:"HTML Source",foreColor:"Foreground Color",hiliteColor:"Background Color",plainFormatBlock:"Paragraph Style",formatBlock:"Paragraph Style",fontSize:"Font Size",fontName:"Font Name",tabIndent:"Tab Indent",fullScreen:"Toggle Full Screen",
viewSource:"View HTML Source",print:"Print",newPage:"New Page",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{al:1,ar:1,az:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,lt:1,lv:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,zh:1,"zh-hk":1,"zh-tw":1}},"dijit/_editor/nls/FontChoice":{fontSize:"Size",
fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"None",p:"Paragraph",h1:"Heading",h2:"Subheading",h3:"Sub-subheading",pre:"Pre-formatted",1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",_localized:{al:1,ar:1,az:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,lt:1,lv:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,
sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{ar:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",
findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{ar:1,
bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",_localized:{ar:1,bg:1,bs:1,
ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{ar:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,
ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{ar:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"widgets/GroupFilter/setting/nls/strings":{configText:"Define Your Filter Groups Below",labels:{groupName:"Filter Set Name:",groupNameTip:"Name of the filter that the user will select from.",
groupDesc:"Description:",groupDescTip:"Description of the filter set.",groupOperator:"Preset Operator:",groupOperatorTip:"Option to predefine the operator of the filter. If no Preset Operator is selected, the filter will use the Equal operator.",groupDefault:"Preset Value:",groupDefaultTip:"Option to choose a value from an existing layer.",sameLayerAppend:"When a layer is listed more than once:",sameLayerConjunc:"Append Using:",caseSearch:"Perform a case sensitive search: ",headerTextHelp:"Provide text to display above filter selection"},
buttons:{addNewGroup:"Add a New Group",addNewGroupTip:"Add a new filter set.",addLayer:"Add Layer",addLayerTip:"Add a layer to the filter set."},inputs:{groupName:"Give Your Group a Name",groupDesc:"Description for Your Group",groupDefault:"Enter a Predefined Value",sameLayerAny:"Match any expression",sameLayerAll:"Match all expression",simpleMode:"Start in Simple View",simpleModeTip:"Option to simplify the configured widget interface. When checked, the operator drop-down list and add criteria buttons are removed from the interface.",
webmapAppendModeAny:"Append any expressions to existing map filter",webmapAppendModeAll:"Append all expressions to existing map filter",webmapAppendModeTip:"Option to append the filter set to an existing web map filter.",persistOnClose:"Persist After Widget is Closed",selectGroup:"Select a Group to Filter",hideDropDown:"Hide the header and  filter selection if only 1 group is configured",optionsMode:"Hide Widget Options",optionsModeTip:"Option to expose additional widget settings. If checked, saving and loading defined filters and persisting the filter after the widget is closed are removed from the interface.",
optionOR:"OR",optionAND:"AND",optionEQUAL:"EQUALS",optionNOTEQUAL:"NOT EQUAL",optionGREATERTHAN:"GREATER THAN",optionGREATERTHANEQUAL:"GREATER THAN OR EQUAL",optionLESSTHAN:"LESS THAN",optionLESSTHANEQUAL:"LESS THAN OR EQUAL",optionSTART:"BEGINS WITH",optionEND:"ENDS WITH",optionLIKE:"CONTAINS",optionLIKESPECIFIC:"CONTAINS SPECIFIC VALUE-S",optionNOTLIKESPECIFIC:"DOES NOT CONTAIN SPECIFIC VALUE-S",optionNOTLIKE:"DOES NOT CONTAIN",optionONORBEFORE:"IS ON OR BEFORE",optionONORAFTER:"IS ON OR AFTER",
optionNONE:"NONE"},tables:{layer:"Layers",layerTip:"Name of the layer as defined in the map.",field:"Fields",fieldTip:"Field that the layer will be filtered on.",value:"Use Value",valueTip:"Option to use the drop-down list values from the layer. If no layer uses this parameter, a plain text box will be presented to the user.",zoom:"Zoom",zoomTip:"Option to zoom to the extent of the features after the filter is applied. Only one layer can be selected to zoom to.",action:"Delete",actionTip:"Remove layer from the filter set."},
popup:{label:"Pick a Value"},errors:{noGroups:"You need at least one group.",noGroupName:"One or more group names are missing.",noDuplicates:"One or more group names are duplicated.",noRows:"You need at least one row in the table.",noLayers:"You have no layers in your map."},picker:{description:"Use this form to find a preset value for this group.",layer:"Select a Layer",layerTip:"Name of the layer as defined in the web map.",field:"Select a Field",fieldTip:"Field that the preset value will be set from.",
value:"Select a Value",valueTip:"Value that will be the default of the widget."},_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}}});