// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Podebljaj",copy:"Kopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Uvuci",insertHorizontalRule:"Vodoravno ravnalo",insertOrderedList:"Numerirani popis",insertUnorderedList:"Popis s grafi\u010dkim oznakama",italic:"Kurziv",justifyCenter:"Centriraj",justifyFull:"Poravnaj",justifyLeft:"Poravnaj lijevo",justifyRight:"Poravnaj desno",outdent:"Izvuci",paste:"Zalijepi",redo:"Ponovno napravi",removeFormat:"Ukloni oblikovanje",selectAll:"Izaberi sve",strikethrough:"Precrtaj",
subscript:"Indeks",superscript:"Superskript",underline:"Podcrtaj",undo:"Poni\u0161ti",unlink:"Ukloni vezu",createLink:"Kreiraj vezu",toggleDir:"Prebaci smjer",insertImage:"Umetni sliku",insertTable:"Umetni/Uredi tablicu",toggleTableBorder:"Prebaci rub tablice",deleteTable:"Izbri\u0161i tablicu",tableProp:"Svojstvo tablice",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",plainFormatBlock:"Stil odlomka",formatBlock:"Stil odlomka",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",
tabIndent:"Tabulator uvla\u010denja",fullScreen:"Prebaci na potpun ekran",viewSource:"Pogledaj HTML izvor",print:"Ispis",newPage:"Nova stranica",systemShortcut:'"${0}" akcija je dostupna jedino u va\u0161em pregledniku upotrebom pre\u010dice tipkovnice. Koristite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Veli\u010dina",fontName:"Font",formatBlock:"Oblikovanje",serif:"serif","sans-serif":"sans-serif",monospace:"jednaki razmak",cursive:"rukopisni",
fantasy:"fantastika",noFormat:"Nijedan",p:"Odlomak",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Prethodno formatirano",1:"vrlo vrlo malo",2:"vrlo malo",3:"malo",4:"srednje",5:"veliko",6:"vrlo veliko",7:"vrlo vrlo veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Tra\u017ei:",findTooltip:"Unesi tekst pretrage",replaceLabel:"Zamijeni s:",replaceTooltip:"Unesi tekst za zamjenu",findReplace:"Tra\u017ei i zamijeni",
matchCase:"Usporedi velika/mala slova",matchCaseTooltip:"Usporedi velika/mala slova",backwards:"Natrag",backwardsTooltip:"Pretra\u017ei tekst u prethodnim koracima",replaceAllButton:"Zamijeni sve",replaceAllButtonTooltip:"Zamijeni cijeli tekst",findButton:"Tra\u017ei",findButtonTooltip:"Tra\u017ei tekst",replaceButton:"Zamijeni",replaceButtonTooltip:"Zamijeni tekst",replaceDialogText:"Zamijenjeno ${0} pojavljivanja.",eofDialogText:"Zadnje pojavljivanje ${0}",eofDialogTextFind:"na\u0111eno",eofDialogTextReplace:"zamijenjeno",
_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Zalijepi iz Worda",instructions:"Zalijepite sadr\u017eaj iz Worda u donji tekstni okvir. Kad ste zadovoljni sa sadr\u017eajem za umetanje, pritisnite tipku Zalijepi.  Za prekid umetanja teksta, pritisnite tipku Opoziv.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",title:"Svojstva sidra",anchor:"Naziv:",text:"Opis:",set:"Postavi",cancel:"Opoziv",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Dugi citat",
_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Definirajte grupe filtara u nastavku",labels:{groupName:"Postavljeni naziv filtra:",groupNameTip:"Naziv filtra koje \u0107e korisnik mo\u0107i upotrijebiti.",groupDesc:"Opis:",groupDescTip:"Opis skupa filtra.",groupOperator:"Prethodno postavljeni rukovatelj:",groupOperatorTip:"Opcija za prethodno definiranje rukovatelja filtra. Ako ne postoji predefinirani rukovatelj, filtar \u0107e upotrijebiti jednakog rukovatelja.",groupDefault:"Prethodno postavljena vrijednost:",
groupDefaultTip:"Opcija za odabir vrijednosti s postoje\u0107eg sloja.",sameLayerAppend:"Kada je sloj naveden vi\u0161e puta:",sameLayerConjunc:"Pridodajte pomo\u0107u sljede\u0107eg:",caseSearch:"Izvr\u0161ite pretra\u017eivanje osjetljivo na veli\u010dinu slova: ",headerTextHelp:"Navedite tekst za prikaz iznad odabira filtra"},buttons:{addNewGroup:"Dodaj novu grupu",addNewGroupTip:"Dodajte novi skup filtara.",addLayer:"Dodaj sloj",addLayerTip:"Dodajte sloj skupu filtara."},inputs:{groupName:"Dodijelite naziv svojoj grupi",
groupDesc:"Opis za svoju grupu",groupDefault:"Unesite prethodno definiranu vrijednost",sameLayerAny:"Prona\u0111i podudaranje s bilo kojim izrazom",sameLayerAll:"Prona\u0111i podudaranje sa svim izrazima",simpleMode:"Po\u010dnite u jednostavno prikazu",simpleModeTip:"Opcija za pojednostavljenje su\u010delja konfiguriranog widgeta. Kada je ozna\u010dena, padaju\u0107i izbornik za rukovatelja i gumbi za dodavanje kriterija uklanjaju se sa su\u010delja.",webmapAppendModeAny:"Dodaj bilo koje izraze postoje\u0107em filtru karte",
webmapAppendModeAll:"Dodaj sve izraze postoje\u0107em filtru karte",webmapAppendModeTip:"Izaberite dodavanje filtra postavljenog na postoje\u0107i filtar web-karte.",persistOnClose:"Nastavi nakon \u0161to se widget zatvori",selectGroup:"Odaberi grupu za filtriranje",hideDropDown:"Sakrij zaglavlje i filtriraj odabir ako je samo 1 grupa konfigurirana",optionsMode:"Sakrij opcije widgeta",optionsModeTip:"Opcija za otkrivanje dodatnih postavki widgeta. Ako je ozna\u010dena, sa su\u010delja se uklanjanju funkcije za spremanje i u\u010ditavanje definiranih filtara te upotrebu filtra nakon \u0161to se widget zatvori.",
optionOR:"ILI",optionAND:"I",optionEQUAL:"JEDNAKO",optionNOTEQUAL:"NIJE JEDNAKO",optionGREATERTHAN:"VE\u0106E OD",optionGREATERTHANEQUAL:"VE\u0106E OD ILI JEDNAKO",optionLESSTHAN:"MANJE OD",optionLESSTHANEQUAL:"MANJE OD ILI JEDNAKO",optionSTART:"PO\u010cINJE S",optionEND:"ZAVR\u0160AVA S",optionLIKE:"SADR\u017dI",optionLIKESPECIFIC:"SADR\u017dI ODRE\u0110ENE VRIJEDNOSTI",optionNOTLIKESPECIFIC:"NE SADR\u017dI ODRE\u0110ENE VRIJEDNOSTI",optionNOTLIKE:"NE SADR\u017dI",optionONORBEFORE:"JE NA ILI PRIJE",
optionONORAFTER:"JE NA ILI KASNIJE",optionNONE:"NEMA"},tables:{layer:"Slojevi",layerTip:"Naziv sloja kako je definirano na karti.",field:"Polja",fieldTip:"Polje prema kojem \u0107e se sloj filtrirati.",value:"Upotrijebi vrijednost",valueTip:"Opcija za upotrebu vrijednosti padaju\u0107eg izbornika sa sloja. Ako nijedan sloj ne upotrebljava ovaj parametar, korisniku \u0107e se prikazati obi\u010dan okvir za tekst.",zoom:"Pove\u0107aj",zoomTip:"Opcija za uve\u0107anje do obuhvata geoobjekata nakon primjene filtra. Mo\u017ee se odabrati samo jedan sloj za uve\u0107anje.",
action:"Izbri\u0161i",actionTip:"Uklonite sloj iz skupa filtara."},popup:{label:"Izaberi vrijednost"},errors:{noGroups:"Potrebna vam je barem jedna grupa.",noGroupName:"Nedostaje jedan ili vi\u0161e naziva grupa.",noDuplicates:"Kopiranu su jedan ili vi\u0161e naziva grupa.",noRows:"Potreban vam je barem jedan red u tablici.",noLayers:"Nemate slojeva u karti."},picker:{description:"Upotrijebite ovaj oblik kako biste prona\u0161li prethodno postavljenu vrijednost za ovu grupu.",layer:"Odaberi sloj",
layerTip:"Naziv sloja kako je definirano na web-karti.",field:"Odaberi polje",fieldTip:"Polje prema kojem \u0107e se postavljati predefinirana vrijednost.",value:"Odaberi vrijednost",valueTip:"Vrijednost koja \u0107e biti zadana widgetu."},_localized:{}}});