// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Boldirano",copy:"Kopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Uvla\u010di",insertHorizontalRule:"Horizontalno pravilo",insertOrderedList:"Numerisana lista",insertUnorderedList:"Lista oznaka",italic:"Kurziv",justifyCenter:"Poravnaj po sredini",justifyFull:"Poravnaj",justifyLeft:"Poravnaj na lijevo",justifyRight:"Poravnaj na desno",outdent:"Izvuci",paste:"Zalijepi",redo:"Ponovo napravi",removeFormat:"Ukloni format",selectAll:"Izaberi sve",strikethrough:"Precrtaj",
subscript:"Indeks",superscript:"Superskript",underline:"Podvuci",undo:"Poni\u0161ti",unlink:"Ukloni link",createLink:"Kreiraj link",toggleDir:"Promijeni smjer",insertImage:"Umetni sliku",insertTable:"Umetni/uredi tabelu",toggleTableBorder:"Promijeni rub tabele",deleteTable:"Bri\u0161i tabelu",tableProp:"Osobina tabele",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",plainFormatBlock:"Stil paragrafa",formatBlock:"Stil paragrafa",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",
tabIndent:"Uvla\u010denje kartice",fullScreen:"Promijeni pun ekran",viewSource:"Pogledaj HTML izvor",print:"Ispi\u0161i",newPage:"Nova stranica",systemShortcut:'Akcija "${0}"je dostupna u va\u0161em pretra\u017eiva\u010du kad koristite pre\u010dicu tastature. Koristite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Veli\u010dina",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"bez-serifa",monospace:"monoprostor",cursive:"kurziv",
fantasy:"Fantazija",noFormat:"ni\u0161ta",p:"Paragraf",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Predformatizovano",1:"xx-malo",2:"x-malo",3:"maleno",4:"srednje",5:"veliko",6:"x-veliko",7:"xx-veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Na\u0111i:",findTooltip:"Unesite tekst koji treba na\u0107i",replaceLabel:"Zamijeni sa:",replaceTooltip:"Unesite tekst s kojim zamijeniti",findReplace:"Na\u0111i i zamijeni",
matchCase:"Spari slovo",matchCaseTooltip:"Spari slovo",backwards:"Unazad",backwardsTooltip:"Pretra\u017euj unazad za tekst",replaceAllButton:"Zamijeni sve",replaceAllButtonTooltip:"Zamijeni cijeli tekst",findButton:"Na\u0111i",findButtonTooltip:"Na\u0111i tekst",replaceButton:"Zamijeni",replaceButtonTooltip:"Zamijeni tekst",replaceDialogText:"Zamijenjena ${0} pojavljivanja",eofDialogText:"zadnje pojavljivanje ${0}",eofDialogTextFind:"prona\u0111eno",eofDialogTextReplace:"zamijenjeno",_localized:{}},
"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Zalijepi iz Worda",instructions:"Zalijepi sadr\u017eaj iz Worda ispod okvira s tekstom. Kad ste jednom zadovoljni sa sadr\u017eajem koji ume\u0107ete, pritisnite dugme za lijepljenje. Za prekid umetanja teksta, pritisnite dugme odustani.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",title:"Osobine sidra",anchor:"Ime:",text:"Opis:",set:"Postav",cancel:"Odustani",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Citat bloka",
_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Definirajte grupe filtara u nastavku",labels:{groupName:"Postavljeni naziv filtra:",groupNameTip:"Naziv filtra koje \u0107e korisnik mo\u0107i upotrijebiti.",groupDesc:"Opis:",groupDescTip:"Opis skupa filtra.",groupOperator:"Prethodno postavljeni rukovatelj:",groupOperatorTip:"Opcija za prethodno definiranje rukovatelja filtra. Ako ne postoji predefinirani rukovatelj, filtar \u0107e upotrijebiti jednakog rukovatelja.",groupDefault:"Prethodno postavljena vrijednost:",
groupDefaultTip:"Opcija za odabir vrijednosti s postoje\u0107eg sloja.",sameLayerAppend:"Kada je sloj naveden vi\u0161e puta:",sameLayerConjunc:"Pridodajte pomo\u0107u sljede\u0107eg:",caseSearch:"Izvr\u0161ite pretra\u017eivanje osjetljivo na veli\u010dinu slova: ",headerTextHelp:"Navedite tekst za prikaz iznad odabira filtra"},buttons:{addNewGroup:"Dodaj novu grupu",addNewGroupTip:"Dodajte novi skup filtara.",addLayer:"Dodaj sloj",addLayerTip:"Dodajte sloj skupu filtara."},inputs:{groupName:"Dodijelite naziv svojoj grupi",
groupDesc:"Opis za svoju grupu",groupDefault:"Unesite prethodno definiranu vrijednost",sameLayerAny:"Prona\u0111i podudaranje s bilo kojim izrazom",sameLayerAll:"Prona\u0111i podudaranje sa svim izrazima",simpleMode:"Po\u010dnite u jednostavno prikazu",simpleModeTip:"Opcija za pojednostavljenje su\u010delja konfiguriranog widgeta. Kada je ozna\u010dena, padaju\u0107i izbornik za rukovatelja i gumbi za dodavanje kriterija uklanjaju se sa su\u010delja.",webmapAppendModeAny:"Dodaj bilo koje izraze postoje\u0107em filtru karte",
webmapAppendModeAll:"Dodaj sve izraze postoje\u0107em filtru karte",webmapAppendModeTip:"Izaberite dodavanje filtra postavljenog na postoje\u0107i filtar web-karte.",persistOnClose:"Nastavi nakon \u0161to se widget zatvori",selectGroup:"Odaberi grupu za filtriranje",hideDropDown:"Sakrij zaglavlje i filtriraj odabir ako je samo 1 grupa konfigurirana",optionsMode:"Sakrij opcije widgeta",optionsModeTip:"Opcija za otkrivanje dodatnih postavki widgeta. Ako je ozna\u010dena, sa su\u010delja se uklanjanju funkcije za spremanje i u\u010ditavanje definiranih filtara te upotrebu filtra nakon \u0161to se widget zatvori.",
optionOR:"ILI",optionAND:"I",optionEQUAL:"JEDNAKO",optionNOTEQUAL:"NIJE JEDNAKO",optionGREATERTHAN:"VE\u0106E OD",optionGREATERTHANEQUAL:"VE\u0106E OD ILI JEDNAKO",optionLESSTHAN:"MANJE OD",optionLESSTHANEQUAL:"MANJE OD ILI JEDNAKO",optionSTART:"PO\u010cINJE S",optionEND:"ZAVR\u0160AVA S",optionLIKE:"SADR\u017dI",optionLIKESPECIFIC:"SADR\u017dI ODRE\u0110ENE VRIJEDNOSTI",optionNOTLIKESPECIFIC:"NE SADR\u017dI ODRE\u0110ENE VRIJEDNOSTI",optionNOTLIKE:"NE SADR\u017dI",optionONORBEFORE:"JE NA ILI PRIJE",
optionONORAFTER:"JE NA ILI KASNIJE",optionNONE:"NEMA"},tables:{layer:"Slojevi",layerTip:"Naziv sloja kako je definirano na karti.",field:"Polja",fieldTip:"Polje prema kojem \u0107e se sloj filtrirati.",value:"Upotrijebi vrijednost",valueTip:"Opcija za upotrebu vrijednosti padaju\u0107eg izbornika sa sloja. Ako nijedan sloj ne upotrebljava ovaj parametar, korisniku \u0107e se prikazati obi\u010dan okvir za tekst.",zoom:"Pove\u0107aj",zoomTip:"Opcija za uve\u0107anje do obuhvata geoobjekata nakon primjene filtra. Mo\u017ee se odabrati samo jedan sloj za uve\u0107anje.",
action:"Izbri\u0161i",actionTip:"Uklonite sloj iz skupa filtara."},popup:{label:"Izaberi vrijednost"},errors:{noGroups:"Potrebna vam je barem jedna grupa.",noGroupName:"Nedostaje jedan ili vi\u0161e naziva grupa.",noDuplicates:"Kopiranu su jedan ili vi\u0161e naziva grupa.",noRows:"Potreban vam je barem jedan red u tablici.",noLayers:"Nemate slojeva u karti."},picker:{description:"Upotrijebite ovaj oblik kako biste prona\u0161li prethodno postavljenu vrijednost za ovu grupu.",layer:"Odaberi sloj",
layerTip:"Naziv sloja kako je definirano na web-karti.",field:"Odaberi polje",fieldTip:"Polje prema kojem \u0107e se postavljati predefinirana vrijednost.",value:"Odaberi vrijednost",valueTip:"Vrijednost koja \u0107e biti zadana widgetu."},_localized:{}}});