// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fet",copy:"Kopier",cut:"Klipp ut","delete":"Slett",indent:"Innrykk",insertHorizontalRule:"Vannrett strek",insertOrderedList:"Nummerert liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Midtstill",justifyFull:"Juster",justifyLeft:"Venstrejuster",justifyRight:"H\u00f8yrejuster",outdent:"Fjern innrykk",paste:"Lim inn",redo:"Gj\u00f8r om",removeFormat:"Fjern format",selectAll:"Velg alle",strikethrough:"Gjennomstreking",subscript:"Senket skrift",
superscript:"Hevet skrift",underline:"Understreking",undo:"Angre",unlink:"Fjern kobling",createLink:"Opprett kobling",toggleDir:"Bytt retning",insertImage:"Sett inn bilde",insertTable:"Sett inn/rediger tabell",toggleTableBorder:"Bytt tabellkant",deleteTable:"Slett tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-kilde",foreColor:"Forgrunnsfarge",hiliteColor:"Bakgrunnsfarge",plainFormatBlock:"Avsnittsstil",formatBlock:"Avsnittsstil",fontSize:"Skriftst\u00f8rrelse",fontName:"Skriftnavn",tabIndent:"Tabulatorinnrykk",
fullScreen:"Sl\u00e5 p\u00e5/av full skjerm",viewSource:"Vis HTML-kilde",print:"Skriv ut",newPage:"Ny side",systemShortcut:'Handlingen "${0}" er bare tilgjengelig i nettleseren ved hjelp av en tastatursnarvei. Bruk ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"St\u00f8rrelse",fontName:"Skrift",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"kursiv",fantasy:"fantasi",noFormat:"Ingen",p:"Avsnitt",
h1:"Overskrift",h2:"Undertittel",h3:"Under-undertittel",pre:"Forh\u00e5ndsformatert",1:"xx-liten",2:"x-liten",3:"liten",4:"middels",5:"stor",6:"x-stor",7:"xx-stor",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Forh\u00e5ndsvis",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f8k:",findTooltip:"Skriv inn teksten du vil s\u00f8ke etter",replaceLabel:"Erstatt med:",replaceTooltip:"Skriv inn teksten du vil erstatte med",findReplace:"S\u00f8k og erstatt",matchCase:"Skill mellom store og sm\u00e5 bokstaver",
matchCaseTooltip:"Skill mellom store og sm\u00e5 bokstaver",backwards:"Bakover",backwardsTooltip:"S\u00f8k bakover etter tekst",replaceAllButton:"Erstatt alle",replaceAllButtonTooltip:"Erstatt all tekst",findButton:"S\u00f8k",findButtonTooltip:"S\u00f8k etter teksten",replaceButton:"Erstatt",replaceButtonTooltip:"Erstatt teksten",replaceDialogText:"Erstattet ${0} forekomster.",eofDialogText:"Siste forekomst ${0}",eofDialogTextFind:"funnet",eofDialogTextReplace:"erstattet",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Lim inn fra Word",
instructions:"Lim inn innhold fra Word til tekstboksen nedenfor. N\u00e5r du er forn\u00f8yd med innholdet du skal sette inn, trykker du p\u00e5 innlimingsknappen. Hvis du vil avbryte innsettingen av teksten, trykker du p\u00e5 avbruddsknappen.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Sett inn anker",title:"Ankeregenskaper",anchor:"Navn:",text:"Beskrivelse:",set:"Definer",cancel:"Avbryt",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokksitat",_localized:{}},
"widgets/GroupFilter/setting/nls/strings":{configText:"Definer filtergruppene nedenfor",labels:{groupName:"Navn p\u00e5 filtersett:",groupNameTip:"Navn p\u00e5 filteret som brukeren velger fra.",groupDesc:"Beskrivelse:",groupDescTip:"Beskrivelse av filtersettet.",groupOperator:"Forh\u00e5ndsinnstilt operator:",groupOperatorTip:"Alternativ for \u00e5 forh\u00e5ndsdefinere operatoren i filteret. Hvis Forh\u00e5ndsinnstilt operator ikke er valgt, bruker filteret Lik operator.",groupDefault:"Forh\u00e5ndsinnstilt verdi:",
groupDefaultTip:"Alternativ for \u00e5 velge en verdi fra et eksisterende lag.",sameLayerAppend:"N\u00e5r et lag er oppf\u00f8rt flere ganger:",sameLayerConjunc:"Legg til ved hjelp av:",caseSearch:"Utf\u00f8r s\u00f8k som skiller mellom store og sm\u00e5 bokstaver: ",headerTextHelp:"Oppgi tekst som skal vises over filtervalg"},buttons:{addNewGroup:"Legg til ny gruppe",addNewGroupTip:"Legg til et nytt filtersett.",addLayer:"Legg til lag",addLayerTip:"Legg til et lag i filtersettet."},inputs:{groupName:"Gi gruppen et navn",
groupDesc:"Beskrivelse for gruppen",groupDefault:"Angi en forh\u00e5ndsinnstilt verdi",sameLayerAny:"Finn et uttrykk",sameLayerAll:"Finn alle uttrykk",simpleMode:"Start i enkel visning",simpleModeTip:"Alternativ for \u00e5 forenkle det konfigurerte miniprogram-grensesnittet. N\u00e5r avmerkingsboksen er merket av, fjernes rullegardinlisten for operatorer og knappene for \u00e5 legge til kriterier fra grensesnittet.",webmapAppendModeAny:"Legg til et uttrykk til eksisterende kartfilter",webmapAppendModeAll:"Legg til alle uttrykk til eksisterende kartfilter",
webmapAppendModeTip:"Alternativ for \u00e5 legge til filtersettet til et eksisterende webkartfilter",persistOnClose:"Behold etter at miniprogrammet er lukket",selectGroup:"Velg en gruppe som skal filtreres",hideDropDown:"Skjul overskriften og filtervalget hvis kun 1 gruppe er konfigurert",optionsMode:"Skjul alternativer for miniprogram",optionsModeTip:"Alternativ for \u00e5 vise flere miniprogram-innstillinger. Hvis avmerkingsboksen er merket av, fjernes muligheten til \u00e5 lagre og laste definerte filtre og beholde filteret n\u00e5r miniprogrammet er lukket fra grensesnittet.",
optionOR:"ELLER",optionAND:"OG",optionEQUAL:"LIK",optionNOTEQUAL:"IKKE LIK",optionGREATERTHAN:"ST\u00d8RRE ENN",optionGREATERTHANEQUAL:"ST\u00d8RRE ENN ELLER LIK",optionLESSTHAN:"MINDRE ENN",optionLESSTHANEQUAL:"MINDRE ENN ELLER LIK",optionSTART:"BEGYNNER MED",optionEND:"SLUTTER MED",optionLIKE:"INNEHOLDER",optionLIKESPECIFIC:"INNEHOLDER BESTEMT(E) VERDI(ER)",optionNOTLIKESPECIFIC:"INNEHOLDER IKKE BESTEMT(E) VERDI(ER)",optionNOTLIKE:"INNEHOLDER IKKE",optionONORBEFORE:"ER P\u00c5 ELLER F\u00d8R",optionONORAFTER:"ER P\u00c5 ELLER ETTER",
optionNONE:"INGEN"},tables:{layer:"Lag",layerTip:"Navn p\u00e5 laget slik det er definert i kartet.",field:"Felter",fieldTip:"Felt som laget filtreres p\u00e5.",value:"Bruk verdi",valueTip:"Alternativ for \u00e5 bruke rullegardinlisteverdier fra laget. Hvis det ikke er et lag som bruker denne parameteren, vises en enkel tekstboks for brukeren.",zoom:"Zoom",zoomTip:"Alternativ for \u00e5 zoome til utstrekningen av geoobjektene n\u00e5r filteret brukes. Du kan bare velge ett lag du kan zoome til.",
action:"Slett",actionTip:"Fjern lag fra filtersettet."},popup:{label:"Velg en verdi"},errors:{noGroups:"Du m\u00e5 ha minst \u00e9n gruppe.",noGroupName:"Et eller flere gruppenavn mangler.",noDuplicates:"Et eller flere gruppenavn er like.",noRows:"Du m\u00e5 ha minst \u00e9n rad i tabellen.",noLayers:"Du har ingen lag i kartet."},picker:{description:"Bruk dette skjemaet til \u00e5 finne en forh\u00e5ndsinnstilt verdi for denne gruppen.",layer:"Velg et lag",layerTip:"Navn p\u00e5 laget slik det er definert i webkartet.",
field:"Velg et felt",fieldTip:"Felt som den forh\u00e5ndsinnstilte verdien angis fra.",value:"Velg en verdi",valueTip:"Verdi som vil v\u00e6re standardverdien for miniprogrammet."},_localized:{}}});