// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Krepko",copy:"Prekopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Zamik",insertHorizontalRule:"Vodoravno ravnilo",insertOrderedList:"O\u0161tevil\u010den seznam",insertUnorderedList:"Na\u0161tevni seznam",italic:"Le\u017ee\u010de",justifyCenter:"Poravnaj na sredino",justifyFull:"Poravnaj obojestransko",justifyLeft:"Poravnaj levo",justifyRight:"Poravnaj desno",outdent:"Primakni",paste:"Prilepi",redo:"Znova uveljavi",removeFormat:"Odstrani oblikovanje",
selectAll:"Izberi vse",strikethrough:"Pre\u010drtano",subscript:"Podpisano",superscript:"Nadpisano",underline:"Pod\u010drtano",undo:"Razveljavi",unlink:"Odstrani povezavo",createLink:"Ustvari povezavo",toggleDir:"Preklopi smer",insertImage:"Vstavi sliko",insertTable:"Vstavi/uredi tabelo",toggleTableBorder:"Preklopi na obrobo tabele",deleteTable:"Izbri\u0161i tabelo",tableProp:"Lastnost tabele",htmlToggle:"Izvorna koda HTML",foreColor:"Barva ospredja",hiliteColor:"Barva ozadja",plainFormatBlock:"Slog odstavka",
formatBlock:"Slog odstavka",fontSize:"Velikost pisave",fontName:"Ime pisave",tabIndent:"Zamik tabulatorja",fullScreen:"Preklopi na celozaslonski na\u010din",viewSource:"Prika\u017ei izvorno kodo HTML",print:"Natisni",newPage:"Nova stran",systemShortcut:'Dejanje "${0}" lahko v va\u0161em brskalniku uporabite samo z bli\u017enjico na tipkovnici. Uporabite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Velikost",fontName:"Pisava",formatBlock:"Oblika",
serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Brez",p:"Odstavek",h1:"Naslovni slog",h2:"Podnaslovni slog",h3:"Pod-podnaslovni slog",pre:"Vnaprej oblikovan",1:"xx-majhno",2:"x-majhno",3:"majhno",4:"srednje",5:"veliko",6:"x-veliko",7:"xx-veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Predogled ",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Najdi:",findTooltip:"Vnesite besedilo za iskanje",replaceLabel:"Zamenjaj z:",
replaceTooltip:"Vnesite besedilo za zamenjavo",findReplace:"Najdi in zamenjaj",matchCase:"Razlikuj velike in male \u010drke",matchCaseTooltip:"Razlikuj velike in male \u010drke",backwards:"Nazaj",backwardsTooltip:"Vzvratno iskanje besedila",replaceAllButton:"Zamenjaj vse",replaceAllButtonTooltip:"Zamenjaj celotno besedilo",findButton:"Najdi",findButtonTooltip:"Najdi besedilo",replaceButton:"Zamenjaj",replaceButtonTooltip:"Zamenjaj besedilo",replaceDialogText:"Zamenjanih ${0} pojavitev.",eofDialogText:"Zadnja pojavitev ${0}",
eofDialogTextFind:"najdeno",eofDialogTextReplace:"zamenjano",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Prilepi iz programa Word",instructions:"Vsebino iz programa Word prilepite v spodnje besedilno polje. Ko ste zadovoljni z vstavljeno vsebino, pritisnite gumb Vstavi. \u010ce \u017eelite prenehati z vstavljanjem vsebine, pritisnite gumb Prekli\u010di.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Vstavi sidro",title:"Lastnosti sidra",anchor:"Ime:",
text:"Opis:",set:"Nastavi",cancel:"Prekli\u010di",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokovno besedilo",_localized:{}},"widgets/DataAggregation/setting/nls/strings":{locatorUrl:"URL lokatorja",set:"Nastavi",locatorName:"Ime lokatorja",locatorExample:"Primer",countryCode:"\u0160ifre dr\u017eave ali regije",eg:"npr. ",countryCodeHint:"\u010ce to vrednost pustite prazno, bo iskanje potekalo po vseh dr\u017eavah in regijah",minCandidateScore:"Minimalna ocena kandidata",
minCandidateScoreHint:"\u010ce to vrednost pustite prazno, bo uporabljena minimalna ocena kandidata 90",enableSingleField:"Mo\u017enosti enega polja",singleFieldHint:"Podatki o naslovu bodo v enem polju",enableMultiField:"Mo\u017enosti ve\u010d polj",multiFieldHint:"Podatki o naslovu bodo v ve\u010d poljih",enableXYField:"Mo\u017enosti polja X/Y",xyFieldHint:"Podatki bodo vsebovali vrednosti koordinat X/Y",instructionGeocode:"Dodajte in konfigurirajte storitve lokatorja.",invalidUrlTip:"URL ${URL} ni veljaven ali dostopen.",
geocodeTabLabel:"Nastavitve lokacije",lookupList:"Imena polj za prepoznavanje",isRecognized:"Imena polj v spodnji tabeli so samodejno prepoznana za to polje",needsEditablePointLayers:"Spletna karta mora vsebovati vsaj en to\u010dkovni sloj za urejanje.",editpageAlias:"Vzdevek",configureFields:"Konfigurirajte polja sloja",configureSingleFields:"Konfiguriraj polje z enim naslovom",configureMultiFields:"Konfiguriraj polja z ve\u010d naslovi",configureXYFields:"Konfiguriraj polja X/Y",noFields:"Uporabiti dejanje za urejanje, da opredelite eno ali ve\u010d polj za prikaz",
display:"Prikaz",duplicate:"Poi\u0161\u010di podvojitev",duplicateTip:"Po tem polju i\u0161\u010dite identi\u010dne vrednosti med izvorno datoteko in ciljnim slojem./n Ko je najdeno identi\u010dno ujemanje, zapis iz datoteke ne bo najden in bo ozna\u010den kot podvojitev.",noSelectField:"Najprej izberite mo\u017enost geoobjektnega sloja",newNamePlaceholder:"",xyFieldsLabelX:"X (geografska dol\u017eina)",xyFieldsLabelY:"Y (geografska \u0161irina)",xyFieldsX:"X",xyFieldsY:"Y",easting:"Pomik proti vzhodu",
northing:"Pomik proti severu",lon:"G.D.",lat:"G.\u0160.",layerOptionHint:"Izberite sloj v katerega \u017eelite poslati podatke.",layerFieldTitle:"Ciljni sloj",tempSymbolHint:"Izberite simbol, ki bo uporabljen za prikaz geoobjektov.",tempSymbolTitle:"Prikazni simbol",maxRecords:"Maks. zapisov",maxRecordsHint:"Maksimalno \u0161tevilo zapisov za iskanje",searchRadius:"Iskalni polmer",searchRadiusHint:"Razdalje za iskanje podvojenih geoobjektov iz sloja",requiresInteger:"Vnesite \u0161tevilsko vrednost.",
requiresInteger0100:"Vnesite \u0161tevilsko vrednost med 0 in 100",requiresLocator:"Dodajte vsaj en veljaven lokator.",layerFields:"Nastavitve sloja",layerFieldsHint:"Dolo\u010dite polja iz ciljnega sloja, ki bodo preslikana v izvorna polja.",locatorError:"Lokator je neveljaven ali nedostopen.",optionNotMatch:"Mo\u017enosti polja niso dosledna po celotnih lokatorjih. Nadomestni na\u010din morda ne bo deloval kot pri\u010dakovano.",targetLayerTabTitle:"Ciljni sloj",locationSettingsTabTitle:"Nastavitve lokacije",
generalSettingsTabTitle:"Splo\u0161ne nastavitve",addTargetLayersLabel:"Dodajte ciljni sloj",introductoryText:"Ustvarite vsebino z navodili za pripomo\u010dek",defaultStartPageInstructions:"Ta pripomo\u010dek vam bo v pomo\u010d pri obdelavi in po\u0161iljanju podatkov iz datoteke v izbrani sloj na karti.\x3cbr/\x3e \x3cbr/\x3e Vrednosti znotraj datoteke morajo biti lo\u010dene z vejico, presledkom, podpi\u010djem ali navpi\u010dnico.",noTargetLayerConfiguredErrorMsg:"Noben ciljni sloj ni konfiguriran",
noFieldsForTargetLayer:"Nastavitve sloja niso opredeljene za ciljni sloj",locationSettingsNotConfigured:"Nastavitve lokacije niso ustrezno konfigurirane",_localized:{}}});