// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fett",copy:"Kopieren",cut:"Ausschneiden","delete":"L\u00f6schen",indent:"Einr\u00fccken",insertHorizontalRule:"Horizontaler Strich",insertOrderedList:"Nummerierung",insertUnorderedList:"Aufz\u00e4hlungszeichen",italic:"Kursiv",justifyCenter:"Zentriert",justifyFull:"Blocksatz",justifyLeft:"Linksb\u00fcndig",justifyRight:"Rechtsb\u00fcndig",outdent:"Ausr\u00fccken",paste:"Einf\u00fcgen",redo:"Wiederholen",removeFormat:"Formatierung entfernen",selectAll:"Alles ausw\u00e4hlen",
strikethrough:"Durchgestrichen",subscript:"Tiefgestellt",superscript:"Hochgestellt",underline:"Unterstrichen",undo:"R\u00fcckg\u00e4ngig",unlink:"Link entfernen",createLink:"Link erstellen",toggleDir:"Richtung wechseln",insertImage:"Grafik einf\u00fcgen",insertTable:"Tabelle einf\u00fcgen/bearbeiten",toggleTableBorder:"Tabellenumrandung ein-/ausschalten",deleteTable:"Tabelle l\u00f6schen",tableProp:"Tabelleneigenschaft",htmlToggle:"HTML-Quelltext",foreColor:"Vordergrundfarbe",hiliteColor:"Hintergrundfarbe",
plainFormatBlock:"Absatzstil",formatBlock:"Absatzstil",fontSize:"Schriftgr\u00f6\u00dfe",fontName:"Schriftartname",tabIndent:"Registerkarteneinr\u00fcckung",fullScreen:"Gesamtanzeige",viewSource:"HTML-Quelle",print:"Drucken",newPage:"Neue Seite",systemShortcut:'Die Aktion "${0}" ist nur \u00fcber einen Direktaufruf in Ihrem Browser verf\u00fcgbar. Verwenden Sie ${1}.',ctrlKey:"Strg+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Gr\u00f6\u00dfe",fontName:"Schriftart",
formatBlock:"Format",serif:"Serife","sans-serif":"Serifenlos",monospace:"Monospaceschrift",cursive:"Kursiv",fantasy:"Fantasie",noFormat:"Keine Angabe",p:"Absatz",h1:"\u00dcberschrift",h2:"Unter\u00fcberschrift",h3:"Unterunter\u00fcberschrift",pre:"Vorformatiert",1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Vorschau",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Suchen:",findTooltip:"Text zum Suchen eingeben",replaceLabel:"Ersetzen durch:",
replaceTooltip:"Text zum Ersetzen eingeben",findReplace:"Suchen und ersetzen",matchCase:"Gro\u00df- und Kleinschreibung abgleichen",matchCaseTooltip:"Gro\u00df- und Kleinschreibung abgleichen",backwards:"Zur\u00fcck",backwardsTooltip:"R\u00fcckw\u00e4rts nach Text suchen",replaceAllButton:"Global ersetzen",replaceAllButtonTooltip:"Gesamten Text ersetzen",findButton:"Suchen",findButtonTooltip:"Text suchen",replaceButton:"Ersetzen",replaceButtonTooltip:"Text ersetzen",replaceDialogText:"${0} Vorkommen ersetzt.",
eofDialogText:"Letztes Vorkommen ${0}",eofDialogTextFind:"gefunden",eofDialogTextReplace:"ersetzt",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Aus Word einf\u00fcgen",instructions:"F\u00fcgt den Inhalt aus Word in das Textfeld unten ein. Wenn Sie mit dem einzuf\u00fcgenden Inhalt zufrieden sind, klicken Sie auf die Schaltfl\u00e4che zum Einf\u00fcgen. Um das Einf\u00fcgen von Text abzubrechen, klicken Sie auf die Schaltfl\u00e4che zum Abbrechen. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker einf\u00fcgen",
title:"Eigenschaften des Ankers",anchor:"Name:",text:"Beschreibung:",set:"Festlegen",cancel:"Abbrechen",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockzitat",_localized:{}},"widgets/DataAggregation/setting/nls/strings":{locatorUrl:"Locator-URL",set:"Festlegen",locatorName:"Locator-Name",locatorExample:"Beispiel",countryCode:"L\u00e4nder- oder Regionscode(s)",eg:"z. B. ",countryCodeHint:"Wenn dieser Wert leer gelassen wird, werden alle L\u00e4nder und Regionen durchsucht",minCandidateScore:"Minimale Kandidatenpunktzahl",
minCandidateScoreHint:"Wenn dieser Wert leer gelassen wird, wird die minimale Kandidatenpunktzahl 90 verwendet.",enableSingleField:"Einzelfeldoptionen",singleFieldHint:"Adressendaten befinden sich in einem einzelnen Feld",enableMultiField:"Mehrfeldoptionen",multiFieldHint:"Adressendaten befinden sich in mehreren Feldern",enableXYField:"X-/Y-Feldoptionen",xyFieldHint:"Daten enthalten X-/Y-Koordinatenwerte",instructionGeocode:"F\u00fcgen Sie Locator-Services hinzu, und konfigurieren Sie sie.",invalidUrlTip:"Die URL ${URL} ist ung\u00fcltig oder es kann nicht darauf zugegriffen werden.",
geocodeTabLabel:"Positionseinstellungen",lookupList:"Feldnamen f\u00fcr Wiedererkennung",isRecognized:"Feldnamen in der nachfolgenden Tabelle werden automatisch f\u00fcr dieses Feld erkannt",needsEditablePointLayers:"Die Webkarte muss mindestens einen editierbaren Punkt-Layer enthalten.",editpageAlias:"Alias",configureFields:"Layer-Felder konfigurieren",configureSingleFields:"Einzelnes Adressenfeld konfigurieren",configureMultiFields:"Mehrere Adressenfelder konfigurieren",configureXYFields:"X-/Y-Felder konfigurieren",
noFields:"Verwenden Sie die Bearbeitungsaktion, um ein oder mehrere anzuzeigende Felder zu definieren.",display:"Anzeige",duplicate:"Duplikat suchen",duplicateTip:"Dieses Feld nach identischen Werten in Quelldatei und Ziel-Layer durchsuchen./n Wenn ein identischer Wert gefunden wird, wird der Datensatz aus der Datei nicht verortet und als Duplikat gekennzeichnet.",noSelectField:'W\u00e4hlen Sie zuerst die Option "Feature-Layer" aus.',newNamePlaceholder:"",xyFieldsLabelX:"X (L\u00e4ngengrad)",xyFieldsLabelY:"Y (Breitengrad)",
xyFieldsX:"X",xyFieldsY:"Y",easting:"Rechtswert",northing:"Hochwert",lon:"LON",lat:"LAT",layerOptionHint:"W\u00e4hlen Sie den Layer aus, an den Sie Daten senden m\u00f6chten.",layerFieldTitle:"Ziel-Layer",tempSymbolHint:"W\u00e4hlen Sie das Symbol aus, mit dem die Features angezeigt werden.",tempSymbolTitle:"Symbol anzeigen",maxRecords:"Maximale Anzahl der Datens\u00e4tze",maxRecordsHint:"Maximale Anzahl der zu verortenden Datens\u00e4tze",searchRadius:"Suchradius",searchRadiusHint:"Entfernung f\u00fcr die Suche nach doppelten Features vom Layer",
requiresInteger:"Geben Sie einen numerischen Wert ein.",requiresInteger0100:"Geben Sie einen numerischen Wert zwischen 0 und 100 ein.",requiresLocator:"F\u00fcgen Sie mindestens einen g\u00fcltigen Locator hinzu.",layerFields:"Layer-Einstellungen",layerFieldsHint:"Geben Sie Felder aus dem Ziel-Layer an, die den Quellfeldern zugeordnet werden.",locatorError:"Der Locator ist ung\u00fcltig, oder es kann nicht darauf zugegriffen werden.",optionNotMatch:"Die Feldoptionen sind in den Locators nicht konsistent. Das Failover funktioniert m\u00f6glicherweise nicht erwartungsgem\u00e4\u00df.",
targetLayerTabTitle:"Ziel-Layer",locationSettingsTabTitle:"Positionseinstellungen",generalSettingsTabTitle:"Allgemeine Einstellungen",addTargetLayersLabel:"Ziel-Layer hinzuf\u00fcgen",introductoryText:"Lehrinhalte f\u00fcr das Widget hinzuf\u00fcgen",defaultStartPageInstructions:"Dieses Widget unterst\u00fctzt die Verarbeitung von Daten und deren \u00dcbermittlung von einer Datei an den ausgew\u00e4hlten Layer in der Karte.\x3cbr/\x3e \x3cbr/\x3e Werte innerhalb der Datei m\u00fcssen durch ein Komma, einen Tabulator, ein Semikolon oder einen vertikalen Balken getrennt sein.",
noTargetLayerConfiguredErrorMsg:"Kein Ziel-Layer konfiguriert.",noFieldsForTargetLayer:"Layer-Einstellungen sind f\u00fcr den Ziel-Layer nicht konfiguriert.",locationSettingsNotConfigured:"Positionseinstellungen sind nicht ordnungsgem\u00e4\u00df konfiguriert.",_localized:{}}});