// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Bold",copy:"Copy",cut:"Cut","delete":"Delete",indent:"Indent",insertHorizontalRule:"Horizontal Rule",insertOrderedList:"Numbered List",insertUnorderedList:"Bullet List",italic:"Italic",justifyCenter:"Align Center",justifyFull:"Justify",justifyLeft:"Align Left",justifyRight:"Align Right",outdent:"Outdent",paste:"Paste",redo:"Redo",removeFormat:"Remove Format",selectAll:"Select All",strikethrough:"Strikethrough",subscript:"Subscript",superscript:"Superscript",
underline:"Underline",undo:"Undo",unlink:"Remove Link",createLink:"Create Link",toggleDir:"Toggle Direction",insertImage:"Insert Image",insertTable:"Insert/Edit Table",toggleTableBorder:"Toggle Table Border",deleteTable:"Delete Table",tableProp:"Table Property",htmlToggle:"HTML Source",foreColor:"Foreground Color",hiliteColor:"Background Color",plainFormatBlock:"Paragraph Style",formatBlock:"Paragraph Style",fontSize:"Font Size",fontName:"Font Name",tabIndent:"Tab Indent",fullScreen:"Toggle Full Screen",
viewSource:"View HTML Source",print:"Print",newPage:"New Page",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{al:1,ar:1,az:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,lt:1,lv:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,zh:1,"zh-hk":1,"zh-tw":1}},"dijit/_editor/nls/FontChoice":{fontSize:"Size",
fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"None",p:"Paragraph",h1:"Heading",h2:"Subheading",h3:"Sub-subheading",pre:"Pre-formatted",1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",_localized:{al:1,ar:1,az:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,lt:1,lv:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,
sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{ar:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",
findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{ar:1,
bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",_localized:{ar:1,bg:1,bs:1,
ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{ar:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,
ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{ar:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,zh:1,"zh-hk":1,"zh-tw":1}},"widgets/DataAggregation/setting/nls/strings":{locatorUrl:"Locator URL",set:"Set",locatorName:"Locator Name",locatorExample:"Example",countryCode:"Country or Region Code(s)",
eg:"e.g. ",countryCodeHint:"Leaving this value blank will search all countries and regions",minCandidateScore:"Minimum Candidate Score",minCandidateScoreHint:"Leaving this value blank will use a minimum candidate score of 90",enableSingleField:"Single-field Options",singleFieldHint:"Address data will be in a single field",enableMultiField:"Multi-field Options",multiFieldHint:"Address data will be in multiple fields",enableXYField:"X/Y Field Options",xyFieldHint:"Data will contain X/Y coordinate values",
instructionGeocode:"Add and configure locator services.",invalidUrlTip:"The URL ${URL} is invalid or inaccessible.",geocodeTabLabel:"Location Settings",lookupList:"Field Names to Recognize",isRecognized:"Field names in the table below are automatically recognized for this field",needsEditablePointLayers:"The webmap must contain at least one editable point layer.",editpageAlias:"Alias",configureFields:"Configure Layer Fields",configureSingleFields:"Configure a Single Address Field",configureMultiFields:"Configure Multiple Address Fields",
configureXYFields:"Configure X/Y Fields",noFields:"Use the edit action to define one or more fields to display",display:"Display",duplicate:"Find Duplicate",duplicateTip:"Search this field for identical values between the source file and target layer./n When an identical match is found the record from the file will not be located and will be flagged as a duplicate.",noSelectField:"Select the Feature Layer option first",newNamePlaceholder:"",xyFieldsLabelX:"X (Longitude)",xyFieldsLabelY:"Y (Latitude)",
xyFieldsX:"X",xyFieldsY:"Y",easting:"Easting",northing:"Northing",lon:"LON",lat:"LAT",layerOptionHint:"Choose the layer to submit data to.",layerFieldTitle:"Target Layer",tempSymbolHint:"Choose the symbol that will be used to display the features.",tempSymbolTitle:"Display Symbol",maxRecords:"Max records",maxRecordsHint:"Max number of records to locate",searchRadius:"Search radius",searchRadiusHint:"Distance to search for duplicate features from layer",requiresInteger:"Enter a numeric value.",requiresInteger0100:"Enter a numeric value between 0 and 100",
requiresLocator:"Add at least one valid locator.",layerFields:"Layer Settings",layerFieldsHint:"Specify fields from the Target Layer that will be mapped to the source fields.",locatorError:"Locator is invalid or inaccessible.",optionNotMatch:"Field options not consistent across locators. Failover may not work as expected.",targetLayerTabTitle:"Target Layer",locationSettingsTabTitle:"Location Settings",generalSettingsTabTitle:"General Settings",addTargetLayersLabel:"Add Target Layer",introductoryText:"Create instructional content for the widget",
defaultStartPageInstructions:"This widget will assist with processing and submitting data from a file to the selected layer in the map.\x3cbr/\x3e \x3cbr/\x3e Values within the file must be delimited by comma, tab, semi-colon, or vertical bar.",noTargetLayerConfiguredErrorMsg:"No target layer configured",noFieldsForTargetLayer:"Layer settings are not defined for the target layer",locationSettingsNotConfigured:"Location settings are not properly configured",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,
el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}}});