// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Halvfet",copy:"Kopiera",cut:"Klipp ut","delete":"Ta bort",indent:"Indrag",insertHorizontalRule:"Horisontell linje",insertOrderedList:"Numrerad lista",insertUnorderedList:"Punktlista",italic:"Kursiv",justifyCenter:"Centrera",justifyFull:"Marginaljustera",justifyLeft:"V\u00e4nsterjustera",justifyRight:"H\u00f6gerjustera",outdent:"Utdrag",paste:"Klistra in",redo:"G\u00f6r om",removeFormat:"Ta bort format",selectAll:"Markera allt",strikethrough:"Genomstruken",
subscript:"Neds\u00e4nkt",superscript:"Upph\u00f6jt",underline:"Understruken",undo:"\u00c5ngra",unlink:"Ta bort l\u00e4nk",createLink:"Skapa l\u00e4nk",toggleDir:"V\u00e4xla riktning",insertImage:"Infoga bild",insertTable:"Infoga/redigera tabell",toggleTableBorder:"V\u00e4xla tabellinjer",deleteTable:"Ta bort tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-k\u00e4llkod",foreColor:"F\u00f6rgrundsf\u00e4rg",hiliteColor:"Bakgrundsf\u00e4rg",plainFormatBlock:"Styckeformat",formatBlock:"Styckeformat",
fontSize:"Teckenstorlek",fontName:"Teckensnitt",tabIndent:"Tabbindrag",fullScreen:"V\u00e4xla helsk\u00e4rm",viewSource:"Visa HTML-kod",print:"Skriv ut",newPage:"Ny sida",systemShortcut:"\u00c5tg\u00e4rden ${0} \u00e4r endast tillg\u00e4nglig i webbl\u00e4saren via ett tangentbordskommando. Anv\u00e4nd ${1}.",ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Storlek ",fontName:"Teckensnitt",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",
monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Inget",p:"Stycke",h1:"Rubrik 1",h2:"Rubrik 2",h3:"Rubrik 3",pre:"F\u00f6rformaterad",1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"F\u00f6rhandsgranskning",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f6k: ",findTooltip:"Skriv s\u00f6ktexten",replaceLabel:"Ers\u00e4tt med:",replaceTooltip:"Skriv ers\u00e4ttningstexten",findReplace:"S\u00f6k och ers\u00e4tt",
matchCase:"Matcha gemener/versaler",matchCaseTooltip:"Matcha gemener/versaler",backwards:"Bak\u00e5t",backwardsTooltip:"S\u00f6k bak\u00e5t efter text",replaceAllButton:"Ers\u00e4tt alla",replaceAllButtonTooltip:"Ers\u00e4tt all text",findButton:"S\u00f6k",findButtonTooltip:"S\u00f6k efter texten",replaceButton:"Er\u00e4tt",replaceButtonTooltip:"Ers\u00e4tt texten",replaceDialogText:"${0} f\u00f6rekomster har ersatts.",eofDialogText:"Sista f\u00f6rekomsten ${0}",eofDialogTextFind:"hittades",eofDialogTextReplace:"ersattes",
_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Klistra in fr\u00e5n Word",instructions:"Klistra in inneh\u00e5llet fr\u00e5n Word i textrutan nedan. N\u00e4r du har valt inneh\u00e5ll klickar du p\u00e5 Klistra in. Klicka p\u00e5 Avbryt om du inte vill klistra in text. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Infoga ankare",title:"Ankaregenskaper",anchor:"Namn:",text:"Beskrivning:",set:"Anv\u00e4nd",cancel:"Avbryt",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockcitat",
_localized:{}},"widgets/DataAggregation/setting/nls/strings":{locatorUrl:"Lokaliseringsfils-URL",set:"Ange",locatorName:"Namn p\u00e5 placeringsfil",locatorExample:"Exempel",countryCode:"Lands- eller regionkoder",eg:"t.ex. ",countryCodeHint:"Om du l\u00e4mnar det h\u00e4r v\u00e4rdet tomt sker s\u00f6kningen i alla l\u00e4nder och regioner",minCandidateScore:"Minsta kandidatpo\u00e4ng",minCandidateScoreHint:"Om det h\u00e4r f\u00e4ltet l\u00e4mnas tomt anv\u00e4nds en minsta kandidatpo\u00e4ng p\u00e5 90",
enableSingleField:"Alternativ f\u00f6r enstaka f\u00e4lt",singleFieldHint:"Adressdata \u00e4r i ett enda f\u00e4lt",enableMultiField:"Alternativ f\u00f6r flera f\u00e4lt",multiFieldHint:"Adressdata \u00e4r i flera f\u00e4lt",enableXYField:"Alternativ f\u00f6r X/Y-f\u00e4lt",xyFieldHint:"Data inneh\u00e5ller X/Y-koordinatv\u00e4rden",instructionGeocode:"L\u00e4gg till och konfigurera lokaliseringsfilstj\u00e4nster.",invalidUrlTip:"URL:en ${URL} \u00e4r ogiltig eller g\u00e5r inte att \u00f6ppna.",
geocodeTabLabel:"Platsinst\u00e4llningar",lookupList:"F\u00e4ltnamn som ska k\u00e4nnas igen",isRecognized:"F\u00e4ltnamnen i tabellen nedan k\u00e4nns automatiskt igen f\u00f6r det h\u00e4r f\u00e4ltet",needsEditablePointLayers:"Webbkartan m\u00e5ste inneh\u00e5lla minst ett redigerbart punktlager.",editpageAlias:"Alias",configureFields:"Konfigurera lagerf\u00e4lt",configureSingleFields:"Konfigurera ett enstaka adressf\u00e4lt",configureMultiFields:"Konfigurera flera adressf\u00e4lt",configureXYFields:"Konfigurera X/Y-f\u00e4lt",
noFields:"Definiera ett eller flera f\u00e4lt att visa med hj\u00e4lp av \u00e5tg\u00e4rden Redigera",display:"Visa",duplicate:"Hitta dubblett",duplicateTip:"S\u00f6k i det h\u00e4r f\u00e4ltet efter identiska v\u00e4rden mellan k\u00e4llagret och m\u00e5llagret./n N\u00e4r en identisk matchning uppt\u00e4cks hittas inte posten fr\u00e5n filen och flaggas som en dubblett.",noSelectField:"V\u00e4lj alternativet Geoobjektlager f\u00f6rst",newNamePlaceholder:"",xyFieldsLabelX:"X (longitud)",xyFieldsLabelY:"Y (latitud)",
xyFieldsX:"X",xyFieldsY:"Y",easting:"\u00d6stlig",northing:"Nordlig",lon:"LON",lat:"LAT",layerOptionHint:"V\u00e4lj lager att skicka data till:",layerFieldTitle:"M\u00e5llager",tempSymbolHint:"V\u00e4lj den symbol som ska anv\u00e4ndas f\u00f6r att visa geoobjekten.",tempSymbolTitle:"Visningssymbol",maxRecords:"Max antal poster",maxRecordsHint:"Maximalt antal poster att hitta",searchRadius:"S\u00f6kradie",searchRadiusHint:"Avst\u00e5nd till s\u00f6kning efter dubblerade geoobjekt fr\u00e5n lager",
requiresInteger:"Ange ett numeriskt v\u00e4rde.",requiresInteger0100:"Ange ett numeriskt v\u00e4rde mellan 0 och 100",requiresLocator:"L\u00e4gg till minst en giltig lokaliseringsfil.",layerFields:"Lagerinst\u00e4llningar",layerFieldsHint:"Ange f\u00e4lt fr\u00e5n m\u00e5llagret som ska karteras till k\u00e4llf\u00e4lten.",locatorError:"Lokaliseringsfilen \u00e4r ogiltig eller inte tillg\u00e4nglig.",optionNotMatch:"F\u00e4ltalternativen \u00e4r inte konsekventa mellan lokaliseringsfiler. Redundansen kanske inte fungerar som v\u00e4ntat.",
targetLayerTabTitle:"M\u00e5llager",locationSettingsTabTitle:"Platsinst\u00e4llningar",generalSettingsTabTitle:"Allm\u00e4nna inst\u00e4llningar",addTargetLayersLabel:"L\u00e4gg till m\u00e5llager",introductoryText:"Skapa instruktionsinneh\u00e5ll f\u00f6r widgeten",defaultStartPageInstructions:"Den h\u00e4r widgeten hj\u00e4lper till med bearbetning och \u00f6verf\u00f6ring av data fr\u00e5n en fil till det valda lagret i kartan.\x3cbr/\x3e \x3cbr/\x3eV\u00e4rden i filen m\u00e5ste avgr\u00e4nsas med komma, tabb, semikolon eller vertikalstreck.",
noTargetLayerConfiguredErrorMsg:"Inget m\u00e5llager \u00e4r konfigurerat",noFieldsForTargetLayer:"Lagerinst\u00e4llningar \u00e4r inte definierade f\u00f6r m\u00e5llagret",locationSettingsNotConfigured:"Platsinst\u00e4llningarna \u00e4r inte korrekt konfigurerade",_localized:{}}});