// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Pary\u0161kintasis",copy:"Kopijuoti",cut:"Kirpti","delete":"Pa\u0161alinti",indent:"\u012etrauka",insertHorizontalRule:"Horizontali linija",insertOrderedList:"Sunumeruotas s\u0105ra\u0161as",insertUnorderedList:"S\u0105ra\u0161as su \u017eenkleliais",italic:"Pasvirasis",justifyCenter:"Lygiuoti centre",justifyFull:"Abipus\u0117 lygiuot\u0117",justifyLeft:"Lygiuoti kair\u0117je",justifyRight:"Lygiuoti de\u0161in\u0117je",outdent:"Atvirk\u0161tin\u0117 \u012ftrauka",
paste:"\u012eklijuoti",redo:"Gr\u0105\u017einti",removeFormat:"Pa\u0161alinti formatavim\u0105",selectAll:"\u017dym\u0117ti visk\u0105",strikethrough:"Perbrauktasis",subscript:"Apatinis indeksas",superscript:"Vir\u0161utinis indeksas",underline:"Pabrauktasis",undo:"At\u0161aukti",unlink:"Pa\u0161alinti nuorod\u0105",createLink:"Kurti nuorod\u0105",toggleDir:"Perjungti krypt\u012f",insertImage:"\u012eterpti vaizd\u0105",insertTable:"\u012eterpti / redaguoti vaizd\u0105",toggleTableBorder:"Perjungti lentel\u0117s kra\u0161tin\u0119",
deleteTable:"Pa\u0161alinti lentel\u0119",tableProp:"Lentel\u0117s savyb\u0117",htmlToggle:"HTML \u0161altinis",foreColor:"Priekinio plano spalva",hiliteColor:"Fono spalva",plainFormatBlock:"Pastraipos stilius",formatBlock:"Pastraipos stilius",fontSize:"\u0160rifto dydis",fontName:"\u0160rifto pavadinimas",tabIndent:"Tabuliacijos \u012ftrauka",fullScreen:"Perjungti vis\u0105 ekran\u0105",viewSource:"Per\u017ei\u016br\u0117ti HTML \u0161altin\u012f",print:"Spausdinti",newPage:"Naujas puslapis",systemShortcut:'"${0}" veiksm\u0105 galima atlikti nar\u0161ykl\u0117je tik naudojant spart\u0173j\u012f klavi\u0161\u0105. Naudokite ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dydis",fontName:"\u0160riftas",formatBlock:"Formatuoti",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"N\u0117ra",p:"Pastraipa",h1:"Antra\u0161t\u0117",h2:"Paantra\u0161t\u0117",h3:"Antrin\u0117 paantra\u0161t\u0117",pre:"I\u0161 anksto suformatuota",1:"xx ma\u017eas",2:"x ma\u017eas",3:"ma\u017eas",4:"vidutinis",5:"didelis",6:"x didelis",
7:"xx didelis",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",
findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/DataAggregation/setting/nls/strings":{locatorUrl:"Lokatoriaus URL",set:"Grup\u0117",locatorName:"Lokatoriaus pavadinimas",locatorExample:"Pavyzdys",countryCode:"\u0160alies arba regiono kodas (-ai)",eg:"pvz. ",countryCodeHint:"Jei \u0161i reik\u0161m\u0117 nebus nurodyta, bus ie\u0161komos visos \u0161alys ir regionai",
minCandidateScore:"Minimalus kandidato \u012fvertinimas",minCandidateScoreHint:"Palikus \u0161i\u0105 reik\u0161m\u0119 tu\u0161\u010di\u0105, bus naudojamas ma\u017eiausias kandidato \u012fvertinimas \u2013 90",enableSingleField:"Vieno lauko parinktis",singleFieldHint:"Adreso duomenys yra viename lauke",enableMultiField:"Keli\u0173 lauk\u0173 parinktys",multiFieldHint:"Adreso duomenys yra keliuose laukuose",enableXYField:"X/Y lauk\u0173 parinktys",xyFieldHint:"Duomenyse bus X/Y koordina\u010di\u0173 reik\u0161m\u0117s",
instructionGeocode:"\u012etraukite ir konfig\u016bruokite lokatoriaus paslaugas.",invalidUrlTip:"URL ${URL} yra neteisingas arba nepasiekiamas.",geocodeTabLabel:"Vietos parametrai",lookupList:"Lauk\u0173 pavadinimai, skirti atpa\u017einti",isRecognized:"Tolesn\u0117je lentel\u0117je esantys lauk\u0173 pavadinimai yra automati\u0161kai pripa\u017e\u012fstami \u0161iam laukui",needsEditablePointLayers:"Internetiniame \u017eem\u0117lapyje turi b\u016bti bent vienas redaguojamas ta\u0161k\u0173 sluoksnis.",
editpageAlias:"Pseudonimas",configureFields:"Konfig\u016bruoti sluoksnio laukus",configureSingleFields:"Konfig\u016bruoti vien\u0105 adreso lauk\u0105",configureMultiFields:"Konfig\u016bruoti kelis adreso laukus",configureXYFields:"Konfig\u016bruoti X/Y laukus",noFields:"Nor\u0117dami apibr\u0117\u017eti vien\u0105 arba kelis rodytinus laukus, naudokite redagavimo veiksm\u0105",display:"Rodyti",duplicate:"Rasti dublikat\u0105",duplicateTip:"\u0160iame lauke ie\u0161kokite identi\u0161k\u0173 \u0161altinio failo ir tikslinio sluoksnio reik\u0161mi\u0173./n Radus identi\u0161k\u0105 atitikmen\u012f, failo \u012fra\u0161as nebus rastas ir bus pa\u017eym\u0117tas kaip dublikatas.",
noSelectField:"Pirmiausia pasirinkite elemento sluoksnio parinkt\u012f",newNamePlaceholder:"",xyFieldsLabelX:"X (ilguma)",xyFieldsLabelY:"Y (platuma)",xyFieldsX:"X",xyFieldsY:"Y",easting:"Platumos poslinkis",northing:"Ilgumos poslinkis",lon:"Ilguma",lat:"Platuma",layerOptionHint:"Pasirinkite sluoksn\u012f, \u012f kur\u012f norite pateikti duomenis.",layerFieldTitle:"Tikslinis sluoksnis",tempSymbolHint:"Pasirinkite simbol\u012f, kuris bus naudojamas elementams rodyti.",tempSymbolTitle:"Rodymo simbolis",
maxRecords:"Maks. \u012fra\u0161\u0173",maxRecordsHint:"Maksimalus rastin\u0173 \u012fra\u0161\u0173 skai\u010dius",searchRadius:"Paie\u0161kos spindulys",searchRadiusHint:"Dubliuot\u0173 element\u0173 i\u0161 sluoksnio atstumo paie\u0161ka",requiresInteger:"\u012eveskite skaitin\u0119 reik\u0161m\u0119.",requiresInteger0100:"\u012eveskite skaitin\u0119 reik\u0161m\u0119 nuo 0 iki 100",requiresLocator:"\u012etraukite bent vien\u0105 tinkam\u0105 lokatori\u0173.",layerFields:"Sluoksnio parametrai",
layerFieldsHint:"Nurodykite laukus i\u0161 Tikslinio sluoksnio, kurie bus susieti su \u0161altinio laukais.",locatorError:"Lokatorius netinkamas arba nepasiekiamas.",optionNotMatch:"Lauko parinktys skirtinguose lokatoriuose nesutampa. Rezervinis serveris gali neveikti kaip tikimasi.",targetLayerTabTitle:"Tikslinis sluoksnis",locationSettingsTabTitle:"Vietos parametrai",generalSettingsTabTitle:"Bendrieji parametrai",addTargetLayersLabel:"\u012etraukti tikslin\u012f sluoksn\u012f",introductoryText:"Kurti valdiklio instrukcij\u0173 turin\u012f",
defaultStartPageInstructions:"\u0160is valdiklis pad\u0117s apdoroti ir pateikti failo duomenis pasirinktame \u017eem\u0117lapio sluoksnyje.\x3cbr/\x3e \x3cbr/\x3e Reik\u0161m\u0117s faile turi b\u016bti atskirtos kableliais, tabuliavimo \u017eingsniais, kabliata\u0161kiais arba vertikaliaisiais br\u016bk\u0161niais.",noTargetLayerConfiguredErrorMsg:"Tikslinis sluoksnis nesukonfig\u016bruotas",noFieldsForTargetLayer:"Neapibr\u0117\u017eti tikslinio sluoksnio nustatymai",locationSettingsNotConfigured:"Vietos nustatymai sukonfig\u016bruoti netinkamai",
_localized:{}}});