// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/Color dojo/Deferred esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/request esri/main esri/layers/LayerDrawingOptions esri/renderers/UniqueValueRenderer".split(" "),function(t,u,m,n,v,p,k,q,w,x,y,l){return t(null,{_drsExtensionUrl:null,_queryParams:null,_reviewerMapServerUrl:null,pointSymbol:null,lineSymbol:null,polySymbol:null,_fieldQualifier:null,_colorMapCache:null,SEVERITY_COLORS:{1:"#D80202",
2:"#DF370C",3:"#E76D16",4:"#E76D16",5:"#FFEC5A"},LIFECYCLEPHASE_COLORS:{2:"#C00000",4:"#FFFF00",6:"#92D050"},DEFAULT_COLOR:"#00C5FF",defaultColor:null,constructor:function(a,b,d,c,f){a=x.urlToObject(a);this._drsExtensionUrl=a.path;this._queryParams=a.query;a=this._drsExtensionUrl.toLowerCase().lastIndexOf("/exts/");0<a&&(this._reviewerMapServerUrl=this._drsExtensionUrl.substring(0,a));this.defaultColor=null!==f?f:new n(this.DEFAULT_COLOR);this.pointSymbol=null!==b?b:new p(p.STYLE_CIRCLE,7,null,this.defaultColor);
this.lineSymbol=null!==d?d:new k(k.STYLE_SOLID,this.defaultColor,5);this.polySymbol=null!==c?c:new q(q.STYLE_SOLID,null,this.defaultColor);this._colorMapCache={}},getLayerDrawingOptions:function(a,b,d){var c=new v;if(!a)return c;var f=this._reviewerMapServerUrl+"/0";null!==this._fieldQualifier?this._generateLayerDrawingOptions(a,b,d,c):w({url:f,content:{f:"json"},callbackParamName:"callback"}).then(m.hitch(this,function(g){var e=new RegExp(/severity/i);u.forEach(g.fields,m.hitch(this,function(h){if(h.name.match(e))try{var r=
h.name.split(e);this._fieldQualifier=1<r.length?r[0]:"";this._generateLayerDrawingOptions(a,b,d,c)}catch(z){this._errorHandler(z,c)}}))}),m.hitch(this,function(g){this._errorHandler(g,c)}));return c},_generateLayerDrawingOptions:function(a,b,d,c){var f=[];var g=this._mapDashboardFieldNameToFullyQualifiedName(a.fieldName).toLowerCase();f=a.fieldValues;b=this._updateColorMapAndCache(a.fieldName,f,b,d);a=this._createPolyRenderer(g,f,b);d=this._createLineRenderer(g,f,b);g=this._createPointRenderer(g,
f,b);b={layerDrawingOptions:{layerDrawingOptionsArray:[this._createLayerDrawingOptions(0,g),this._createLayerDrawingOptions(1,d),this._createLayerDrawingOptions(2,a)],colorMap:b}};c.resolve(b)},_updateColorMapAndCache:function(a,b,d,c){if(null===d){if(0<=a.toLowerCase().indexOf("severity")||0<=a.toLowerCase().indexOf("lifecyclephase"))c=!0;d=this._colorMapCache.hasOwnProperty(a)?this._colorMapCache[a]:this._createDefaultColorMap(a)}b=this._appendMissingValuesToColorMap(b,d,c);return this._colorMapCache[a]=
b},_appendMissingValuesToColorMap:function(a,b,d){var c=0,f;for(f in b)b.hasOwnProperty(f)&&++c;for(c=0;c<a.length;c++)b.hasOwnProperty(a[c])||(b[a[c]]=d?this.defaultColor:new n(this.getColor(c)));return b},getColor:function(a){var b="#E8940C #98C000 #0CBDE8 #F2DA9A #E74327 #DECF3F #878786 #452B7F #9A8B76 #B2912F #9893da #139887".split(" ");return 11>a?b[a]:"#"+Math.floor(16777215*Math.random()).toString(16)},_createLayerDrawingOptions:function(a,b){var d=new y;d.layerId=a;d.renderer=b;return d},
_createDefaultColorMap:function(a){return 0<=a.toLowerCase().indexOf("severity")?this._getColorMap(this.SEVERITY_COLORS):0<=a.toLowerCase().indexOf("lifecyclephase")?this._getColorMap(this.LIFECYCLEPHASE_COLORS):{}},_getColorMap:function(a){var b={},d;for(d in a)b[d]=new n(a[d]);return b},_mapDashboardFieldNameToFullyQualifiedName:function(a){if(!a||""===a)return"";"FEATUREOBJECTCLASS"===a.toUpperCase()&&(a="ORIGINTABLE");return null!==this._fieldQualifier&&0<this._fieldQualifier.length?this._fieldQualifier+
a:a},_createPolyRenderer:function(a,b,d){for(var c=new l(this.polySymbol,a),f=0;f<b.length;f++){var g=b[f],e=new q;e.style=this.polySymbol.style;d.hasOwnProperty(g)?e.color=d[g]:e.color=this.defaultColor;if(null!==this.polySymbol.outline){var h=new k;h.color=e.color;h.style=this.polySymbol.outline.style;h.width=this.polySymbol.outline.width;e.outline=h}else e.outline=new k(k.STYLE_SOLID,e.color,1);"\x3cNull\x3e"===g&&(c=new l(e,a));c.addValue(g,e)}return c},_createLineRenderer:function(a,b,d){for(var c=
new l(this.lineSymbol,a),f=0;f<b.length;f++){var g=b[f],e=new k;d.hasOwnProperty(g)?e.color=d[g]:e.color=this.defaultColor;e.style=this.lineSymbol.style;e.width=this.lineSymbol.width;"\x3cNull\x3e"===g&&(c=new l(e,a));c.addValue(g,e)}return c},_createPointRenderer:function(a,b,d){for(var c=new l(this.pointSymbol,a),f=0;f<b.length;f++){var g=b[f],e=new p;d.hasOwnProperty(g)?e.color=d[g]:e.color=this.defaultColor;e.outline=this.pointSymbol.outline;e.size=this.pointSymbol.size;e.style=this.pointSymbol.style;
"\x3cNull\x3e"===g&&(c=new l(e,a));c.addValue(g,e)}return c},_errorHandler:function(a,b){null===a&&(a=Error("Unexpected response received from server"),a.code=500);b&&b.reject(a)}})});