// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/string dojo/Evented jimu/BaseWidget esri/request dojo/Deferred dojo/promise/all esri/geometry/projection esri/SpatialReference".split(" "),function(k,f,l,m,n,p,q,r,t,h,u){return k([p,n],{baseClass:"jimu-widget-screening-create-replica",_extractDataTaskGPService:null,errMessageString:"",responseArray:[],layerDetailsObj:{},constructor:function(a){this._extractDataTaskGPService=null;this.errMessageString="";this.responseArray=[];this.layerDetailsObj=
{};f.mixin(this,a)},startup:function(){this.responseArray=[];this.layerDetailsObj={};this._loadProjection()},_init:function(){var a,b,d;l.forEach(this.config.downloadSettings.layers,f.hitch(this,function(c){var e;if(this.downloadFeatureDetailsObj[c.id]&&0<this.downloadFeatureDetailsObj[c.id].length&&-1<c.downloadingFileOption.indexOf(this.fileFormat)&&c.allowDownload){a=c.url.split("/");b=parseInt(a.pop(),10);a=a.join("/");var g=!1;for(e in this.layerDetailsObj)e.toLowerCase()===a.toLowerCase()&&
(g=!0,a=e);g||(this.layerDetailsObj[a]={layerInstance:c,layerIndexes:[],layerDetails:{},layerNames:[],wkid:this.filterLayerObj[c.id].spatialReference.wkid});this.layerDetailsObj[a].layerIndexes.push(b);this.layerDetailsObj[a].layerNames.push(c.layerName);this.layerDetailsObj[a].layerDetails[b]={queryOption:"useFilter",useGeometry:!0,where:this.filterLayerObj[c.id].getDefinitionExpression()||""}}}));this.errMessageString="";for(d in this.layerDetailsObj)this.responseArray.push(this._exportFileUsingCreateReplica(d,
this.layerDetailsObj[d]));t(this.responseArray).then(f.hitch(this,function(){this.errMessageString?(this.errMessageString=m.substitute(this.nls.reportsTab.createReplicaFailedMessage,{layerNames:this.errMessageString}),this.emit("createReplicaComplete",this.errMessageString)):this.emit("createReplicaComplete")}))},_exportFileUsingCreateReplica:function(a,b){var d=this._removeDuplicateLayerIds(b.layerIndexes);var c=new r;if("shapefile"===this.fileFormat){var e=new u({wkid:b.wkid});e=h.project(this.aoi.geometry,
e)}else e=this.aoi.geometry;d={f:"json",replicaName:b.layerInstance.layerName,layers:d.join(),layerQueries:JSON.stringify(b.layerDetails),inSR:JSON.stringify(this.aoi.geometry.spatialReference),geometry:JSON.stringify(e),geometryType:"esriGeometryPolygon",transportType:"esriTransportTypeUrl",returnAttachments:!1,returnAttachmentsDataByUrl:!1,async:!1,syncModel:"none",dataFormat:this.fileFormat};q({url:a+"/createReplica",content:d,handleAs:"json",callbackParamName:"callback"},{usePost:!0}).then(f.hitch(this,
function(g){this.onRequestSucceeded(c,g)}),f.hitch(this,function(g){this.errMessageString&&(this.errMessageString+=", ");this.errMessageString+=b.layerNames.join(", ");this.onRequestFailed(c,g)}));return c.promise},_removeDuplicateLayerIds:function(a){return a.filter(function(b,d,c){return d===c.indexOf(b)})},onRequestSucceeded:function(a,b){a.resolve();if(b.responseUrl)var d=b.responseUrl;else b.URL?d=b.URL:b.resultUrl&&(d=b.resultUrl);d&&this.emit("onRequestSucceeded",d)},onRequestFailed:function(a,
b){a.resolve();this.emit("onRequestFailed",b)},_loadProjection:function(){"shapefile"===this.fileFormat?h.load().then(f.hitch(this,function(){this._init()}),f.hitch(this,function(){this.loadingIndicator.hide();this.emit("showMessage",this.nls.reportsTab.errorInLoadingProjectionModule)})):this._init()}})});