// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/Evented jimu/BaseWidget dojo/_base/html dojo/_base/array dojo/on dijit/TooltipDialog jimu/dijit/formSelect dojo/dom-construct dijit/popup jimu/dijit/Message jimu/CSVUtils ./extractDataTask ./createReplica dojo/dom-class jimu/utils dijit/focus dojo/keys dojo/_base/event".split(" "),function(v,g,w,x,y,l,h,z,A,m,t,B,C,D,E,F,G,q,n,p){return v([x,w],{baseClass:"jimu-widget-screening",_popup:null,downloadOptions:[],isTooltipDialogOpened:!1,downLoadStatus:{},
constructor:function(a){this._popup=null;this.downloadOptions=[];this.isTooltipDialogOpened=!1;this.downLoadStatus={};g.mixin(this,a)},startup:function(){this._popup=new z({"class":"esriCTDownloadSettingsDialog "+this.baseClass,style:{width:"300px"}});"DartTheme"===this.appConfig.theme.name&&F.add(this._popup.domNode,"dart-panel");this._popup.startup();this.own(h(document.body,"click",g.hitch(this,function(a){this.isPartOfPopup(a.target||a.srcElement)||this.closePopup()})));this.own(h(window,"resize",
g.hitch(this,function(){this.closePopup()})));this._createSettingsDialog()},checkFileForDownload:function(){var a,b;var c=a=b=!1;"extractDataTask"===this.config.downloadSettings.type&&(c=a=b=!0);var d=this._getFilteredDownloadLayers();l.forEach(d,g.hitch(this,function(e){e.allowDownload&&this.downloadFeatureDetailsObj[e.id]&&0<this.downloadFeatureDetailsObj[e.id].length&&(0<=e.downloadingFileOption.indexOf("csv")&&(c=!0),0<=e.downloadingFileOption.indexOf("shapefile")&&(a=!0),0<=e.downloadingFileOption.indexOf("filegdb")&&
(b=!0))}));this.downLoadStatus={isCSVAvailable:c,isShapeFileAvailable:a,isFileGDBAvailable:b}},_createSettingsDialog:function(){var a=m.create("div",{"class":"esriCTDownloadSettingsContainer"},null);m.create("div",{"class":"esriCTEllipsis esriCTDownloadSettingLabel",innerHTML:this.nls.reportsTab.downloadLabelText},a);this.downloadFormatSelect=new A({"aria-label":this.nls.reportsTab.downloadLabelText});this.own(h(this.downloadFormatSelect,"keydown",g.hitch(this,function(c){c.keyCode===n.ESCAPE&&(p.stop(c),
this.closePopup(),this.emit("setFocusOnDownloadReportButton"))})));this._getOptionsFordownloadFormat();this.downloadFormatSelect.placeAt(a);var b=m.create("button",{innerHTML:this.nls.reportsTab.downloadBtnText,"class":"esriCTEllipsis jimu-btn esriCTDownloadSettingsBtn",tabindex:0,"aria-label":this.nls.reportsTab.downloadBtnText,role:"button"},m.create("div",{"class":"esriCTDownloadSettingsBtnContainer"},a));this.own(h(b,"click",g.hitch(this,function(c){p.stop(c);this.closePopup();this.emit("setFocusOnDownloadReportButton");
this.isAndroidDevice?this._startDownload():this._chooseFileTypeToDownload()})));this.own(h(b,"keydown",g.hitch(this,function(c){if(c.keyCode===n.ENTER||c.keyCode===n.SPACE)p.stop(c),this.closePopup(),this.emit("setFocusOnDownloadReportButton"),this.isAndroidDevice?this._startDownload():this._chooseFileTypeToDownload();c.keyCode===n.ESCAPE&&(p.stop(c),this.closePopup(),this.emit("setFocusOnDownloadReportButton"))})));this._popup.setContent(a)},_loadOptionsForDropDown:function(a,b){var c=[],d;l.forEach(b,
g.hitch(this,function(e){d={value:e,label:this.nls.reportsTab[e]};c.push(d)}));a.addOption(c)},_getOptionsFordownloadFormat:function(){if("extractDataTask"===this.config.downloadSettings.type)var a=["csv","filegdb","shapefile"];else{var b=[];a=["csv"];b=this._getFilteredDownloadLayers();l.forEach(b,g.hitch(this,function(c){var d=["csv"];if(c.allowDownload){var e=this.filterLayerObj[c.id].capabilities;var f=this.filterLayerObj[c.id].version;1<e.split("Sync").length&&10.4<=f&&(-1===d.indexOf("filegdb")&&
d.push("filegdb"),-1===a.indexOf("filegdb")&&a.push("filegdb"),G.isHostedService(c.url)&&(-1===d.indexOf("shapefile")&&d.push("shapefile"),-1===a.indexOf("shapefile")&&a.push("shapefile")));c.downloadingFileOption=d}}))}this._loadOptionsForDropDown(this.downloadFormatSelect,a)},openPopup:function(){t.open({popup:this._popup,x:this.position.pageX,y:this.position.pageY});this.isTooltipDialogOpened=!0},closePopup:function(){this._popup&&(t.close(this._popup),this.isTooltipDialogOpened=!1)},isPartOfPopup:function(a){var b=
this._popup.domNode;return a===b||y.isDescendant(a,b)},_chooseFileTypeToDownload:function(){switch(this.downloadFormatSelect.get("value")){case "csv":this.downLoadStatus.isCSVAvailable?this._exportToCSV():this.emit("showMessage",this.nls.reportsTab.noFeaturesFound);break;case "filegdb":this.downLoadStatus.isFileGDBAvailable?"syncEnable"===this.config.downloadSettings.type?this._exportFileUsingCreateReplica("filegdb"):"extractDataTask"===this.config.downloadSettings.type&&this.isPointOrLineAOI?this.emit("showMessage",
this.nls.reportsTab.unableToDownloadFileGDBText):this._exportFileUsingExtractDataTask("filegdb"):this.emit("showMessage",this.nls.reportsTab.noFeaturesFound);break;case "shapefile":this.downLoadStatus.isShapeFileAvailable?"syncEnable"===this.config.downloadSettings.type?this._exportFileUsingCreateReplica("shapefile"):"extractDataTask"===this.config.downloadSettings.type&&this.isPointOrLineAOI?this.emit("showMessage",this.nls.reportsTab.unableToDownloadShapefileText):this._exportFileUsingExtractDataTask("shapefile"):
this.emit("showMessage",this.nls.reportsTab.noFeaturesFound)}},_startDownload:function(){var a=new B({titleLabel:this.nls.reportsTab.downloadReportConfirmTitle,message:this.nls.reportsTab.downloadReportConfirmMessage,autoHeight:!0,buttons:[{label:this.nls.common.yes,onClick:g.hitch(this,function(){this._chooseFileTypeToDownload();a.close()})},{label:this.nls.common.no}]})},_exportToCSV:function(){var a,b,c={},d,e,f=[];f=this.config.downloadSettings.layers;this.shapeFileLayerDetails&&(f=f.concat(this.shapeFileLayerDetails));
f=this._getFilteredDownloadLayers();l.forEach(f,g.hitch(this,function(k,r){c={};e=!1;e="extractDataTask"===this.config.downloadSettings.type?!0:k.allowDownload;a=k.isShapeFile?k.layer:this.filterLayerObj[k.id];b=this._getLayerData(a,this.downloadFeatureDetailsObj[k.id]);b=dojo.mixin({},b);b=this._removeAnalysisUnitFromCSV(b);this._addAnalysisDataToCSVData(b,k.id);d=this._getInfoTemplate(a);0<b.graphicsArray.length&&e&&(c.datas=b.graphicsArray,c.fromClient=!1,c.withGeometry="esriGeometryPoint"===a.geometryType,
c.outFields=b.outFields,c.formatNumber=!1,c.formatDate=!0,c.formatCodedValue=!0,(c.popupInfo=d)&&d.expressionInfos&&(c.outFields=this.appendArcadeExpressionsToFields(c.outFields,d.expressionInfos)),this._exportToCSVFile(a,c,r+1))}))},appendArcadeExpressionsToFields:function(a,b){if(a){if(0<b.length){var c=/^expression\//;l.forEach(b,function(d){l.some(a,function(e){if(c.test(e.name))return e=e.name.substr(11),d.name===e})||a.push({name:"expression/"+d.name,alias:d.title,show:!0})})}return a}},_exportToCSVFile:function(a,
b,c){setTimeout(g.hitch(this,function(){C.exportCSVFromFeatureLayer(a.name||"CSV_FILE",a,b)}),100*c)},_removeAnalysisUnitFromCSV:function(a){var b=a.outFields;l.forEach(b,function(c,d){"CSVMeasurementUnit"===c.name&&b.splice(d,1)});return a},_getInfoTemplate:function(a){var b;if(a.infoTemplate)return a.infoTemplate.info;var c=a.id.split("_");if(c[c.length-1]===a.layerId.toString()){c.pop();var d=c.join("_")}d&&(b=this.map.getLayer(d));return b&&b.infoTemplates&&b.infoTemplates.hasOwnProperty(a.layerId)?
b.infoTemplates[a.layerId].infoTemplate.info:null},_getLayerData:function(a,b){var c=[];l.forEach(b,g.hitch(this,function(d){d.attributes.geometry=d.geometry;c.push(d.attributes)}));return"esriGeometryPoint"===a.geometryType?(a=this._formatPointLayerData(c,a),{graphicsArray:a.layerGraphics,outFields:a._outFields}):{graphicsArray:c,outFields:a.fields}},_formatPointLayerData:function(a,b){var c={};a=g.clone(a);b=b.fields;l.forEach(a,function(e){var f=e.geometry;f&&"point"===f.type&&("x"in e?e._x=f.x:
e.x=f.x,"y"in e?e._y=f.y:e.y=f.y);delete e.geometry});b=g.clone(b);var d="";d=-1!==b.indexOf("x")?"_x":"x";b.push({name:d,alias:d,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});d=-1!==b.indexOf("y")?"_y":"y";b.push({name:d,alias:d,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});c.layerGraphics=a;c._outFields=b;return c},_exportFileUsingExtractDataTask:function(a){this.loadingIndicator.show();a=new D({map:this.map,aoi:this.aoi,fileFormat:a,url:this.config.downloadSettings.extractDataTaskURL});
a.startup();this.own(h(a,"onGPTaskSuccess",g.hitch(this,function(b){this._downloadDataFile(b);this.loadingIndicator.hide()})));this.own(h(a,"onGPTaskFailed",g.hitch(this,function(){this.emit("showMessage",this.nls.reportsTab.extractDataTaskFailedMessage);this.loadingIndicator.hide()})))},_exportFileUsingCreateReplica:function(a){this.loadingIndicator.show();a=new E({map:this.map,config:this.config,aoi:this.aoi,fileFormat:a,filterLayerObj:this.filterLayerObj,nls:this.nls,downloadFeatureDetailsObj:this.downloadFeatureDetailsObj,
loadingIndicator:this.loadingIndicator});this.own(h(a,"onRequestSucceeded",g.hitch(this,function(b){this._downloadDataFile(b);this.loadingIndicator.hide()})));this.own(h(a,"onRequestFailed",g.hitch(this,function(){this.loadingIndicator.hide()})));this.own(h(a,"createReplicaComplete",g.hitch(this,function(b){b&&this.emit("showMessage",b);this.loadingIndicator.hide()})));this.own(h(a,"showErrMessage",g.hitch(this,function(b){this.emit("showMessage",b)})));a.startup()},_downloadDataFile:function(a){var b;
for(b in this.filterLayerObj)if(this.filterLayerObj.hasOwnProperty(b)){var c=this.filterLayerObj[b];if(c.credential&&c.credential.token){var d=a.split("replicafiles");var e=c.url;var f=d[0].toLowerCase();f=f.replace(/(^\w+:|^)\/\//,"");if(0<d.length&&-1<e.toLowerCase().indexOf(f.toLowerCase())){a=a+"?token\x3d"+c.credential.token;break}}}var k=m.create("iframe",{"class":"esriCTHidden",src:a},this.iframeNode);var r=setInterval(g.hitch(this,function(){var u=k.contentDocument||k.contentWindow.document;
if("complete"===u.readyState||"interactive"===u.readyState)m.destroy(k),clearInterval(r)}),4E3)},_addAnalysisDataToCSVData:function(a,b){var c,d;var e=a.graphicsArray.length;if(0<e){for(c=0;c<e;c++){var f=a.graphicsArray[c];if(d=this._getFeatureAnalysisData(b,c))f.CSVMeasurementUnit=d.analysisResultValue}d&&this._addGeometryUnitToFields(a,d)}},_addGeometryUnitToFields:function(a,b){a.outFields.push({alias:b.analysisResultKey+"("+b.analysisUnit+")",name:"CSVMeasurementUnit",type:"esriFieldTypeDouble"})},
_getFeatureAnalysisData:function(a,b){var c,d={};var e="";for(c in this.printData){var f=this.printData[c];if(-1!==c.indexOf(a)&&"esriGeometryPoint"!==f.geometryType){if("esriGeometryPolyline"===f.geometryType)return e=this._getAnalysisUnitForGeometry(this.lengthUnits,f.geometryType),a=this.lengthUnits+"UnitInfo",a=this._lowerCaseFirstLetter(a),d.analysisResultValue=f[a][b],d.analysisResultKey=this._getAnalysisResultKey(f.geometryType),d.analysisUnit=e,d;if("esriGeometryPolygon"===f.geometryType)return e=
this._getAnalysisUnitForGeometry(this.areaUnits,f.geometryType),a=this.areaUnits+"UnitInfo",a=this._lowerCaseFirstLetter(a),d.analysisResultValue=f[a][b],d.analysisResultKey=this._getAnalysisResultKey(f.geometryType),d.analysisUnit=e,d}}},_getAnalysisResultKey:function(a){if("esriGeometryPolygon"===a)return this.nls.reportsTab.featureCSVAreaText;if("esriGeometryPolyline"===a)return this.nls.reportsTab.featureCSVLengthText},_getAnalysisUnitForGeometry:function(a,b){switch(a){case "Feet":case "SquareFeet":var c=
"esriGeometryPolygon"===b?this.nls.units.squareFeetAbbr:this.nls.units.feetAbbr;break;case "Miles":case "Acres":c="esriGeometryPolygon"===b?this.nls.units.acresAbbr:this.nls.units.milesAbbr;break;case "Meters":case "SquareMeters":c="esriGeometryPolygon"===b?this.nls.units.squareMetersAbbr:this.nls.units.metersAbbr;break;case "Kilometers":case "SquareKilometers":c="esriGeometryPolygon"===b?this.nls.units.squareKilometerAbbr:this.nls.units.kilometersAbbr;break;case "Hectares":c="esriGeometryPolygon"===
b?this.nls.reportsTab.hectaresAbbr:this.nls.units.kilometersAbbr;break;case "SquareMiles":c="esriGeometryPolygon"===b?this.nls.reportsTab.squareMilesAbbr:this.nls.units.milesAbbr}return c},_getFilteredDownloadLayers:function(){var a=[];a=[];a=this.config.downloadSettings.layers;return a=a.filter(g.hitch(this,function(b){return this.filterLayerObj.hasOwnProperty(b.id)?!0:!1}))},setFocusOnFormatDropdown:function(){this._focusOutCurrentNode();q.focus(this.downloadFormatSelect)},_lowerCaseFirstLetter:function(a){return a.charAt(0).toLowerCase()+
a.slice(1)},_focusOutCurrentNode:function(){q.curNode&&q.curNode.blur()}})});