// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Grassetto",copy:"Copia",cut:"Taglia","delete":"Elimina",indent:"Rientro",insertHorizontalRule:"Righello orizzontale",insertOrderedList:"Elenco numerato",insertUnorderedList:"Elenco puntato",italic:"Corsivo",justifyCenter:"Allinea al centro",justifyFull:"Giustifica",justifyLeft:"Allinea a sinistra",justifyRight:"Allinea a destra",outdent:"Annulla rientro",paste:"Incolla",redo:"Ripristina",removeFormat:"Rimuovi formato",selectAll:"Seleziona tutto",strikethrough:"Barrato",
subscript:"Pedice",superscript:"Apice",underline:"Sottolinea",undo:"Annulla",unlink:"Rimuovi collegamento",createLink:"Crea collegamento",toggleDir:"Attiva/Disattiva direzione",insertImage:"Inserisci immagine",insertTable:"Inserisci/Modifica tabella",toggleTableBorder:"Attiva/Disattiva bordo tabella",deleteTable:"Elimina tabella",tableProp:"Propriet\u00e0 tabella",htmlToggle:"Origine HTML",foreColor:"Colore primo piano",hiliteColor:"Colore sfondo",plainFormatBlock:"Stile paragrafo",formatBlock:"Stile paragrafo",
fontSize:"Dimensione carattere",fontName:"Nome carattere",tabIndent:"Rientro tabulazione",fullScreen:"Attiva/Disattiva schermo intero",viewSource:"Visualizza origine HTML",print:"Stampa",newPage:"Nuova pagina",systemShortcut:'La azione "${0}" \u00e8 disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"widgets/BusinessAnalyst/nls/strings":{_widgetLabel:"Business Analyst",addPoint:"Aggiungere il punto facendo clic sulla mappa",
addPolygon:"Crea poligono disegnando sulla mappa",addFreehandPolygon:"Crea poligono a mano libera disegnando sulla mappa",addRingsDtWt:"Aggiungere anello, tempo di guida o tempo di camminata.",apply:"Applica",back:"Indietro",colon:":",creditInformation:"Informazioni di credito",customPolygon:"Poligono personalizzato",driveTime:"Tempo di guida",esriInfographics:"Infografica Esri",esriReports:"Report Esri",headerDescription_km:"chilometro",headerDescription_miles:"miglia",headerDescription_minutes:"minuto",
infographics:"Infografica",invalidValueRing:"Il valore deve essere compreso tra 0 e 1000.",invalidValueDTWT:"Il valore deve essere compreso tra 0 e 300.",km:"km",miles:"miglia",minutes:"minuti",myInfographics:"La mia infografica",myReports:"I miei report",noPermissions:'L\u2019account non pu\u00f2 eseguire il widget Business Analyst. Per eseguire il widget Business Analyst, l\'amministratore dell\u2019organizzazione deve concedere \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3eprivilegi\x3c/a\x3e GeoEnrichment e Network Analysis e anche stanziare \x3ca href\x3d"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?" target\x3d"_blank"\x3ecrediti\x3c/a\x3e.',
geServiceNotConfigured:'Il widget Business Analyst non pu\u00f2 essere eseguito su questo portale, perch\u00e9 non presenta il servizio \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F" target\x3d"_blank"\x3eGeoenrichment\x3c/a\x3e configurato.',dirRoutingServiceNotConfigured:'Il widget Business Analyst non pu\u00f2 essere eseguito su questo portale, perch\u00e9 non presenta il servizio \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85" target\x3d"_blank"\x3eIndicazioni e routing\x3c/a\x3e configurato.',
geAndDirRoutingServicesNotConfigured:'Il widget Business Analyst non pu\u00f2 essere eseguito su questo portale, perch\u00e9 non presenta i servizi \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F" target\x3d"_blank"\x3eGeoenrichment\x3c/a\x3e e \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85" target\x3d"_blank"\x3eIndicazioni e routing\x3c/a\x3e configurati.',
radii:"raggi",radius:"Raggio",radius_lowercase:"raggio",reports:"Report",ring:"Anello",rings:"Anelli",runInfographic:"Eseguire infografica",runReport:"Esegui report",selectPointOrPolygon:"Selezionare un punto o un poligono sulla mappa, cercare un indirizzo o luogo, disegnare un poligono o rilasciare una puntina sulla mappa per visualizzare gli indicatori chiave e informazioni sull'area.",selectReport:"Seleziona report",selectTemplate:"Seleziona modello",sharedInfographics:"Infografiche condivise",
sharedReports:"Report condivisi",thisEntryIsNotValid:"Voce non valida.",time:"Tempo",walkTime:"Tempo di camminata",widgetDescription:"Accedere a infografiche e report che riepilogano indicatori e dati chiave per qualsiasi area.",None:"Seleziona...",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dimensione",fontName:"Carattere",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",monospace:"spaziatura fissa",cursive:"corsivo",fantasy:"fantasy",noFormat:"Nessuna",p:"Paragrafo",h1:"Intestazione",
h2:"Sottointestazione",h3:"Sottointestazione secondaria",pre:"Preformattato",1:"piccolissimo",2:"molto piccolo",3:"piccolo",4:"medio",5:"grande",6:"molto grande",7:"grandissimo",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Anteprima",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Trova:",findTooltip:"Immettere il testo da ricercare",replaceLabel:"Sostituisci con:",replaceTooltip:"Immettere il testo con cui sostituire",findReplace:"Trova e sostituisci",matchCase:"Corrispondenza maiuscolo/minuscolo",
matchCaseTooltip:"Corrispondenza maiuscolo/minuscolo",backwards:"Indietro",backwardsTooltip:"Ricercare il testo all'indietro",replaceAllButton:"Sostituisci tutti",replaceAllButtonTooltip:"Sostituisci tutto il testo",findButton:"Trova",findButtonTooltip:"Trova il testo",replaceButton:"Sostituisci",replaceButtonTooltip:"Sostituisci il testo",replaceDialogText:"Sostituite ${0} ricorrenze.",eofDialogText:"Ultime ${0} ricorrenze",eofDialogTextFind:"trovato",eofDialogTextReplace:"sostituito",_localized:{}},
"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Incolla da Word",instructions:"Incollare i contenuti da Word nella seguente casella di testo. Quando si \u00e8 deciso quali contenuti inserire, fare clic sul pulsante incolla. Per interrompere l'inserimento del testo premere il pulsante annulla.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserisci ancoraggio",title:"Propriet\u00e0 ancoraggio",anchor:"Nome:",text:"Descrizione:",set:"Imposta",cancel:"Annulla",_localized:{}},
"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/BusinessAnalyst/setting/nls/strings":{businessAnalyst:"Business Analyst",defaultFirstPageText:"\x3cbr\x3e\x3cdiv\x3eAccedere a infografiche e report che riepilogano indicatori e dati chiave per qualsiasi area.\x3c/div\x3e\x3cbr\x3e\x3cdiv\x3eSelezionare un punto o un poligono sulla mappa, cercare un indirizzo o luogo, disegnare un poligono o rilasciare una puntina sulla mappa per visualizzare gli indicatori chiave e informazioni sull'area.\x3c/div\x3e",
defineWhichInfographics:"Definire le infografiche disponibili nel widget:",defineWhichReports:"Definire i report disponibili nel widget:",defaultValues:"Valori predefiniti:",disable:"Disabilita",drawFreehandPolygon:"Disegna poligono a mano libera",drawPolygon:"Disegna poligono",driveTime:"Tempo di guida",dropPin:"Posiziona spillo",dynamicHTML:"HTML Dinamico",exportOptions:"Opzioni di esportazione:",home:"Home",image:"Immagine",infographics:"Infografica",invalidValueRing:"Il valore deve essere compreso tra 0 e 1000.",
invalidValueDTWT:"Il valore deve essere compreso tra 0 e 300.",km:"km",makeDefault:"Imposta come predefinito",miles:"miglia",minutes:"minuti",options:"Opzioni:",pdf:"PDF",print:"Stampa",radius:"Raggio",removeDefault:"Rimuovere le impostazioni predefinite",reports:"Report",rings:"Anelli",searchTextBox:"Casella di testo di ricerca",selectCountryOrRegion:"Selezionare paese o regione:",thisEntryIsNotValid:"Voce non valida.",time:"Tempo",walkTime:"Tempo di camminata",_localized:{}}});