// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Pogrubienie",copy:"Kopiuj",cut:"Wytnij","delete":"Usu\u0144",indent:"Wci\u0119cie",insertHorizontalRule:"Linia pozioma",insertOrderedList:"Lista numerowana",insertUnorderedList:"Lista wypunktowana",italic:"Kursywa",justifyCenter:"Wyr\u00f3wnaj do \u015brodka",justifyFull:"Wyr\u00f3wnaj do lewej i prawej",justifyLeft:"Wyr\u00f3wnaj do lewej",justifyRight:"Wyr\u00f3wnaj do prawej",outdent:"Usu\u0144 wci\u0119cie",paste:"Wklej",redo:"Pon\u00f3w",removeFormat:"Usu\u0144 formatowanie",
selectAll:"Wybierz wszystko",strikethrough:"Przekre\u015blenie",subscript:"Indeks dolny",superscript:"Indeks g\u00f3rny",underline:"Podkre\u015blenie",undo:"Cofnij",unlink:"Usu\u0144 odsy\u0142acz",createLink:"Utw\u00f3rz odsy\u0142acz",toggleDir:"Prze\u0142\u0105cz kierunek",insertImage:"Wstaw obraz",insertTable:"Wstaw/edytuj tabel\u0119",toggleTableBorder:"Prze\u0142\u0105cz ramk\u0119 tabeli",deleteTable:"Usu\u0144 tabel\u0119",tableProp:"W\u0142a\u015bciwo\u015b\u0107 tabeli",htmlToggle:"\u0179r\u00f3d\u0142o HTML",
foreColor:"Kolor pierwszego planu",hiliteColor:"Kolor t\u0142a",plainFormatBlock:"Styl akapitu",formatBlock:"Styl akapitu",fontSize:"Wielko\u015b\u0107 czcionki",fontName:"Nazwa czcionki",tabIndent:"Wci\u0119cie o tabulator",fullScreen:"Prze\u0142\u0105cz pe\u0142ny ekran",viewSource:"Wy\u015bwietl kod \u017ar\u00f3d\u0142owy HTML",print:"Drukuj",newPage:"Nowa strona",systemShortcut:"Dzia\u0142anie ${0} jest dost\u0119pne w tej przegl\u0105darce wy\u0142\u0105cznie przy u\u017cyciu skr\u00f3tu klawiaturowego. Nale\u017cy u\u017cy\u0107 klawiszy ${1}.",
ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"widgets/BusinessAnalyst/nls/strings":{_widgetLabel:"Business Analyst",addPoint:"Dodaj punkt, klikaj\u0105c na mapie",addPolygon:"Utw\u00f3rz poligon, rysuj\u0105c na mapie",addFreehandPolygon:"Utw\u00f3rz poligon odr\u0119czny, rysuj\u0105c na mapie",addRingsDtWt:"Dodaj pier\u015bcienie, czas przejazdu lub czas pokonania trasy pieszej.",apply:"Zastosuj",back:"Wstecz",colon:":",creditInformation:"Informacje o kredytach",customPolygon:"Poligon niestandardowy",
driveTime:"Czas przejazdu",esriInfographics:"Infografiki Esri",esriReports:"Raporty Esri",headerDescription_km:"kilometr",headerDescription_miles:"mila",headerDescription_minutes:"minuta",infographics:"Infografiki",invalidValueRing:"Warto\u015bci musz\u0105 nale\u017ce\u0107 do zakresu od 0 do 1 000.",invalidValueDTWT:"Warto\u015bci musz\u0105 nale\u017ce\u0107 do zakresu od 0 do 300.",km:"km",miles:"mil",minutes:"minut(y)",myInfographics:"Moje infografiki",myReports:"Moje raporty",noPermissions:'Na Twoim koncie nie mo\u017cna uruchomi\u0107 wid\u017cetu Business Analyst.  Aby uruchomi\u0107 wid\u017cet Business Analyst, administrator instytucji musi nada\u0107 Tobie \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3euprawnienia\x3c/a\x3e do wzbogacania danych przestrzennych i analizy sieciowej, a tak\u017ce przydzieli\u0107 \x3ca href\x3d"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?" target\x3d"_blank"\x3ekredyty\x3c/a\x3e.',
geServiceNotConfigured:'Nie mo\u017cna uruchomi\u0107 wid\u017cetu Business Analyst w tym portalu, poniewa\u017c nie zosta\u0142a w nim skonfigurowana us\u0142uga \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F" target\x3d"_blank"\x3ewzbogacania danych przestrzennych\x3c/a\x3e.',dirRoutingServiceNotConfigured:'Nie mo\u017cna uruchomi\u0107 wid\u017cetu Business Analyst w tym portalu, poniewa\u017c nie zosta\u0142a w nim skonfigurowana us\u0142uga \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85" target\x3d"_blank"\x3ewskaz\u00f3wek dojazdu i wyznaczania tras\x3c/a\x3e.',
geAndDirRoutingServicesNotConfigured:'Nie mo\u017cna uruchomi\u0107 wid\u017cetu Business Analyst w tym portalu, poniewa\u017c nie zosta\u0142y w nim skonfigurowane us\u0142ugi \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F" target\x3d"_blank"\x3ewzbogacania danych przestrzennych\x3c/a\x3e oraz \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85" target\x3d"_blank"\x3ewskaz\u00f3wek dojazdu i wyznaczania tras\x3c/a\x3e.',
radii:"promienie",radius:"Promie\u0144",radius_lowercase:"promie\u0144",reports:"Raporty",ring:"Pier\u015bcie\u0144",rings:"Pier\u015bcienie",runInfographic:"Uruchom infografik\u0119",runReport:"Uruchom raport",selectPointOrPolygon:"Wybierz na mapie punkt lub poligon, wyszukaj adres lub miejsce, narysuj poligon albo umie\u015b\u0107 na mapie szpilk\u0119, aby wy\u015bwietli\u0107 kluczowe wska\u017aniki i informacje o tym obszarze.",selectReport:"Wybierz raport",selectTemplate:"Wybierz szablon",sharedInfographics:"Udost\u0119pnione infografiki",
sharedReports:"Udost\u0119pnione raporty",thisEntryIsNotValid:"Ten wpis nie jest prawid\u0142owy.",time:"Czas",walkTime:"Czas pokonania trasy pieszej",widgetDescription:"Uzyskaj dost\u0119p do infografik i raport\u00f3w podsumowuj\u0105cych kluczowe wska\u017aniki i dane w dowolnym obszarze.",None:"Wybierz...",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Rozmiar",fontName:"Czcionka",formatBlock:"Format",serif:"szeryfowa","sans-serif":"bezszeryfowa",monospace:"czcionka o sta\u0142ej szeroko\u015bci",
cursive:"kursywa",fantasy:"fantazyjna",noFormat:"Brak",p:"Akapit",h1:"Nag\u0142\u00f3wek",h2:"Nag\u0142\u00f3wek 2-go poziomu",h3:"Nag\u0142\u00f3wek 3-go poziomu",pre:"Wst\u0119pnie sformatowane",1:"najmniejsza",2:"mniejsza",3:"ma\u0142a",4:"\u015brednia",5:"du\u017ce",6:"wi\u0119ksza",7:"najwi\u0119ksza",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Podgl\u0105d",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Znajd\u017a:",findTooltip:"Wprowad\u017a szukany tekst",
replaceLabel:"Zast\u0105p przez:",replaceTooltip:"Wprowad\u017a tekst zast\u0119puj\u0105cy",findReplace:"Znajd\u017a i zast\u0105p",matchCase:"Uwzgl\u0119dnij wielko\u015b\u0107 liter",matchCaseTooltip:"Uwzgl\u0119dnij wielko\u015b\u0107 liter",backwards:"Do ty\u0142u",backwardsTooltip:"Wyszukaj tekst wstecz",replaceAllButton:"Zast\u0105p wszystko",replaceAllButtonTooltip:"Zast\u0105p ca\u0142y tekst",findButton:"Znajd\u017a",findButtonTooltip:"Znajd\u017a tekst",replaceButton:"Zast\u0105p",replaceButtonTooltip:"Zast\u0105p tekst",
replaceDialogText:"Zast\u0105pione wyst\u0105pienia: ${0}.",eofDialogText:"Ostatnie wyst\u0105pienie: ${0}",eofDialogTextFind:"znaleziono",eofDialogTextReplace:"zast\u0105pione",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Wklej z programu Word",instructions:"Wklej tekst z programu Word do poni\u017cszego pola tekstowego. Po uzyskaniu odpowiedniej tre\u015bci do wstawienia kliknij przycisk Wklej. Aby przerwa\u0107 wstawianie tre\u015bci, kliknij przycisk Anuluj.",_localized:{}},
"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Wstaw zakotwiczenie",title:"W\u0142a\u015bciwo\u015bci zakotwiczenia",anchor:"Nazwa:",text:"Opis:",set:"Ustaw",cancel:"Anuluj",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Cytat blokowy",_localized:{}},"widgets/BusinessAnalyst/setting/nls/strings":{businessAnalyst:"Business Analyst",defaultFirstPageText:"\x3cbr\x3e\x3cdiv\x3eUzyskaj dost\u0119p do infografik i raport\u00f3w podsumowuj\u0105cych kluczowe wska\u017aniki i dane w dowolnym obszarze.\x3c/div\x3e\x3cbr\x3e\x3cdiv\x3eWybierz na mapie punkt lub poligon, wyszukaj adres lub miejsce, narysuj poligon albo umie\u015b\u0107 na mapie szpilk\u0119, aby wy\u015bwietli\u0107 kluczowe wska\u017aniki i informacje o tym obszarze.\x3c/div\x3e",
defineWhichInfographics:"Zdefiniuj, kt\u00f3re infografiki s\u0105 dost\u0119pne w wid\u017cecie:",defineWhichReports:"Zdefiniuj, kt\u00f3re raporty s\u0105 dost\u0119pne w wid\u017cecie:",defaultValues:"Warto\u015bci domy\u015blne:",disable:"Dezaktywuj",drawFreehandPolygon:"Rysuj dowolny poligon",drawPolygon:"Rysowanie poligonu",driveTime:"Czas przejazdu",dropPin:"Umie\u015b\u0107 szpilk\u0119",dynamicHTML:"Dynamiczny kod HTML",exportOptions:"Opcje eksportu:",home:"Strona g\u0142\u00f3wna",image:"Obraz",
infographics:"Infografiki",invalidValueRing:"Warto\u015bci musz\u0105 nale\u017ce\u0107 do zakresu od 0 do 1 000.",invalidValueDTWT:"Warto\u015bci musz\u0105 nale\u017ce\u0107 do zakresu od 0 do 300.",km:"km",makeDefault:"Ustaw jako domy\u015blne",miles:"mil",minutes:"minut(y)",options:"Opcje:",pdf:"PDF",print:"Drukuj",radius:"Promie\u0144",removeDefault:"Usu\u0144 domy\u015blne",reports:"Raporty",rings:"Pier\u015bcienie",searchTextBox:"Pole tekstowe wyszukiwania",selectCountryOrRegion:"Wybierz kraj lub region:",
thisEntryIsNotValid:"Ten wpis nie jest prawid\u0142owy.",time:"Czas",walkTime:"Czas pokonania trasy pieszej",_localized:{}}});