// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negrita",copy:"Copiar",cut:"Cortar","delete":"Suprimir",indent:"Sangr\u00eda",insertHorizontalRule:"Regla horizontal",insertOrderedList:"Lista numerada",insertUnorderedList:"Lista con vi\u00f1etas",italic:"Cursiva",justifyCenter:"Alinear centro",justifyFull:"Justificar",justifyLeft:"Alinear izquierda",justifyRight:"Alinear derecha",outdent:"Anular sangr\u00eda",paste:"Pegar",redo:"Rehacer",removeFormat:"Eliminar formato",selectAll:"Seleccionar todo",strikethrough:"Tachado",
subscript:"Sub\u00edndice",superscript:"Super\u00edndice",underline:"Subrayado",undo:"Deshacer",unlink:"Eliminar enlace",createLink:"Crear enlace",toggleDir:"Conmutar direcci\u00f3n",insertImage:"Insertar imagen",insertTable:"Insertar/Editar tabla",toggleTableBorder:"Conmutar borde de tabla",deleteTable:"Suprimir tabla",tableProp:"Propiedad de tabla",htmlToggle:"Fuente HTML",foreColor:"Color de primer plano",hiliteColor:"Color de segundo plano",plainFormatBlock:"Estilo de p\u00e1rrafo",formatBlock:"Estilo de p\u00e1rrafo",
fontSize:"Tama\u00f1o de font",fontName:"Nombre de font",tabIndent:"Sangr\u00eda de tabulador",fullScreen:"Conmutar pantalla completa",viewSource:"Ver fuente HTML",print:"Imprimir",newPage:"Nueva p\u00e1gina",systemShortcut:'La acci\u00f3n "${0}" s\u00f3lo est\u00e1 disponible en su navegador mediante un atajo de teclado. Utilice ${1}.',ctrlKey:"control+${0}",appleKey:"\u2318${0}",_localized:{}},"widgets/BusinessAnalyst/nls/strings":{_widgetLabel:"Business Analyst",addPoint:"Agregar un punto haciendo clic en el mapa",
addPolygon:"Crear un pol\u00edgono dibujando en el mapa",addFreehandPolygon:"Crear un pol\u00edgono dibujando a mano alzada en el mapa",addRingsDtWt:"Agregar anillos, tiempo de recorrido por veh\u00edculo o tiempo de recorrido a pie.",apply:"Solicitar participaci\u00f3n",back:"Atr\u00e1s",colon:":",creditInformation:"Informaci\u00f3n de cr\u00e9ditos",customPolygon:"Pol\u00edgono personalizado",driveTime:"Tiempo de recorrido por veh\u00edculo",esriInfographics:"Infograf\u00eda de Esri",esriReports:"Informes de Esri",
headerDescription_km:"kil\u00f3metro",headerDescription_miles:"milla",headerDescription_minutes:"minuto",infographics:"Infograf\u00eda",invalidValueRing:"Los valores deben estar entre el rango de 0 a 1.000.",invalidValueDTWT:"Los valores deben estar entre el rango de 0 a 300.",km:"km",miles:"millas",minutes:"minutos",myInfographics:"Mi infograf\u00eda",myReports:"Mis informes",noPermissions:'Su cuenta no puede ejecutar el widget Business Analyst.  Para poder ejecutar el widget Business Analyst, el administrador de su organizaci\u00f3n debe otorgarle \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3eprivilegios\x3c/a\x3e de GeoEnrichment y An\u00e1lisis de red adem\u00e1s de asignar \x3ca href\x3d"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?" target\x3d"_blank"\x3ecr\u00e9ditos\x3c/a\x3e.',
geServiceNotConfigured:'El widget Business Analyst no se puede ejecutar en este portal porque no tiene configurado el servicio de \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F" target\x3d"_blank"\x3eGeoenriquecimiento\x3c/a\x3e.',dirRoutingServiceNotConfigured:'El widget Business Analyst no se puede ejecutar en este portal porque no tiene configurado el servicio de \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85" target\x3d"_blank"\x3eDirecciones y generaci\u00f3n de rutas\x3c/a\x3e.',
geAndDirRoutingServicesNotConfigured:'El widget Business Analyst no se puede ejecutar en este portal porque no tiene configurados los servicios de \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F" target\x3d"_blank"\x3eGeoenriquecimiento\x3c/a\x3e y \x3ca href\x3d"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85" target\x3d"_blank"\x3eDirecciones y generaci\u00f3n de rutas\x3c/a\x3e.',
radii:"radios",radius:"Radio",radius_lowercase:"radio",reports:"Informes",ring:"Anillo",rings:"Anillos",runInfographic:"Ejecutar infograf\u00eda",runReport:"Ejecutar informe",selectPointOrPolygon:"Seleccione un punto o un pol\u00edgono en el mapa, busque una direcci\u00f3n o un lugar, dibuje un pol\u00edgono o suelte una chincheta en el mapa para visualizar informaci\u00f3n e indicadores clave sobre el \u00e1rea.",selectReport:"Seleccionar informe",selectTemplate:"Seleccionar plantilla",sharedInfographics:"Infograf\u00edas compartidas",
sharedReports:"Informes compartidos",thisEntryIsNotValid:"Esta entrada no es v\u00e1lida.",time:"Time",walkTime:"Tiempo de recorrido a pie",widgetDescription:"Acceda a Infograf\u00edas e Informes que resumen los indicadores clave y datos de cualquier \u00e1rea.",None:"Seleccionar...",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Tama\u00f1o",fontName:"Font",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",monospace:"espacio sencillo",cursive:"cursiva",fantasy:"fantas\u00eda",
noFormat:"Ninguno",p:"P\u00e1rrafo",h1:"Cabecera",h2:"Subcabecera",h3:"Sub-subcabecera",pre:"Preformateado",1:"xx-peque\u00f1o",2:"x-peque\u00f1o",3:"peque\u00f1o",4:"medio",5:"grande",6:"x-grande",7:"xx-grande",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Previsualizaci\u00f3n",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Buscar:",findTooltip:"Especifique el texto que desee buscar",replaceLabel:"Sustituir por:",replaceTooltip:"Especifique el texto por el que se debe sustituir",
findReplace:"Conmutar Buscar/Sustituir",matchCase:"Coincidir may\u00fasculas y min\u00fasculas",matchCaseTooltip:"Coincidir may\u00fasculas y min\u00fasculas",backwards:"Hacia atr\u00e1s",backwardsTooltip:"Buscar texto hacia atr\u00e1s",replaceAllButton:"Sustituir todo",replaceAllButtonTooltip:"Sustituir todo el texto",findButton:"Buscar",findButtonTooltip:"Buscar el texto",replaceButton:"Sustituir",replaceButtonTooltip:"Sustituir el texto",replaceDialogText:"Se han sustituido ${0} apariciones.",
eofDialogText:"\u00daltima aparici\u00f3n ${0}",eofDialogTextFind:"encontrado",eofDialogTextReplace:"sustituido",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Pegar desde Word",instructions:"Pegue el contenido de Word en el siguiente recuadro de texto. Cuando est\u00e9 satisfecho con el contenido que se debe insertar, pulse el bot\u00f3n pegar. Para abortar la inserci\u00f3n de texto, pulse el bot\u00f3n cancelar.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insertar ancla",
title:"Propiedades del ancla",anchor:"Nombre:",text:"Descripci\u00f3n:",set:"Establecer",cancel:"Cancelar",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Cita en bloque",_localized:{}},"widgets/BusinessAnalyst/setting/nls/strings":{businessAnalyst:"Business Analyst",defaultFirstPageText:"\x3cbr\x3e\x3cdiv\x3eAcceda a Infograf\u00edas e Informes que resumen los indicadores clave y datos de cualquier \u00e1rea.\x3c/div\x3e\x3cbr\x3e\x3cdiv\x3eSeleccione un punto o un pol\u00edgono en el mapa, busque una direcci\u00f3n o un lugar, dibuje un pol\u00edgono o suelte una chincheta en el mapa para visualizar informaci\u00f3n e indicadores clave sobre el \u00e1rea.\x3c/div\x3e",
defineWhichInfographics:"Defina qu\u00e9 infograf\u00edas est\u00e1n disponibles en el widget:",defineWhichReports:"Defina qu\u00e9 informes est\u00e1n disponibles en el widget:",defaultValues:"Valores predeterminados:",disable:"Deshabilitar",drawFreehandPolygon:"Dibujar un pol\u00edgono a mano alzada",drawPolygon:"Dibujar pol\u00edgono",driveTime:"Tiempo de recorrido por veh\u00edculo",dropPin:"Colocar marcador",dynamicHTML:"HTML din\u00e1mico",exportOptions:"Opciones de exportaci\u00f3n:",home:"Inicio",
image:"Imagen",infographics:"Infograf\u00eda",invalidValueRing:"Los valores deben estar entre el rango de 0 a 1.000.",invalidValueDTWT:"Los valores deben estar entre el rango de 0 a 300.",km:"km",makeDefault:"Definir como predeterminado",miles:"millas",minutes:"minutos",options:"Opciones:",pdf:"PDF",print:"Imprimir",radius:"Radio",removeDefault:"Eliminar predeterminado",reports:"Informes",rings:"Anillos",searchTextBox:"Cuadro de texto de b\u00fasqueda",selectCountryOrRegion:"Seleccionar pa\u00eds o regi\u00f3n:",
thisEntryIsNotValid:"Esta entrada no es v\u00e1lida.",time:"Time",walkTime:"Tiempo de recorrido a pie",_localized:{}}});