// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["dojo/_base/lang","dojo/_base/array","dojo/_base/Color","dojo/_base/html"],function(n,l,m,k){var d={defaultColor:"#dadada",handlerPosition:{top:null,bottom:null,left:null,right:null},_isNewAddedLayer:function(a,c){c=c.getLayerInfoArrayOfWebmap();for(var b=0,e=c.length;b<e;b++)if(c[b].id===a.id)return!1;return!0},zoomToCurrentLayer:function(a){var c=a.config.isZoom,b=a.layerInfosObj;a=a.getSelection();var e;a&&a[0]&&(e=a[0]);c&&e&&(c=b.getLayerInfoById(e))&&c.zoomTo&&c.zoomTo()},shouldHideInfoWindow:function(a,
c){if(!c.map.infoWindow.isShowing)return!1;var b=c.map.infoWindow.getSelectedFeature();return a&&l.some(a,function(e){var g=b&&b.getLayer&&b.getLayer(),f=c.layerInfosObj.getLayerInfoById(e.id);f=g&&f&&f.traversal(function(h){return h.id===g.id});return g===e||f},c)},getVisibleLayerInfos:function(a,c){a=a.getLayerInfoArray();if(c){for(var b=[],e=0,g=a.length;e<g;e++){var f=a[e];if(f.isShowInMap())b.push(f);else for(var h=0,p=c.length;h<p;h++)c[h]===f.id&&b.push(f)}return b}return l.filter(a,function(q){return q.isShowInMap()})},
isDefaultSelectedLayerAndInShow:function(a,c,b,e){if("mult"===e){if(b&&b.defaultLayers&&b.defaultLayers.length){a=a.value;for(var g=0,f=b.defaultLayers.length;g<f;g++)if(a===b.defaultLayers[g]&&(e=c.getLayerInfoById(a),e.isShowInMap()))return!0}}else if(b&&b.layer&&(a=a.value,a===b.layer&&(e=c.getLayerInfoById(a),e.isShowInMap())))return!0;return!1},isTherePreconfiguredLayer:function(a,c){if(c)return!0;if(a&&a.layerState){a=a.layerState;for(var b in a)if(a.hasOwnProperty(b)&&!0===a[b].selected)return!0}return!1},
processColor:function(a){return a?new m(a):new m(d.defaultColor)},getScreenMiddle:function(a){var c=0,b=0;a&&(a.root?(a=k.getMarginBox(a.root),c=a.w/2,b=a.h/2):a.width&&a.height&&(c=a.width/2,b=a.height/2));return{left:c,top:b}},hideSelectorPopup:function(a){k.addClass(a,"hide")},showSelectorPopup:function(a){k.removeClass(a,"hide")},hackToRefreshSwipe:function(a){setTimeout(n.hitch(a,function(){a.swipeDijit.swipe&&a.swipeDijit.swipe()}),200)},cleanHandlerPosition:function(){d.handlerPosition={top:null,
bottom:null,left:null,right:null}},isCacheHandlerPosition:function(){return d.handlerPosition.top||d.handlerPosition.bottom||d.handlerPosition.left||d.handlerPosition.right?!0:!1},saveHandlerPosition:function(a){a&&(d.handlerPosition.top=a.top,d.handlerPosition.bottom=a.bottom,d.handlerPosition.left=a.left,d.handlerPosition.right=a.right)},setHandlerPosition:function(a,c,b){c.style&&"scope"===c.style?(d.handlerPosition.top&&(a.top=d.handlerPosition.top-9),d.handlerPosition.bottom&&(a.bottom=d.handlerPosition.bottom),
d.handlerPosition.left&&(a.left=d.handlerPosition.left-9),d.handlerPosition.right&&(a.right=d.handlerPosition.right)):c.invertPlacement?(d.handlerPosition.right&&(a.right=d.handlerPosition.right),d.handlerPosition.left&&(a.left=d.handlerPosition.left),d.handlerPosition.bottom&&(a.bottom=d.handlerPosition.bottom),d.handlerPosition.top&&(a.top=d.handlerPosition.top)):(d.handlerPosition.right&&(a.left=d.handlerPosition.right),d.handlerPosition.left&&(a.right=d.handlerPosition.left),d.handlerPosition.bottom&&
(a.top=d.handlerPosition.bottom),d.handlerPosition.top&&(a.bottom=d.handlerPosition.top));0>a.top&&(a.top=0);a.top>b.height&&(a.top=b.height);0>a.left&&(a.left=0);a.left>b.width&&(a.left=b.width)},getLayerNode:function(a){return a._heatmapManager&&a._heatmapManager.imageLayer&&a._heatmapManager.imageLayer._div||a._div},getLayerTransform:function(a,c){var b=a.layer;a={dx:0,dy:0};if(b.getNavigationTransform)a=b.getNavigationTransform();else if(b._getTransform){if(c=b._getTransform())a.dx=c.dx,a.dy=
c.dy}else(b=d.getLayerNode(b).style)&&"css-transforms"===c.map.navigationMode&&(b=c._getTransformValue(b))&&(c=c._parseTransformValue(b),a.dx=c.x,a.dy=c.y);return a}};return d});