// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Rasvane",copy:"Kopeeri",cut:"L\u00f5ika","delete":"Kustuta",indent:"Paremtaane",insertHorizontalRule:"Horisontaaljoon",insertOrderedList:"Nummerdatud loend",insertUnorderedList:"T\u00e4pploend",italic:"Kursiiv",justifyCenter:"Keskjoondus",justifyFull:"R\u00f6\u00f6pjoondus",justifyLeft:"Vasakjoondus",justifyRight:"Paremjoondus",outdent:"Vasaktaane",paste:"Kleebi",redo:"Tee uuesti",removeFormat:"Eemalda vorming",selectAll:"Vali k\u00f5ik",strikethrough:"L\u00e4bikriipsutus",
subscript:"Allindeks",superscript:"\u00dclaindeks",underline:"Allajoonitud",undo:"T\u00fchista",unlink:"Eemalda link",createLink:"Loo link",toggleDir:"Vaheta suund",insertImage:"Sisesta pilt",insertTable:"Lisa/muuda tabelit",toggleTableBorder:"L\u00fclita tabeli\u00e4\u00e4ris sisse/v\u00e4lja",deleteTable:"Kustuta tabel",tableProp:"Tabeli atribuut",htmlToggle:"HTML-l\u00e4htetekst",foreColor:"Esiv\u00e4rv",hiliteColor:"Taustav\u00e4rv",plainFormatBlock:"L\u00f5igu laad",formatBlock:"L\u00f5igu laad",
fontSize:"Fondi suurus",fontName:"Fondi nimi",tabIndent:"Tabeldustaane",fullScreen:"L\u00fclita t\u00e4isekraan sisse/v\u00e4lja",viewSource:"Kuva HTML-l\u00e4htetekst",print:"Prindi",newPage:"Uus leht",systemShortcut:"Seda toimingut ${0} saab Teie brauseris teha ainult kiirklahvi abil. Kasutage klahvikombinatsiooni ${1}.",ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Suurus",fontName:"Font",formatBlock:"Formaat",serif:"seriifidega","sans-serif":"groteskkiri",
monospace:"p\u00fcsisamm",cursive:"kursiiv",fantasy:"fantaasia",noFormat:"Puudub",p:"L\u00f5ik",h1:"Pealkiri",h2:"Alapealkiri",h3:"Ala-alapealkiri",pre:"Eelvormindatud",1:"eriti v\u00e4ike",2:"v\u00e4ga v\u00e4ike",3:"v\u00e4ike",4:"keskmine",5:"suur",6:"v\u00e4ga suur",7:"eriti suur",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",
findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},
"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",
_localized:{}},"widgets/NetworkTrace/setting/nls/strings":{taskUrl:"\u00dclesande URL",setTask:"M\u00e4\u00e4ra",setTaskPopupTitle:"M\u00e4\u00e4ra \u00fclesanne",validate:"M\u00e4\u00e4ra",inValidGPService:"Sisestage kehtiv geot\u00f6\u00f6tlusteenus.",noOutputParameterWithGeometryType:"Valitud geot\u00f6\u00f6tlusteenusel peab olema v\u00e4hemalt \u00fcks v\u00e4ljundparameeter m\u00e4\u00e4ratud geomeetria t\u00fc\u00fcbiga. Valige teistsugune geot\u00f6\u00f6tlusteenus.",invalidOutputGeometry:"Valitud geot\u00f6\u00f6tlusteenuse v\u00e4ljundgeomeetria t\u00fc\u00fcp ei \u00fchildu projekti seadistustega. Geot\u00f6\u00f6tlusteenuse tulemusi ei saa salvestada.",
GPFeatureRecordSetLayerERR:"Palun sisestage geot\u00f6\u00f6tlusteenus, mille sisendid on ainult t\u00fc\u00fcpi GPFeatureRecordSetLayer.",invalidInputParameters:"Sisendparameetrite arv on kas alla 1 v\u00f5i enam kui 3. Sisestage kehtiv geot\u00f6\u00f6tlusteenus.",projectSetting:{title:"Projekti seaded",note:"M\u00e4rkus: projekti seaded on valikulised, kui konfigureeritud kasutaja saab projekti salvestada veebikaardi soovitud kihtides koos v\u00f5rgukatkestuse alaga ja sisendparameetritega. Kasutaja saab salvestada muud v\u00e4ljundparameetrid vahekaardil \u201cV\u00e4ljund\u201d.",
projectPolygonLayer:"Projekti pol\u00fcgoonikiht",outputParameterName:"V\u00e4ljundparameetri nimi",projectPointLayer:"Projekti punktikiht",selectLabel:"Vali",polygonLayerHelp:"\x3cp\x3eKuvatakse pol\u00fcgoonikiht (-kihid) j\u00e4rgmiste tingimustega:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eKihil peavad olema muutmisfunktsioonid, nimelt \u201eLoo\u201c, \u201eKustuta\u201c ja \u201eV\u00e4rskenda\u201c\x3c/li\x3e\x3cli\x3eKihil peab olema 2 v\u00e4lja t\u00e4pse nime- ja andmet\u00fc\u00fcbiga:\x3c/li\x3e\x3cul\x3e\x3cli\x3enimi (stringit\u00fc\u00fcpi v\u00e4li)\x3c/li\x3e\x3cli\x3eglobalid (GlobalID t\u00fc\u00fcpi v\u00e4li)\x3c/li\x3e\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e",
outputParameterHelp:"\x3cp\x3eN\u00e4idatakse v\u00e4ljundpol\u00fcgooni kihti (kihte) \u00fclesande URL-ilt\x3cp/\x3e",pointLayerHelp:"\x3cp\x3eKuvatakse j\u00e4rgmiste tingimustega kiht (-kihid): \x3cbr/\x3e\x3cul\x3e\x3cli\x3eKihil peavad olema muutmisfunktsioonid, nimelt \u201eLoo\u201c, \u201eKustuta\u201c ja \u201eV\u00e4rskenda\u201c\x3c/li\x3e\x3cli\x3eKihil peab olema kaks t\u00e4pse nime- ja andmet\u00fc\u00fcbiga v\u00e4lja:\x3c/li\x3e\x3cul\x3e\x3cli\x3einputtype (stringit\u00fc\u00fcpi v\u00e4li)\x3c/li\x3e\x3cli\x3eprojectid (Guid-t\u00fc\u00fcpi v\u00e4li)\x3c/li\x3e\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e"},
inputOutputTab:{flag:"Lipp",barrier:"T\u00f5ke",skip:"J\u00e4ta vahele",title:"Sisend",inputTooltip:"Kohtspikker",typeText:"T\u00fc\u00fcp",symbol:"S\u00fcmbol",summaryEditorText:"Kokkuv\u00f5tte tekst",summaryTextTitle:"Esitage sisendvahekaardil kuvatav tekst"},summaryTab:{title:"V\u00e4ljund",summaryFieldsetText:"Kokkuv\u00f5tte seaded",inputOutput:"Sisend/v\u00e4ljund",field:"V\u00e4li",operator:"Operaator",inputOperatorCountOption:"Koguarv",outputOperatorCountOption:"Koguarv",outputOperatorSkipCountOption:"Vahelej\u00e4tmiste arv",
fieldOperatorSumOption:"Summa",fieldOperatorMinOption:"Min",fieldOperatorMaxOption:"Max",fieldOperatorMeanOption:"Keskmine",expressionAddButtonText:"Lisa",expressionVerifyButtonText:"Kinnita",summaryEditorText:"Kokkuv\u00f5tte tekst",zoomText:"Automaatne suumimine p\u00e4rast j\u00e4litamist",summarSettingTooltipText:"Lisa sisendi/v\u00e4ljundi arvestus",symbol:"S\u00fcmbol",outputParametersText:"V\u00e4ljundi parameetrid",skipText:"Vahelej\u00e4etav",visibilityText:"N\u00e4htav",exportToCsvText:"Ekspordi CSV formaati",
settitngstext:"S\u00e4tted",saveToLayerText:"Salvesta kihti (valikuline)",inputLabel:"M\u00e4rgis",inputTooltip:"Kohtspikker",outputDisplay:"Kuvamise tekst",addFieldTitle:"Lisa v\u00e4li",setScale:"M\u00e4\u00e4ra m\u00f5\u00f5tkava",enterDisplayText:"Sisestage kuvatekst",saveToLayerHelp:"\x3cp\x3eKuvatakse j\u00e4rgmiste tingimustega kiht:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eKihil peavad olema muutmisfunktsioonid, nimelt \u201eLoo\u201c, \u201eKustuta\u201c ja \u201eV\u00e4rskenda\u201c\x3c/li\x3e\x3cli\x3eKihil peab olema kaks nime- ja andmet\u00fc\u00fcbiga v\u00e4lja:\x3c/li\x3e\x3cul\x3e\x3cli\x3eparametername (stringit\u00fc\u00fcpi v\u00e4li)\x3c/li\x3e\x3cli\x3eprojectid (Guid-t\u00fc\u00fcpi v\u00e4li)\x3c/li\x3e\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e",
exportToCsvDisplayText:"CSV",summaryTextTitle:"Esitage v\u00e4ljundvahekaardil kuvatav kokkuv\u00f5tte tekst",addSummaryItemsTitle:"Lisage kokkuv\u00f5tteobjektid"},validationErrorMessage:{webMapError:"Aluskaardil ei ole kihte. Palun valige kehtiv veebikaart.",inputTypeFlagGreaterThanError:"Lipikut\u00fc\u00fcpi sisendeid ei tohi olla rohkem kui \u00fcks.",inputTypeFlagLessThanError:"N\u00f5utav on v\u00e4hemalt \u00fcks lipikut\u00fc\u00fcpi sisend.",inputTypeBarrierErr:"T\u00f5kket\u00fc\u00fcpi sisendeid ei tohi olla rohkem kui \u00fcks.",
inputTypeSkipErr:"Vahelej\u00e4tmist\u00fc\u00fcpi sisendeid ei tohi olla rohkem kui \u00fcks.",displayTextForButtonError:"Nupu \u201eK\u00e4ivita\u201c kuvatekst ei tohi olla t\u00fchi.",UnableToLoadGeoprocessError:"Ei saanud laadida geot\u00f6\u00f6tlusteenust.",invalidSummaryExpression:"Kehtetu avaldis",validSummaryExpression:"Tehtud!",invalidProjectSettings:"Kehtetud projektiseaded.\x3cbr/\x3e Palun valige kehtiv v\u00e4\u00e4rtus v\u00e4ljal '${projectSetting}'."},hintText:{labelTextHint:"Vihje: sisestage v\u00e4ljundparameetri tulemusplaani kuvatav silt",
displayTextHint:"Vihje: see kuvatakse selle v\u00e4ljundparameetri \u00fcksikasjade paneelil.",inputTextHint:"Vihje: koostage allpool esitatud avaldis, kasutades kokkuv\u00f5tteobjektide nuppu.",expressionHint:"Vihje: avaldise koostamiseks valige \u00fcksused ja kl\u00f5psake nuppu Lisa."},_localized:{}}});