// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fett",copy:"Kopieren",cut:"Ausschneiden","delete":"L\u00f6schen",indent:"Einr\u00fccken",insertHorizontalRule:"Horizontaler Strich",insertOrderedList:"Nummerierung",insertUnorderedList:"Aufz\u00e4hlungszeichen",italic:"Kursiv",justifyCenter:"Zentriert",justifyFull:"Blocksatz",justifyLeft:"Linksb\u00fcndig",justifyRight:"Rechtsb\u00fcndig",outdent:"Ausr\u00fccken",paste:"Einf\u00fcgen",redo:"Wiederholen",removeFormat:"Formatierung entfernen",selectAll:"Alles ausw\u00e4hlen",
strikethrough:"Durchgestrichen",subscript:"Tiefgestellt",superscript:"Hochgestellt",underline:"Unterstrichen",undo:"R\u00fcckg\u00e4ngig",unlink:"Link entfernen",createLink:"Link erstellen",toggleDir:"Richtung wechseln",insertImage:"Grafik einf\u00fcgen",insertTable:"Tabelle einf\u00fcgen/bearbeiten",toggleTableBorder:"Tabellenumrandung ein-/ausschalten",deleteTable:"Tabelle l\u00f6schen",tableProp:"Tabelleneigenschaft",htmlToggle:"HTML-Quelltext",foreColor:"Vordergrundfarbe",hiliteColor:"Hintergrundfarbe",
plainFormatBlock:"Absatzstil",formatBlock:"Absatzstil",fontSize:"Schriftgr\u00f6\u00dfe",fontName:"Schriftartname",tabIndent:"Registerkarteneinr\u00fcckung",fullScreen:"Gesamtanzeige",viewSource:"HTML-Quelle",print:"Drucken",newPage:"Neue Seite",systemShortcut:'Die Aktion "${0}" ist nur \u00fcber einen Direktaufruf in Ihrem Browser verf\u00fcgbar. Verwenden Sie ${1}.',ctrlKey:"Strg+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Gr\u00f6\u00dfe",fontName:"Schriftart",
formatBlock:"Format",serif:"Serife","sans-serif":"Serifenlos",monospace:"Monospaceschrift",cursive:"Kursiv",fantasy:"Fantasie",noFormat:"Keine Angabe",p:"Absatz",h1:"\u00dcberschrift",h2:"Unter\u00fcberschrift",h3:"Unterunter\u00fcberschrift",pre:"Vorformatiert",1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Vorschau",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Suchen:",findTooltip:"Text zum Suchen eingeben",replaceLabel:"Ersetzen durch:",
replaceTooltip:"Text zum Ersetzen eingeben",findReplace:"Suchen und ersetzen",matchCase:"Gro\u00df- und Kleinschreibung abgleichen",matchCaseTooltip:"Gro\u00df- und Kleinschreibung abgleichen",backwards:"Zur\u00fcck",backwardsTooltip:"R\u00fcckw\u00e4rts nach Text suchen",replaceAllButton:"Global ersetzen",replaceAllButtonTooltip:"Gesamten Text ersetzen",findButton:"Suchen",findButtonTooltip:"Text suchen",replaceButton:"Ersetzen",replaceButtonTooltip:"Text ersetzen",replaceDialogText:"${0} Vorkommen ersetzt.",
eofDialogText:"Letztes Vorkommen ${0}",eofDialogTextFind:"gefunden",eofDialogTextReplace:"ersetzt",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Aus Word einf\u00fcgen",instructions:"F\u00fcgt den Inhalt aus Word in das Textfeld unten ein. Wenn Sie mit dem einzuf\u00fcgenden Inhalt zufrieden sind, klicken Sie auf die Schaltfl\u00e4che zum Einf\u00fcgen. Um das Einf\u00fcgen von Text abzubrechen, klicken Sie auf die Schaltfl\u00e4che zum Abbrechen. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker einf\u00fcgen",
title:"Eigenschaften des Ankers",anchor:"Name:",text:"Beschreibung:",set:"Festlegen",cancel:"Abbrechen",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockzitat",_localized:{}},"widgets/NetworkTrace/setting/nls/strings":{taskUrl:"Task-URL",setTask:"Festlegen",setTaskPopupTitle:"Task festlegen",validate:"Festlegen",inValidGPService:"Geben Sie einen g\u00fcltigen Geoverarbeitungsservice an.",noOutputParameterWithGeometryType:"Der ausgew\u00e4hlte Geoverarbeitungsservice muss mindestens einen Ausgabeparameter mit Angabe des Geometrietyps aufweisen. W\u00e4hlen Sie einen anderen Geoverarbeitungsservice aus.",
invalidOutputGeometry:"Der Ausgabegeometrietyp des ausgew\u00e4hlten Geoverarbeitungsservice ist nicht mit den Projekteinstellungen kompatibel. Die Ergebnisse des Geoverarbeitungsservice k\u00f6nnen nicht gespeichert werden.",GPFeatureRecordSetLayerERR:"Geben Sie einen Geoverarbeitungsservice an, der nur Eingaben vom Typ 'GPFeatureRecordSetLayer' enth\u00e4lt.",invalidInputParameters:"Die Anzahl der Eingabeparameter ist kleiner als 1 oder gr\u00f6\u00dfer als 3. Geben Sie einen g\u00fcltigen Geoverarbeitungsservice an.",
projectSetting:{title:"Projekteinstellungen",note:'Hinweis: Projekteinstellungen sind optional. Nach der Konfiguration kann der Benutzer das Projekt in der gew\u00fcnschten Webkarte zusammen mit dem Bereich des Netzwerkausfalls und den Eingabeparametern speichern. Der Benutzer kann andere Ausgabeparameter in der Registerkarte "Ausgabe" speichern.',projectPolygonLayer:"Projekt-Polygon-Layer",outputParameterName:"Name des Ausgabeparameters",projectPointLayer:"Projekt-Punkt-Layer",selectLabel:"Ausw\u00e4hlen",
polygonLayerHelp:'\x3cp\x3ePolygon-Layer mit den folgenden Bedingungen werden angezeigt:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eLayer muss die Bearbeitungsfunktionen "Erstellen", "L\u00f6schen" und "Aktualisieren" aufweisen\x3c/li\x3e\x3cli\x3eLayer muss 2\u00a0Felder mit genau dem folgendem Namen und Datentyp aufweisen:\x3c/li\x3e\x3cul\x3e\x3cli\x3ename (Feld vom Typ "Zeichenfolge")\x3c/li\x3e\x3cli\x3eglobalid (Feld vom Typ "GlobalID")\x3c/li\x3e\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e',outputParameterHelp:"\x3cp\x3eAusgabe-Polygon-Layer aus der Task-URL werden angezeigt\x3cp/\x3e",
pointLayerHelp:'\x3cp\x3ePunkt-Layer mit den folgenden Bedingungen werden angezeigt: \x3cbr/\x3e\x3cul\x3e\x3cli\x3eLayer muss die Bearbeitungsfunktionen "Erstellen", "L\u00f6schen" und "Aktualisieren" aufweisen\x3c/li\x3e\x3cli\x3e\x3c/li\x3eLayer muss 2\u00a0Felder mit genau dem folgendem Namen und Datentyp aufweisen:\x3cul\x3e\x3cli\x3e\x3c/li\x3einputtype (Feld vom Typ "Zeichenfolge")\x3cli\x3e\x3c/li\x3eprojectid (Feld vom Typ "GUID")\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e'},inputOutputTab:{flag:"Flagge",
barrier:"Barriere",skip:"\u00dcberspringen",title:"Eingabe",inputTooltip:"Quickinfo",typeText:"Typ",symbol:"Symbol",summaryEditorText:"Text der Zusammenfassung",summaryTextTitle:'Text f\u00fcr die Anzeige auf der Registerkarte "Eingabe" angeben'},summaryTab:{title:"Ausgabe",summaryFieldsetText:"Einstellungen f\u00fcr Zusammenfassung",inputOutput:"Eingabe/Ausgabe",field:"Feld",operator:"Operator",inputOperatorCountOption:"Anzahl",outputOperatorCountOption:"Anzahl",outputOperatorSkipCountOption:"Anzahl \u00fcberspringen",
fieldOperatorSumOption:"Summe",fieldOperatorMinOption:"Min.",fieldOperatorMaxOption:"Max.",fieldOperatorMeanOption:"Mittelwert",expressionAddButtonText:"Hinzuf\u00fcgen",expressionVerifyButtonText:"\u00dcberpr\u00fcfen",summaryEditorText:"Text der Zusammenfassung",zoomText:"Nach der Verfolgung automatisch zoomen",summarSettingTooltipText:"Eingabe-/Ausgabeanzahl hinzuf\u00fcgen",symbol:"Symbol",outputParametersText:"Ausgabeparameter",skipText:"\u00dcberspringbar",visibilityText:"Sichtbar",exportToCsvText:"In CSV exportieren",
settitngstext:"Einstellungen",saveToLayerText:"In Layer speichern (optional)",inputLabel:"Beschriftung",inputTooltip:"Quickinfo",outputDisplay:"Anzeigetext",addFieldTitle:"Feld hinzuf\u00fcgen",setScale:"Ma\u00dfstab festlegen",enterDisplayText:"Anzeigetext eingeben",saveToLayerHelp:'\x3cp\x3eLayer mit den folgenden Bedingungen werden angezeigt:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eLayer muss die Bearbeitungsfunktionen "Erstellen", "L\u00f6schen" und "Aktualisieren" aufweisen\x3c/li\x3e\x3cli\x3eLayer muss zwei Felder mit folgendem Namens- und Datentyp aufweisen:\x3c/li\x3e\x3cul\x3e\x3cli\x3eparametername (Feld vom Typ "Zeichenfolge")\x3c/li\x3e\x3cli\x3eprojectid (Feld vom Typ "GUID")\x3c/li\x3e\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e',
exportToCsvDisplayText:"CSV",summaryTextTitle:'Text der Zusammenfassung f\u00fcr die Anzeige auf der Registerkarte "Ausgabe" angeben',addSummaryItemsTitle:"Zusammenfassungselemente hinzuf\u00fcgen"},validationErrorMessage:{webMapError:"Keine Layer in der Webkarte verf\u00fcgbar. W\u00e4hlen Sie eine g\u00fcltige Webkarte aus.",inputTypeFlagGreaterThanError:'Eingabe vom Typ "Flag" darf nur einmal vorhanden sein.',inputTypeFlagLessThanError:'Es ist mindestens eine Eingabe vom Typ "Flag" erforderlich.',
inputTypeBarrierErr:'Eingabe vom Typ "Barriere" darf nur einmal vorhanden sein.',inputTypeSkipErr:'Eingabe vom Typ "\u00dcberspringen" darf nur einmal vorhanden sein.',displayTextForButtonError:"Der Anzeigetext f\u00fcr die Schaltfl\u00e4che 'Ausf\u00fchren' darf nicht leer sein.",UnableToLoadGeoprocessError:"Geoverarbeitungsservice kann nicht geladen werden.",invalidSummaryExpression:"Ung\u00fcltiger Ausdruck.",validSummaryExpression:"Erfolgreich abgeschlossen.",invalidProjectSettings:"Ung\u00fcltige Projekteinstellungen.\x3cbr/\x3eW\u00e4hlen Sie in '${projectSetting}' einen g\u00fcltigen Wert aus."},
hintText:{labelTextHint:"Hinweis: Geben Sie eine Anzeigebeschriftung f\u00fcr den Ergebnisbereich des Ausgabeparameters an.",displayTextHint:'Hinweis: Dies wird im Bereich "Details" des Ausgabeparameters angezeigt.',inputTextHint:'Hinweis: Erstellen Sie unten den Ausdruck unter Verwendung der Schaltfl\u00e4che "Zusammenfassungselemente hinzuf\u00fcgen".',expressionHint:'Hinweis: W\u00e4hlen Sie Elemente aus, und klicken Sie auf "Hinzuf\u00fcgen", um einen Ausdruck zu erstellen.'},_localized:{}}});