// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fed",copy:"Kopi\u00e9r",cut:"Klip","delete":"Slet",indent:"Indrykning",insertHorizontalRule:"Vandret linje",insertOrderedList:"Nummereret liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Centreret",justifyFull:"Lige margener",justifyLeft:"Venstrejusteret",justifyRight:"H\u00f8jrejusteret",outdent:"Udrykning",paste:"S\u00e6t ind",redo:"Annull\u00e9r Fortryd",removeFormat:"Fjern format",selectAll:"Mark\u00e9r alle",strikethrough:"Gennemstreget",
subscript:"S\u00e6nket skrift",superscript:"H\u00e6vet skrift",underline:"Understreget",undo:"Fortryd",unlink:"Fjern link",createLink:"Opret link",toggleDir:"Skift retning",insertImage:"Inds\u00e6t billede",insertTable:"Inds\u00e6t/redig\u00e9r tabel",toggleTableBorder:"Skift tabelramme",deleteTable:"Slet tabel",tableProp:"Tabelegenskab",htmlToggle:"HTML-kilde",foreColor:"Forgrundsfarve",hiliteColor:"Baggrundsfarve",plainFormatBlock:"Afsnitstypografi",formatBlock:"Afsnitstypografi",fontSize:"Skriftst\u00f8rrelse",
fontName:"Skriftnavn",tabIndent:"Tabulatorindrykning",fullScreen:"Fuld sk\u00e6rm til/fra",viewSource:"Vis HTML-kilde",print:"Udskriv",newPage:"Ny side",systemShortcut:'Funktionen "${0}" kan kun bruges i din browser med en tastaturgenvej. Brug ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"St\u00f8rrelse",fontName:"Skrifttype",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"kursiv",fantasy:"fantasy",
noFormat:"Ingen",p:"Afsnit",h1:"Overskrift",h2:"Underoverskrift",h3:"Underunderoverskrift",pre:"Forudformateret",1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Eksempel",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f8g:",findTooltip:"Indtast tekst, du vil s\u00f8ge efter",replaceLabel:"Erstat med:",replaceTooltip:"Indtast tekst, du vil erstatte med",findReplace:"S\u00f8g og erstat",
matchCase:"Forskel p\u00e5 store og sm\u00e5 bogstaver",matchCaseTooltip:"Forskel p\u00e5 store og sm\u00e5 bogstaver",backwards:"Bagl\u00e6ns",backwardsTooltip:"S\u00f8g bagl\u00e6ns i teksten",replaceAllButton:"Erstat alle",replaceAllButtonTooltip:"Erstat i hele teksten",findButton:"S\u00f8g",findButtonTooltip:"Find teksten",replaceButton:"Erstat",replaceButtonTooltip:"Erstat teksten",replaceDialogText:"${0} forekomster erstattet.",eofDialogText:"Sidste forekomst ${0}",eofDialogTextFind:"fundet",
eofDialogTextReplace:"erstattet",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Inds\u00e6t fra Word",instructions:"Inds\u00e6t indholdet fra Word i tekstfeltet nedenfor. Klik p\u00e5 knappen Inds\u00e6t, n\u00e5r du er tilfreds med indholdet. Tryk p\u00e5 knappen Annull\u00e9r for at fortryde inds\u00e6ttelsen.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inds\u00e6t anker",title:"Egenskaber for anker",anchor:"Navn:",text:"Beskrivelse:",set:"Defin\u00e9r",
cancel:"Annull\u00e9r",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokanf\u00f8rselstegn",_localized:{}},"widgets/NetworkTrace/setting/nls/strings":{taskUrl:"Opgave-URL",setTask:"Indstil",setTaskPopupTitle:"Indstil opgave",validate:"Indstil",inValidGPService:"Angiv en gyldig geoprocesseringstjeneste.",noOutputParameterWithGeometryType:"Den valgte geoprocesseringstjeneste skal have mindst en output-parameter med en specificeret geometritype. V\u00e6lg en anden geoprocesseringstjeneste.",
invalidOutputGeometry:"Output-geometritypen p\u00e5 den valgte geoprocesseringstjeneste er ikke kompatible med projekt-indstillingerne. Resultaterne fra geoprocesseringstjenesten kan ikke gemmes.",GPFeatureRecordSetLayerERR:"Angiv en geoprocesseringstjeneste udelukkende med input af typen 'GPFeatureRecordSetLayer'.",invalidInputParameters:"Antallet af inputparametre er enten mindre end 1 eller mere end 3. Angiv en gyldig geoprocesseringstjeneste.",projectSetting:{title:"Projektindstillinger",note:"Bem\u00e6rk: Projektindstillingerne er valgfrie, n\u00e5r den konfigurerede bruger kan lagre projektet i de \u00f8nskede webkortlag med omr\u00e5de for netv\u00e6rksnedbrud og inputparametre. Brugeren kan lagre andre outputparametre fra fanen 'Output'.",
projectPolygonLayer:"Projektpolygonlag",outputParameterName:"Navn p\u00e5 outputparameter",projectPointLayer:"Projektpunktlag",selectLabel:"V\u00e6lg",polygonLayerHelp:"\x3cp\x3ePolygonlag med f\u00f8lgende betingelser vil blive vist:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eLaget skal have redigeringsfunktioner, nemlig 'Opret', 'Slet' og 'Opdat\u00e9r\u201d'\x3c/li\x3e\x3cli\x3eLaget skal have to felter med pr\u00e6cist navn og datatype:\x3c/li\x3e\x3cul\x3e\x3cli\x3eNavn (Strengtypefelt)\x3c/li\x3e\x3cli\x3eGlobalID (GlobalID-typefelt)\x3c/li\x3e\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e",
outputParameterHelp:"\x3cp\x3eOutputpolygonlag fra opgave-URL vil blive vist\x3cp/\x3e",pointLayerHelp:"\x3cp\x3ePunktlag med f\u00f8lgende betingelser vil blive vist: \x3cbr/\x3e\x3cul\x3e\x3cli\x3eLaget skal have redigeringsfunktioner, nemlig 'Opret', 'Slet' og 'Opdat\u00e9r'\x3c/li\x3e\x3cli\x3eLaget skal have to felter med pr\u00e6cist navn og datatype:\x3c/li\x3e\x3cul\x3e\x3cli\x3eInputtype (Strengtypefelt)\x3c/li\x3e\x3cli\x3eProjectid (GUID-typefelt)\x3c/li\x3e\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e"},
inputOutputTab:{flag:"Flag",barrier:"Barriere",skip:"Spring over",title:"Input",inputTooltip:"V\u00e6rkt\u00f8jstip",typeText:"Type",symbol:"Symbol",summaryEditorText:"Resum\u00e9-tekst",summaryTextTitle:"Angiv tekst, der skal vises p\u00e5 input-fanen"},summaryTab:{title:"Output",summaryFieldsetText:"Resum\u00e9-indstillinger",inputOutput:"Input/Output",field:"Felt",operator:"Operator",inputOperatorCountOption:"T\u00e6lling",outputOperatorCountOption:"T\u00e6lling",outputOperatorSkipCountOption:"SkipCount",
fieldOperatorSumOption:"Sum",fieldOperatorMinOption:"Min.",fieldOperatorMaxOption:"Maks.",fieldOperatorMeanOption:"Middel",expressionAddButtonText:"Tilf\u00f8j",expressionVerifyButtonText:"Bekr\u00e6ft",summaryEditorText:"Resum\u00e9-tekst",zoomText:"Auto-zoom efter sporing",summarSettingTooltipText:"Tilf\u00f8j input/output-antal",symbol:"Symbol",outputParametersText:"Outputparametre",skipText:"Kan udelades",visibilityText:"Synlig",exportToCsvText:"Export to CSV",settitngstext:"Indstillinger",saveToLayerText:"Gem til lag (valgfrit)",
inputLabel:"M\u00e6rke",inputTooltip:"V\u00e6rkt\u00f8jstip",outputDisplay:"Vis tekst",addFieldTitle:"Tilf\u00f8j felt",setScale:"Indstil skala",enterDisplayText:"Indtast visningstekst",saveToLayerHelp:"\x3cp\x3eLag med f\u00f8lgende betingelser vil blive vist:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eLaget skal have redigeringsfunktioner, nemlig 'Opret', 'Slet' og 'Opdat\u00e9r'\x3c/li\x3e\x3cli\x3eLaget skal have to felter med navn og datatype:\x3c/li\x3e\x3cul\x3e\x3cli\x3eParametername (Strengtypefelt)\x3c/li\x3e\x3cli\x3eProjectid (GUID-typefelt)\x3c/li\x3e\x3c/ul\x3e\x3c/ul\x3e\x3cp/\x3e",
exportToCsvDisplayText:"CSV",summaryTextTitle:"Angiv tekst, der skal vises p\u00e5 output-fanen",addSummaryItemsTitle:"Tilf\u00f8j resum\u00e9-poster"},validationErrorMessage:{webMapError:"Der er ingen tilg\u00e6ngelige lag i webkortet. V\u00e6lg et gyldigt webkort.",inputTypeFlagGreaterThanError:"Der kan ikke v\u00e6re mere end \u00e9t input for typeflag.",inputTypeFlagLessThanError:"Der kr\u00e6ves mindst \u00e9t input for typeflag.",inputTypeBarrierErr:"Der kan ikke v\u00e6re mere end \u00e9t input for typegr\u00e6nse.",
inputTypeSkipErr:"Der kan ikke v\u00e6re mere end \u00e9t input for typeudeladelse.",displayTextForButtonError:"Visningstekst til knappen 'K\u00f8r' m\u00e5 ikke v\u00e6re tom.",UnableToLoadGeoprocessError:"Kan ikke indl\u00e6se geoprocesseringstjeneste.",invalidSummaryExpression:"Ugyldigt udtryk.",validSummaryExpression:"F\u00e6rdig!",invalidProjectSettings:"Ugyldige projektindstillinger.\x3cbr/\x3e Angiv en gyldig v\u00e6rdi i '${projectSetting}'."},hintText:{labelTextHint:"Tip: Angiv visningsetiket for outputparameterens resultatpanel.",
displayTextHint:"Tip: Dette vil blive vist i oplysningspanelet for denne outputparameter.",inputTextHint:"Tip: Opret dit udtryk nedenfor ved hj\u00e6lp af knappen Tilf\u00f8j resum\u00e9-elementer.",expressionHint:"Tip: V\u00e6lg elementer, og klik p\u00e5 Tilf\u00f8j for at oprette udtrykket."},_localized:{}}});