// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start}\u2013${end}/${total} tulemust",gotoFirst:"Liigu esimesele lehele",gotoNext:"Liigu j\u00e4rgmisele lehele",gotoPrev:"Liigu eelmisele lehele",gotoLast:"Liigu viimasele lehele",gotoPage:"Liigu lehele",jumpPage:"H\u00fcppa lehele",rowsPerPage:"Number of rows per page",_localized:{}},"esri/layers/vectorTiles/nls/common":{_localized:{}},"esri/dijit/analysis/nls/DataStoreSelect":{relationalDS:"Relatsiooniline",spatialDS:"Ajalisruumiline",agsDataStore:"ArcGIS-i andmeladu",
bdfsTemplates:"Suurandmete failijaotuse v\u00e4ljundmallid",_localized:{}},"esri/dijit/analysis/nls/BrowseLayerMixin":{defaultAnaysisLayerTitle:"Valige Living Atlas anal\u00fc\u00fcsikiht",customAnalysisLayerTitle:"Vali anal\u00fc\u00fcsikiht",searchPlaceholderText:"Otsi Living Atlas anal\u00fc\u00fcsikihte",searchCustomPlaceholderText:"Otsi anal\u00fc\u00fcsikihte",mainActionTitle:"Vali",customActionName:"Vali ja lisa kaardile",customeSectionName:"Living Atlase anal\u00fc\u00fcsikihid",Categories:"Kategooriad",
boundaries:"Piirid",places:"Kohad",boundariesAndPlaces:"Piirid ja kohad",hexbins:"Kuusnurksalved",transportation:"Transport",point:"Punktikihid",line:"Murdjoonekihid",polygon:"Pol\u00fcgoonkihid",pointFilterName:"Punkt",lineFilterName:"Joon",polygonFilterName:"Pol\u00fcgoon",multiPointFilterName:"Mitmekordsed punktid",geometryFilterName:"Geomeetria",featureLayerName:"Objektikiht",tableLayerName:"Tabel",itemTypeFilterName:"\u00dcksuse t\u00fc\u00fcp",instantFilterName:"Jooksev",intervalFilterName:"Intervall",
timeFilterName:"Aeg",edit:"Muuda",boundaryLayers:"Esri piiride kihid",customAnalysisGroupName:"Organisatsiooni anal\u00fc\u00fcsigrupp",_localized:{}},"widgets/Visibility/nls/strings":{_widgetLabel:"N\u00e4htavus",observerLocation:"Vaatleja asukoht",formatIconTooltip:"Vormingu sisestus",addPointToolTip:"Lisa vaatleja asukoht",fieldOfView:"Vaatev\u00e4li",useMilsText:"Kasuta nurkade jaoks milliradiaane (1 mils \x3d 0.001 tolli)",observerHeight:"Vaatleja k\u00f5rgus",minObsDistance:"V\u00e4him vaadeldav kaugus",
maxObsDistance:"Suurim vaadeldav kaugus",taskURLError:"Vidina konfiguratsioonifail sisaldab URL-i, millele ei p\u00e4\u00e4se juurde. K\u00fcsige n\u00f5u s\u00fcsteemiadministraatorilt.",taskURLInvalid:"Selle vidina kaudu konfigureeritud geot\u00f6\u00f6tlustoiming ei sobi. K\u00fcsige n\u00f5u s\u00fcsteemiadministraatorilt.",viewshedError:"N\u00e4htavuse loomisel ilmnes t\u00f5rge. Veenduge, et vaatleja asukoht j\u00e4\u00e4b teie k\u00f5rguspinna ulatusse.\x3c/p\x3e",validationError:"\x3cp\x3eN\u00e4htavuse loomise vormil on parameetreid puudu v\u00f5i m\u00f5ni parameeter ei sobi. Veenduge, et:\x3c/p\x3e\x3cul\x3e\x3cli\x3evaatleja asukoht oleks m\u00e4\u00e4ratud;\x3c/li\x3e\x3cli\x3evaatleja vaatev\u00e4lja v\u00e4\u00e4rtus poleks 0;\x3c/li\x3e\x3cli\x3evaatleja k\u00f5rguse v\u00e4\u00e4rtus oleks sobiv;\x3c/li\x3e\x3cli\x3ev\u00e4hima ja suurima vaadeldava kauguse v\u00e4\u00e4rtused oleksid sobivad.\x3c/li\x3e\x3c/ul\x3e",
comfirmInputNotation:"Kinnita sisestatud t\u00e4histus",notationsMatch:"t\u00e4histust vastab Teie sisestusele; palun kinnitage, millist soovite kasutada:",createBtn:"Loo",clearBtn:"T\u00fchjenda",setCoordFormat:"M\u00e4\u00e4ra koordinaatide vormingu string",prefixNumbers:"Lisa positiivsetele ja negatiivsetele arvudele eesliide \u201e+/-\u201d",parseCoordinatesError:"Ei saa koordinaate s\u00f5eluda. Kontrollige sisendit.",cancelBtn:"Loobu",applyBtn:"Rakenda",invalidMessage:"Sisestage numbriline v\u00e4\u00e4rtus.",
observerRangeMessage:"Vaatleja k\u00f5rgus ei sobi",minimumRangeMessage:"Minimaalne vaadeldav vahemik ei sobi",maximumRangeMessage:"Maksimaalne vaadeldav vahemik peab olema suurem kui minimaalne vaadeldav vahemik ja ei tohi \u00fcletada ${limit} ${units}.",portalURLError:"ArcGIS Online'i organisatsiooni veebilehe v\u00f5i Portal for ArcGIS-i URL ei ole konfigureeritud. K\u00fcsige n\u00f5u s\u00fcsteemiadministraatorilt",privilegeError:'Teie kasutajaroll ei luba teha anal\u00fc\u00fcsi. Anal\u00fc\u00fcsi tegemiseks peab teie organisatsiooni administraator andma teile teatud \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3e\u00f5igused\x3c/a\x3e.',
noServiceError:"K\u00f5rgusanal\u00fc\u00fcsi teenus pole saadaval. Kontrollige ArcGIS Online'i organisatsiooni veebilehe v\u00f5i Portal for ArcGIS-i konfiguratsioone.",pointToolTooltip:"Kl\u00f5psake vaatleja asukoha lisamiseks",degreesLabel:"kraadi",milsLabel:"miili",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"K\u00fcmnendkraadid \u2013 laiuskraad/pikkuskraad",DDLongLatNotation:"K\u00fcmnendkraadid  \u2013 pikkuskraad/laiuskraad",
DDMLatLongNotation:"Kraadid-k\u00fcmnendminutid \u2013 laiuskraad/pikkuskraad",DDMLongLatNotation:"Kraadid-k\u00fcmnendminutid \u2013 pikkuskraad/laiuskraad",DMSLatLongNotation:"Kraadid-k\u00fcmnendsekundid \u2013 laiuskraad/pikkuskraad",DMSLongLatNotation:"Kraadid-k\u00fcmnendsekundid \u2013 pikkuskraad/laiuskraad",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM \u2013 vahemiku t\u00e4ht",UTMHemNotation:"UTM \u2013 poolkera (N/S)",mainPageTitle:"Radiaalne vaatev\u00e4li",
resultsTitle:"Tulemused",publishBtnLabel:"Publitseeri",layerName:"Publitseeritud kihi nimi",invalidLayerName:"Kihi nimi tohib sisaldada ainult t\u00e4he- ja numbrim\u00e4rke ning allkriipse",back:"Tagasi",publishingFailedLayerExists:"Publitseerimine nurjus: objektiteenus nimega {0} on juba olemas. Valige m\u00f5ni muu nimi.",checkService:"Kontrolli teenust: {0}",createService:"Loo teenus: {0}",unableToCreate:"Ei saa luua: {0}",addToDefinition:"Lisa definitsiooni: {0}",successfullyPublished:"Edukalt publitseeritud veebikiht{0}Halda veebikihti",
userRole:"Teenust ei saa luua, kuna kasutajal pole \u00f5igusi",publishToNewLayer:"Publitseeri tulemused uue objektikihina",missingLayerNameMessage:"Publitseerimiseks peate esmalt sisestama sobiva kihi nime",layerNameExists:"Kihi nimi on juba olemas. Valige kihile m\u00f5ni muu nimi.",regionTypeLabel:"Piirkonna t\u00fc\u00fcp",centerPointLabel:"Keskpunkt",observationHeightLabel:"Vaatlusk\u00f5rgus",heightUnitLabel:"K\u00f5rguse \u00fchik",minObservationDistanceLabel:"Minimaalne vaatluskaugus",maxObservationDistance:"Maksimaalne vaatluskaugus",
distanceUnitLabel:"Vahemaa \u00fchik",fovstartAngleLabel:"Vaatev\u00e4lja algusnurk",fovEndAngleLabel:"Vaatev\u00e4lja l\u00f5punurk",andleUnitsLabel:"Nurga \u00fchikud",visibleSectionLabel:"N\u00e4htav sektsioon",nonVisibleSectionLabel:"N\u00e4htamatu sektsioon",visibleSectionButtonLabel:"Konfigureeri n\u00e4htava sektsiooni s\u00e4tted",nonVisibleSectionButtonLabel:"Konfigureeri n\u00e4htamatu sektsiooni s\u00e4tted",transparency:"L\u00e4bipaistvus",outline:"\u00c4\u00e4rejoon",fill:"T\u00e4ida (v\u00e4rv rakendatakse ainult juhul, kui valitud on pidev laad)",
style:"Stiil",colorPicker:"V\u00e4rvivalija",lineStyles:{esriSLSDash:"Katkendlik",esriSLSDashDot:"Katkendlik punktiga",esriSLSDashDotDot:"Katkendlik kahe punktiga",esriSLSDot:"Punkt",esriSLSLongDash:"Pikk katkendlik kriips",esriSLSLongDashDot:"Pikk katkendlik kriips punktiga",esriSLSNull:"Null",esriSLSShortDash:"L\u00fchike katkendlik kriips",esriSLSShortDashDot:"L\u00fchike katkendlik kriips punktiga",esriSLSShortDashDotDot:"L\u00fchike katkendlik kriips kahe punktiga",esriSLSShortDot:"L\u00fchike punktiir",
esriSLSSolid:"Pidev"},fillStyles:{esriSFSBackwardDiagonal:"Tagasi",esriSFSCross:"Rist",esriSFSDiagonalCross:"Diagonaal",esriSFSForwardDiagonal:"Edasi",esriSFSHorizontal:"Horisontaalne",esriSFSNull:"Null",esriSFSSolid:"Pidev",esriSFSVertical:"Vertikaalne"},settingsTitle:"Seaded",_localized:{}}});