// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/nls/strings":{_widgetLabel:"Uhka-analyysi",threatAnalysisMainPageTitle:"Perustuu JCAT Counterterrorism Guide -oppaaseen",jcatURL:"https://www.dni.gov/nctc/jcat/references.html",inputLocation:"L\u00e4ht\u00f6sijainti",interactive:"Vuorovaikutteinen",fromCoord:"Kiinte\u00e4 koordinaatti",existingFeature:"Aiemmin m\u00e4\u00e4ritetyist\u00e4 kohteista",threatAnalysisCoordInputLabel:"Uhkan sijainti",enterCoords:"Kirjoita koordinaatit",threatAddPointToolTip:"Lis\u00e4\u00e4 uhkan sijainti",
threatDrawPointToolTip:"Lis\u00e4\u00e4 uhkan sijainti napsauttamalla",threatType:"Uhkan laji",threatPlaceholder:"Etsi uhkaa aloittamalla sen nimen kirjoitus",mandatoryLabel:"Pakollinen evakuointiet\u00e4isyys",safeLabel:"Turvallinen evakuointiet\u00e4isyys",zoneTypeLabel:"Vy\u00f6hykkeen tyyppi",feetLabel:"Jalkaa",metersLabel:"Metri\u00e4",unitsLabel:"Yksik\u00f6t",threatGraphicLayer:"Uhka-alueen grafiikka",settingsTitle:"Asetukset",mandatoryButtonLabel:"M\u00e4\u00e4rit\u00e4 pakollisen evakuointiet\u00e4isyyden asetukset",
safeButtonLabel:"M\u00e4\u00e4rit\u00e4 suojavy\u00f6hykkeen asetukset",style:"Tyyli",colorPicker:"v\u00e4rivalitsin",lineStyles:{esriSLSDash:"Viiva",esriSLSDashDot:"Viiva-piste",esriSLSDashDotDot:"Viiva-piste-piste",esriSLSDot:"Piste",esriSLSLongDash:"Pitk\u00e4 viiva",esriSLSLongDashDot:"Pitk\u00e4 viiva-piste",esriSLSNull:"Null",esriSLSShortDash:"Lyhyt viiva",esriSLSShortDashDot:"Lyhyt viiva-piste",esriSLSShortDashDotDot:"Lyhyt viiva-piste-piste",esriSLSShortDot:"Lyhyt piste",esriSLSSolid:"Yhten\u00e4inen"},
fillStyles:{esriSFSBackwardDiagonal:"Taaksep\u00e4in",esriSFSCross:"Risti",esriSFSDiagonalCross:"L\u00e4vist\u00e4j\u00e4n suunnassa",esriSFSForwardDiagonal:"Eteenp\u00e4in",esriSFSHorizontal:"Vaaka",esriSFSNull:"Null",esriSFSSolid:"Yhten\u00e4inen",esriSFSVertical:"Pysty"},resultsTitle:"Tulokset",publishTABtn:"Julkaise",layerName:"Julkaistun karttatason nimi",invalidLayerName:"Karttatason nimi voi sis\u00e4lt\u00e4\u00e4 vain aakkosnumeerisia merkkej\u00e4 ja alaviivoja",missingLayerNameMessage:"Kelvollinen karttatason nimi on annettava ennen julkaisua",
publishingFailedLayerExists:"Julkaisu ep\u00e4onnistui: Sinulla on jo kohdepalvelu nimelt\u00e4 {0}. Valitse toinen karttatason nimi.",checkService:"Tarkista palvelu: {0}",createService:"Luo palvelu: {0}",unableToCreate:"Kohteen {0} tuonti ei onnistu",addToDefinition:"Lis\u00e4\u00e4 m\u00e4\u00e4ritykseen: {0}",successfullyPublished:"Web-karttatason julkaisu onnistui",successfullyAppended:"Uudet kohteet on lis\u00e4tty web-karttatasoon",manageWebLayerText:"Hallitse web-karttatasoa",userRole:"Palvelun luonti ei onnistu, koska k\u00e4ytt\u00e4j\u00e4ll\u00e4 ei ole k\u00e4ytt\u00f6oikeuksia",
retrieveExistingLayerError:"Kohdetta {0} ei voi noutaa. Julkaisen k\u00e4ytt\u00e4m\u00e4ll\u00e4 toista karttatason nime\u00e4",publishToNewLayer:"Julkaise tulokset uuteen kohdekarttatasoon",layerNameExists:"Karttatason nimi on jo k\u00e4yt\u00f6ss\u00e4. K\u00e4yt\u00e4 toista karttatason nime\u00e4.",pipeBombLabel:"Putkipommi",suicideBombLabel:"Itsemurhapommi",briefcaseLabel:"Salkku",carLabel:"Auto",suvVanLabel:"Kaupunkimaasturi/pakettiauto",smallDeliveryTruckLabel:"Pieni jakeluauto",containerWaterTruckLabel:"S\u00e4ili\u00f6-/vesis\u00e4ili\u00f6auto",
semiTrailerLabel:"Puoliper\u00e4vaunu",transparencyLabel:"L\u00e4pin\u00e4kyvyys",outline:"\u00c4\u00e4riviiva",fill:"T\u00e4ytt\u00f6 (v\u00e4ri\u00e4 k\u00e4ytet\u00e4\u00e4n vain, kun tyyliksi on m\u00e4\u00e4ritetty yhten\u00e4inen)",createBtn:"Luo alueet",clearBtn:"Tyhjenn\u00e4",invalidNumberMessage:"Annettu arvo ei kelpaa",invalidRangeMessage:"Arvon on oltava suurempi kuin 0",parseCoordinatesError:"Koordinaatteja ei voida j\u00e4sent\u00e4\u00e4. Tarkista sy\u00f6tteesi.",selectDrawModeLabel:"Valitse piirustustila",
selectFeatureLabel:"Valitse kohde t\u00e4st\u00e4 karttatasosta",fireBallDiameterLable:"Tulipallon l\u00e4pimitta",lpgSafeDistanceLable:"Turvaet\u00e4isyys",threatTypeCatagoryLabel:"Uhkatyypin luokka",fireballButtonLabel:"M\u00e4\u00e4rit\u00e4 tulipallon l\u00e4pimitan asetukset",safeDistanceButtonLabel:"M\u00e4\u00e4rit\u00e4 turvaet\u00e4isyyden asetukset",chemicalThreatCatagoryLabel:"Kemikaali",lpgThreatCatagoryLabel:"Nestekaasu",chemicalThreatLabel:"Kemiallinen uhka",lpgThreatLabel:"Nestekaasun aiheuttama uhka",
fireBallDiameterFieldAlias:"Nestekaasun aiheuttaman tulipallon l\u00e4pimitta",lpgSafeDistanceFieldAlias:"Turvaet\u00e4isyys nestekaasun tapauksessa",smallLPGTank:"Pieni nestekaasus\u00e4ili\u00f6",largeLPGTank:"Suuri nestekaasus\u00e4ili\u00f6",commercialResidentialLPGTank:"Kaupallinen tai kotitalousk\u00e4ytt\u00f6\u00f6n tarkoitettu nestekaasus\u00e4ili\u00f6",smallLPGTruck:"Pieni nestekaasus\u00e4ili\u00f6auto",semiTankerLPG:"Keskikokoinen nestekaasus\u00e4ili\u00f6auto",_localized:{}}});