// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/nls/strings":{_widgetLabel:"Trusselanalyse",threatAnalysisMainPageTitle:"Basert p\u00e5 JCATs veiledning om kontraterrorisme",jcatURL:"https://www.dni.gov/nctc/jcat/references.html",inputLocation:"Angi lokasjon",interactive:"Interaktiv",fromCoord:"Fast koordinat",existingFeature:"Fra eksisterende geoobjekter",threatAnalysisCoordInputLabel:"Trussellokasjon",enterCoords:"Angi koordinater",threatAddPointToolTip:"Legg til trussellokasjon",threatDrawPointToolTip:"Klikk for \u00e5 legge til trussellokasjon",
threatType:"Trusseltype",threatPlaceholder:"Skriv inn for \u00e5 s\u00f8ke etter trussel",mandatoryLabel:"Obligatorisk evakueringsavstand",safeLabel:"Sikker evakueringsavstand",zoneTypeLabel:"Sonetype",feetLabel:"Fot",metersLabel:"Meter",unitsLabel:"Enheter",threatGraphicLayer:"Trusselgrafikk",settingsTitle:"Innstillinger",mandatoryButtonLabel:"Konfigurer innstillinger for obligatorisk evakueringsavstand",safeButtonLabel:"Konfigurer innstillinger for tilfluktsromsone",style:"Stil",colorPicker:"colorPicker",
lineStyles:{esriSLSDash:"Strek",esriSLSDashDot:"Strek prikk",esriSLSDashDotDot:"Strek prikk prikk",esriSLSDot:"Prikk",esriSLSLongDash:"Lang strek",esriSLSLongDashDot:"Lang strek-prikk",esriSLSNull:"Null",esriSLSShortDash:"Kort strek",esriSLSShortDashDot:"Kort strek-prikk",esriSLSShortDashDotDot:"Kort strek-prikk-prikk",esriSLSShortDot:"Kort prikk",esriSLSSolid:"Heltrukken"},fillStyles:{esriSFSBackwardDiagonal:"Bakover",esriSFSCross:"Kryss",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Fremover",
esriSFSHorizontal:"Vannrett",esriSFSNull:"Null",esriSFSSolid:"Heltrukken",esriSFSVertical:"Loddrett"},resultsTitle:"Resultater",publishTABtn:"Publiser",layerName:"Publisert lagnavn",invalidLayerName:"Lagnavn kan bare inneholde alfanumeriske tegn og understrekingstegn",missingLayerNameMessage:"Du m\u00e5 angi et gyldig lagnavn f\u00f8r du kan publisere",publishingFailedLayerExists:"Publiseringen mislyktes: Du har allerede en geoobjektstjeneste med navnet {0}. Velg et annet lagnavn.",checkService:"Kontroller tjeneste: {0}",
createService:"Opprett tjeneste {0}",unableToCreate:"Kan ikke opprette: {0}",addToDefinition:"Legg til definisjon: {0}",successfullyPublished:"Publiserte weblag",successfullyAppended:"La til nye geoobjekter i weblaget",manageWebLayerText:"Behandle weblaget",userRole:"Kan ikke opprette tjeneste fordi brukeren ikke har tillatelser",retrieveExistingLayerError:"Kan ikke hente {0}. Publiser med et annet lagnavn",publishToNewLayer:"Publiser resultater til et nytt geoobjektlag",layerNameExists:"Lagnavnet finnes allerede. Bruk et annet lagnavn.",
pipeBombLabel:"R\u00f8rbombe",suicideBombLabel:"Selvmordsbombe",briefcaseLabel:"Mappe",carLabel:"Bil",suvVanLabel:"SUV/VAREBIL",smallDeliveryTruckLabel:"Liten varebil",containerWaterTruckLabel:"Container/tankbil",semiTrailerLabel:"Semitrailer",transparencyLabel:"Gjennomsiktighet",outline:"Omriss",fill:"Fyll (farge brukes bare n\u00e5r heldekkende er valgt som stil)",createBtn:"Opprett soner",clearBtn:"T\u00f8m",invalidNumberMessage:"Den angitte verdien er ugyldig",invalidRangeMessage:"Verdien m\u00e5 v\u00e6re st\u00f8rre enn 0",
parseCoordinatesError:"Kan ikke analysere koordinatene. Kontroller det du har skrevet inn.",selectDrawModeLabel:"Velg tegnemodus",selectFeatureLabel:"Velg geoobjekt fra dette laget",fireBallDiameterLable:"Ildkulediameter",lpgSafeDistanceLable:"Trygg avstand",threatTypeCatagoryLabel:"Trusseltypekategori",fireballButtonLabel:"Konfigurer innstillinger for ildkulediameter",safeDistanceButtonLabel:"Konfigurer innstillinger for trygg avstand",chemicalThreatCatagoryLabel:"Kjemisk",lpgThreatCatagoryLabel:"Kondensert petroleumsgass",
chemicalThreatLabel:"Kjemisk trussel",lpgThreatLabel:"LPG-trussel",fireBallDiameterFieldAlias:"LPG-ildkulediameter",lpgSafeDistanceFieldAlias:"LPG trygg avstand",smallLPGTank:"Liten LPG-tank",largeLPGTank:"Stor LPG-tank",commercialResidentialLPGTank:"LGP-tank til n\u00e6rings-/husholdningsbruk",smallLPGTruck:"Liten LPG-lastebil",semiTankerLPG:"Semitanker-LPG",_localized:{}}});