// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/Deferred dojo/query ./utils dijit/form/Button dijit/_TemplatedMixin dijit/_WidgetBase esri/undoManager esri/OperationBase esri/graphic esri/tasks/query esri/tasks/QueryTask esri/tasks/RelationshipQuery esri/layers/FeatureLayer esri/dijit/AttributeInspector esri/dijit/Popup esri/dijit/PopupTemplate jimu/utils jimu/portalUrlUtils jimu/SelectionManager jimu/ConfigManager jimu/dijit/DropdownMenu jimu/dijit/LoadingIndicator jimu/LayerInfos/LayerInfos".split(" "),
function(z,f,p,k,r,t,x,u,G,H,I,J,K,C,A,D,T,L,M,N,O,v,E,F,P,Q,R,S){var n=z([I,H],{baseClass:"related-records-editor",templateString:"\x3cdiv\x3e\x3cdiv class\x3d'operation-box' data-dojo-attach-point\x3d'operationBox'\x3e\x3cdiv class\x3d'previos-btn feature-action' data-dojo-attach-point\x3d'previouBtn'data-dojo-attach-event\x3d'click:_onPreviouBtnClick'\x3e\x3c/div\x3e\x3cdiv class\x3d'operation-title' data-dojo-attach-point\x3d'operationTitle'\x3e\x3c/div\x3e\x3cdiv class\x3d'add-new-btn' data-dojo-attach-point\x3d'addNewBtn'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'content-box' data-dojo-attach-point\x3d'contentBox'\x3e\x3c/div\x3e\x3c/div\x3e",
editorATI:null,originalFeature:null,originalLayer:null,originalJimuLayerInfo:null,layerInfosObj:null,undoManager:null,refDomNode:null,_temporaryData:null,tableInfosParam:null,postCreate:function(){this._init();k.place(this.domNode,this.refDomNode,"after");window.isRTL?k.addClass(this.previouBtn,"icon-arrow-forward"):k.addClass(this.previouBtn,"icon-arrow-back");this.loading=(new R({hidden:!0})).placeAt(this.domNode);this._clearPage();this.showFirstPage({feature:this.originalFeature,oriJimuLayerInfo:this.originalJimuLayerInfo})},
_init:function(){this.refDomNode=this.editorATI.domNode;this.originalLayer=this.originalFeature.getLayer();this.layerInfosObj=S.getInstanceSync();this.originalJimuLayerInfo=this.layerInfosObj.getLayerOrTableInfoById(this.originalLayer.id);this.undoManager=new J;this._temporaryData={eventHandles:[],dijits:[]};this._tempPopup=new N({},k.create("div"));this._tempPopup.show()},destroy:function(){this._clearPage();this._tempPopup.destroy();this.inherited(arguments)},_getRelatedTableInfoArray:function(a){var b=
new t,c=[];a.getRelatedTableInfoArray("esriRelRoleOrigin").then(f.hitch(this,function(d){p.forEach(d,function(e){this._findTableInfoFromTableInfosParam(e)&&c.push(e)},this);b.resolve(c)}));return b},_getRelatedRecordsByQuery:function(a){var b=new t,c=new A,d=new D(a.destJimuLayerInfo.getUrl()),e=a.destJimuLayerInfo.layerObject.relationships.keyField,g=a.oriJimuLayerInfo.layerObject.objectIdField;c.where=e?e+" \x3d "+a.feature.attributes[e]:g+" \x3d "+a.feature.attributes[g];c.outFields=["*"];d.execute(c,
f.hitch(this,function(h){b.resolve(h)}));return b},_getRelatedRecordsByRelatedQuery:function(a){return a.oriJimuLayerInfo.getRelatedRecords(a.feature,a.destJimuLayerInfo,a.relationshipIndex)},_getOriRelationshipByDestLayer:function(a){var b=null;b=p.filter(a.oriJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.destJimuLayerInfo.layerObject.layerId)return!0},this);return b=b[a.relationshipIndex]?b[a.relationshipIndex]:b[0]},_getDestRelationshipByDestLayer:function(a){var b=
null;b=p.filter(a.destJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.oriJimuLayerInfo.layerObject.layerId)return!0},this);return b=b[a.relationshipIndex]?b[a.relationshipIndex]:b[0]},_createATI:function(a){var b=a.destJimuLayerInfo;var c=null,d=this._findTableInfoFromTableInfosParam(b);if(d){c=new n.ATI({layerInfos:[d],hideNavButtons:!0},k.create("div"));c.startup();this._temporaryData.dijits.push(c);var e=this._findTableInfoFromTableInfosParam(b);(e=u.getEditCapabilities(b.layerObject,
e).canDelete)||x(".atiButton.atiDeleteButton",c.domNode).addClass("hidden")}this._editWidget._configEditor.usingSaveButton&&(b=c.addButton(this.nls.save,"save-button related-record disable","after"),b=r(b,"click",f.hitch(this,this._onSaveBtnClick,a,c)),this._temporaryData.eventHandles.push(b));b=c.addButton(this.nls.close,"close-button related-record","before");b=r(b,"click",f.hitch(this,this._onCloseBtnClick));this._temporaryData.eventHandles.push(b);e&&(b=r(c,"delete",f.hitch(this,this._onDeleteBtnClick,
a)),this._temporaryData.eventHandles.push(b));b=r(c,"attribute-change",f.hitch(this,this._onAttributeChange,a));this._temporaryData.eventHandles.push(b);return c},_findTableInfoFromTableInfosParam:function(a){var b=null;p.some(this.tableInfosParam,function(c){if(c.featureLayer.id===a.id)return b=c,!0},this);return b},_keepReferentialIntegrity:function(a){var b=this._getOriRelationshipByDestLayer(a),c=this._getDestRelationshipByDestLayer(a),d={key:"",value:"",hasRelationshipTable:!1,originKeyFieldInRelationshipTable:"",
originValueInRelationshipTable:"",destKeyFieldInRelationshipTable:"",destValueInRelationshipTable:""};if(b.keyField&&c&&c.keyField){var e=u.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,b.keyField);var g=u.ignoreCaseToGetFieldKey(a.destJimuLayerInfo.layerObject,c.keyField);e&&g&&(d.key=g,d.value=a.feature.attributes[e])}else b.keyField&&(e=u.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,b.keyField))&&(d.key=e,d.value=a.feature.attributes[e]);b&&null!=b.relationshipTableId&&c&&null!=
c.relationshipTableId&&(d.hasRelationshipTable=!0,d.originKeyFieldInRelationshipTable=b.keyFieldInRelationshipTable,d.destKeyFieldInRelationshipTable=c.keyFieldInRelationshipTable,d.originValueInRelationshipTable=a.feature.attributes[e],a.relatedFeature&&(d.destValueInRelationshipTable=a.relatedFeature.attributes[g||e]));return d},_prepareNewRelatedRecord:function(a){var b=this._getTemplateFromLayerObject(a.destJimuLayerInfo.layerObject);b=f.mixin({},b?b.prototype.attributes:{});a=this._keepReferentialIntegrity(a);
a.hasRelationshipTable||(b[a.key]=a.value);return new C(null,null,b,null)},_prepareNewRelationshipRecord:function(a,b){var c=null,d={};a=this._keepReferentialIntegrity(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,b,a.relationshipIndex));a.hasRelationshipTable&&(d[a.originKeyFieldInRelationshipTable]=a.originValueInRelationshipTable,d[a.destKeyFieldInRelationshipTable]=a.destValueInRelationshipTable,c=new C(null,null,d,null));return c},_prepareRelationshipTableInfo:function(a){var b=
this._getOriRelationshipByDestLayer(a).relationshipTableId,c=null;if(null==b)return null;a=a.oriJimuLayerInfo.layerObject;var d=a.url.lastIndexOf("/"),e=a.url.slice(0,d)+"/"+b.toString();p.some(this.tableInfosParam,function(g){if(f.getObject("featureLayer.url",!1,g)&&E.removeProtocol(e.toString().toLowerCase()).replace(/\/+/g,"/")===E.removeProtocol(g.featureLayer.url.toString().toLowerCase()).replace(/\/+/g,"/"))return c=this.layerInfosObj.getLayerOrTableInfoById(g.featureLayer.id),!0},this);return c},
_addNewRelationshipReocrd:function(a,b){var c=new t,d=null;(a=this._prepareNewRelationshipRecord(b,a))&&(d=this._prepareRelationshipTableInfo(b));d&&d.layerObject?d.layerObject.applyEdits([a],null,null,f.hitch(this,function(){c.resolve()}),f.hitch(this,function(){console.warn("Failed to add relationship record.");c.resolve()})):c.resolve();return c},_addNewRelatedRecord:function(a,b){var c=new t,d=b.destJimuLayerInfo.layerObject;d.applyEdits([a],null,null,f.hitch(this,function(e){var g=e[0];if(g.success&&
g.objectId){e=new A;var h=new D(d.url);e.where=d.objectIdField+" \x3d "+g.objectId;e.outFields=["*"];h.execute(e,f.hitch(this,function(l){var q=l.features[0];q||(a.attributes[d.objectIdField]=g.objectId,q=a);this._addNewRelationshipReocrd(q,b).then(f.hitch(this,function(){c.resolve(q)}))}),f.hitch(this,function(){c.reject()}))}else c.reject()}),f.hitch(this,function(){c.reject()}));return c},_deleteRelatedRecord:function(a){var b=new t;a.destJimuLayerInfo.layerObject.applyEdits(null,null,[a.relatedFeature],
f.hitch(this,function(){b.resolve()}),f.hitch(this,function(){b.reject()}));return b},_updateRelatedRecordOnSave:function(a){this.loading.show();this._updateRelatedRecord(a).then(f.hitch(this,function(){this.loading.hide()}),f.hitch(this,function(){this.loading.hide()}))},_updateRelatedRecordOnClient:function(a,b){this._editWidget._startEditingSession();a.relatedFeature.attributes[b.fieldName]=b.fieldValue;var c=b.target;c&&c.updateCurrentSelectdFeature&&c.updateCurrentSelectdFeature([a.relatedFeature],
a.destJimuLayerInfo.layerObject,b.fieldName,b.fieldValue)},_updateRelatedRecordDirectly:function(a,b){this.loading.show();a.relatedFeature.attributes[b.fieldName]=b.fieldValue;this._updateRelatedRecord(a).then(f.hitch(this,function(){this.loading.hide();var c=b.target;c&&c.updateCurrentSelectdFeature&&c.updateCurrentSelectdFeature([a.relatedFeature],a.destJimuLayerInfo.layerObject,b.fieldName,b.fieldValue)}),f.hitch(this,function(){this.loading.hide()}))},_updateRelatedRecord:function(a){var b=new t;
a.destJimuLayerInfo.layerObject.applyEdits(null,[a.relatedFeature],null,f.hitch(this,function(){b.resolve()}),f.hitch(this,function(){b.reject()}));return b},_getDisplayTitleOfRelatedRecord:function(a,b,c){var d=a.getInfoTemplate();return(a="popupTitle"===c&&d?"function"===typeof d.title?d.title(b):d.title:this._getDisplayTitleFromPopup(a,b,c))?a:""},_getDisplayTitleFromPopup:function(a,b,c){(a=this._getPopupTemplateWithOnlyDisplayField(a,c))?(b.setInfoTemplate(a),this._tempPopup.setFeatures([b]),
c=(c=x("td.attrValue",this._tempPopup.domNode)[0])&&c.innerHTML,b.setInfoTemplate(null)):c=u.getAttrByFieldKey(b,c);return c},_getPopupTemplateWithOnlyDisplayField:function(a,b){a=a._getCustomPopupInfo(a.layerObject,[b]);return new O(a)},_getTemplateFromLayerObject:function(a){var b=null;a.templates&&a.templates[0]?b=a.templates[0]:a.types&&a.types[0]&&a.types[0].templates[0]&&(b=a.types[0].templates[0]);return b},showRelatedRecords:function(a){this._changeRefDomNode();var b=f.getObject("_wabProperties.originalLayerName",
!1,a.destJimuLayerInfo.layerObject)||a.destJimuLayerInfo.title;this._setOperationTitle(b);this._clearPage();this.loading.show();this._getRelatedRecordsByRelatedQuery(a).then(f.hitch(this,function(c){var d=a.oriJimuLayerInfo.getOriRelationshipByDestLayer(a.oriJimuLayerInfo.layerObject,a.destJimuLayerInfo.layerObject);d&&d.cardinality&&d.cardinality.toLowerCase&&0<=d.cardinality.toLowerCase().indexOf("onetoone")&&1<=c.length?this._hideAddNewBtn():this._showAddNewBtn(a);0<c.length?this._setTitle(window.jimuNls.popup.relatedRecords):
this._setTitle(window.jimuNls.popup.noRelatedRecotds,"font-normal");var e=this._showFieldSelector(a.destJimuLayerInfo);p.forEach(c,function(g,h){g._layer=a.destJimuLayerInfo.layerObject;var l=this._getDisplayTitleOfRelatedRecord(a.destJimuLayerInfo,g,e);h=k.create("div",{"class":"item record-item enable "+(0===h%2?"oddLine":"evenLine"),innerHTML:v.sanitizeHTML(l)},this.contentBox);h.relatedRecord=g;h=r(h,"click",f.hitch(this,function(){this._addOperation(n.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,
a.oriJimuLayerInfo,a.destJimuLayerInfo,g,a.relationshipIndex))}));this._temporaryData.eventHandles.push(h)},this);this.loading.hide()}))},showInspector:function(a){var b=!1;this._changeRefDomNode();var c=a.destJimuLayerInfo.layerObject,d=f.getObject("_wabProperties.originalLayerName",!1,c)||a.destJimuLayerInfo.title;c=f.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",!1,c);var e=this._getDisplayTitleOfRelatedRecord(a.destJimuLayerInfo,a.relatedFeature,c);"popupTitle"!==c&&(e=
d+": "+e);this._setOperationTitle(e);this._clearPage();(e=this._createATI(a))&&k.place(e.domNode,this.contentBox);d=a.destJimuLayerInfo.layerObject.objectIdField;c=a.relatedFeature.attributes[d];null===c||void 0===c?(a.destJimuLayerInfo.layerObject.clearSelection(),e.showFeature(a.relatedFeature,a.destJimuLayerInfo.layerObject),b=!0,x(".atiButton.atiDeleteButton",e.domNode).addClass("disable"),this._editWidget._startEditingSession()):(this.loading.show(),e=new A,e.where=d+" \x3d "+c,a.destJimuLayerInfo.layerObject.selectFeatures(e,
L.SELECTION_NEW,f.hitch(this,function(){this.loading.hide();var g=a.destJimuLayerInfo.layerObject.getSelectedFeatures();g&&g[0]&&g[0].geometry&&this._activeGraphicEdit(g[0],a.oriJimuLayerInfo)})));this.showRelatedTables(this._createOperationData(a.relatedFeature,a.destJimuLayerInfo,null,null,null),a,b)},showRelatedTables:function(a,b,c){this._getRelatedTableInfoArray(a.oriJimuLayerInfo).then(f.hitch(this,function(d){0<d.length&&this._setTitle(window.jimuNls.popup.relatedTables);var e={};p.forEach(d,
function(h){void 0===e[h.id]?e[h.id]=0:e[h.id]++},this);var g={};p.forEach(d,function(h,l){void 0===g[h.id]?g[h.id]=0:g[h.id]++;var q=0===l%2?"oddLine ":"evenLine ",m=c?"disable ":"enable ";l='\x3cdiv title\x3d"'+h.title+'"\x3e'+v.sanitizeHTML(h.title)+"\x3c/div\x3e";q=k.create("div",{"class":"item table-item "+q+m,innerHTML:l},this.contentBox);var y=g[h.id];0<e[h.id]&&(m=a.oriJimuLayerInfo.getOriRelationshipByDestLayer(a.oriJimuLayerInfo.layerObject,h.layerObject,y),m=m.name||m.id,m='\x3cdiv class\x3d"relationshipName" title\x3d"'+
m+'"\x3e('+v.sanitizeHTML(m)+")\x3c/div\x3e",q.innerHTML=l+m);c||(l=r(q,"click",f.hitch(this,function(){if(this._editWidget._configEditor.usingSaveButton)var w=this._editWidget._popupConfirmDialog();else w=new t,w.resolve(!0);w.then(f.hitch(this,function(B){B&&h.getLayerObject().then(f.hitch(this,function(){b?this._addOperation(n.OPERATION_SHOW_INSPECTOR,b):this._addOperation(n.OPERATION_FIRST,a);this.showRelatedRecords(this._createOperationData(a.feature,a.oriJimuLayerInfo,h,null,y))}))}))})),this._temporaryData.eventHandles.push(l))},
this)}))},showFirstPage:function(a,b){this._clearPage();this._revertRefDomNode();this.showRelatedTables(a);b&&(p.forEach(this._editWidget._jimuLayerInfos.getLayerInfoArray(),function(c){c.layerObject&&c.layerObject.clearSelection&&c.id!==this.originalJimuLayerInfo.id&&F.getInstance().clearSelection(c.layerObject)},this),this.originalFeature.setSymbol(this.originalLayer.getSelectionSymbol()),this._activeGraphicEdit(this.originalFeature))},_activeGraphicEdit:function(a,b){b&&(b.id===this.originalJimuLayerInfo.id?
this.originalFeature.setSymbol(null,!0):F.getInstance().clearSelection(b.layerObject));var c;this._editWidget.editor._editVertices=!0;this._editWidget.editor._activateEditToolbar(a);a.geometry&&(c="point"===a.geometry.type?a.geometry:a.geometry.getExtent().getCenter());this._editWidget.map.infoWindow.show(c)},_createOperationData:function(a,b,c,d,e){return{feature:a,oriJimuLayerInfo:b,destJimuLayerInfo:c,relatedFeature:d,relationshipIndex:e||0}},_addOperation:function(a,b){this.undoManager.add(new n.Operation(a,
b,this))},_onPreviouBtnClick:function(){if(this._editWidget._configEditor.usingSaveButton)var a=this._editWidget._popupConfirmDialog();else a=new t,a.resolve(!0);a.then(f.hitch(this,function(b){b&&this.undoManager.undo()}))},_onAddNewBtnClick:function(a){var b=a.destJimuLayerInfo.layerObject,c=this._prepareNewRelatedRecord(a),d=this._keepReferentialIntegrity(a);"Table"!==b.type?this._editWidget._startEditingRelatedGraphic(a,d):this._editWidget._configEditor.usingSaveButton?(this._addOperation(n.OPERATION_SHOW_RELATED_RECORDS,
a),this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,c,a.relationshipIndex))):(this.loading.show(),this._addNewRelatedRecord(c,a).then(f.hitch(this,function(e){this.loading.hide();this._addOperation(n.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,e,a.relationshipIndex))}),f.hitch(this,function(){this.loading.hide()})))},_onCloseBtnClick:function(){this._editWidget.editPopup.hide()},
_onDeleteBtnClick:function(a){var b=a.relatedFeature.attributes[a.destJimuLayerInfo.layerObject.objectIdField];null!==b&&void 0!==b&&(this._editWidget._configEditor.usingSaveButton&&this._editWidget._stopEditingSession(),this.loading.show(),this._deleteRelatedRecord(a).then(f.hitch(this,function(){this.loading.hide();this._onPreviouBtnClick()}),f.hitch(this,function(){this.loading.hide()})))},_onSaveBtnClick:function(a){if(this._editWidget._isEditingSession){var b=a.relatedFeature.attributes[a.destJimuLayerInfo.layerObject.objectIdField];
null===b||void 0===b?(b=a.relatedFeature,this.loading.show(),this._addNewRelatedRecord(b,a).then(f.hitch(this,function(c){this.loading.hide();this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,c,a.relationshipIndex))}),f.hitch(this,function(){this.loading.hide()}))):this._updateRelatedRecordOnSave(a);this._editWidget._stopEditingSession()}},_onAttributeChange:function(a,b){this._editWidget._configEditor.usingSaveButton?this._updateRelatedRecordOnClient(a,
b):this._updateRelatedRecordDirectly(a,b)},_clearPage:function(){k.empty(this.contentBox);k.setStyle(this.addNewBtn,"display","none");p.forEach(this._temporaryData.eventHandles,function(a){a&&a.remove&&a.remove()},this);this._temporaryData.eventHandles=[];p.forEach(this._temporaryData.dijits,function(a){a&&a.destroy&&a.destroy()},this);this._temporaryData.dijits=[]},_changeRefDomNode:function(){k.setStyle(this.refDomNode,"display","none");k.setStyle(this.operationBox,"display","block");k.addClass(this.domNode,
"fix-height-mode");this.previouBtn.title=window.jimuNls.common.back;this.addNewBtn.title=window.jimuNls.common.newText;this.undoManager.peekUndo()?k.setStyle(this.previouBtn,"display","block"):k.setStyle(this.previouBtn,"display","none")},_revertRefDomNode:function(){k.setStyle(this.refDomNode,"display","block");k.setStyle(this.operationBox,"display","none");k.removeClass(this.domNode,"fix-height-mode")},_showAddNewBtn:function(a){var b=a.destJimuLayerInfo.layerObject,c=this._findTableInfoFromTableInfosParam(a.destJimuLayerInfo);
u.getEditCapabilities&&u.getEditCapabilities(b,c).canCreate&&(k.setStyle(this.addNewBtn,"display","block"),a=r(this.addNewBtn,"click",f.hitch(this,this._onAddNewBtnClick,a)),this._temporaryData.eventHandles.push(a))},_hideAddNewBtn:function(){k.setStyle(this.addNewBtn,"display","none")},_setTitle:function(a,b){a&&k.create("div",{"class":"title-box "+(b?b:""),innerHTML:v.sanitizeHTML(a)},this.contentBox)},_setOperationTitle:function(a){k.setAttr(this.operationTitle,"innerHTML",v.sanitizeHTML(a));k.setAttr(this.operationTitle,
"title",a)},_showFieldSelector:function(a){var b="objecid",c=x(".title-box",this.contentBox)[0],d=a.layerObject,e=[];if(!c||!a)return b;var g=a.getPopupInfo();g&&g.title&&e.push({label:window.jimuNls.popup.saveAsPopupTitle,value:"popupTitle"});var h=this._findTableInfoFromTableInfosParam(a);h&&h.fieldInfos&&p.forEach(h.fieldInfos,function(m){"globalid"!==m.fieldName.toLowerCase()&&"shape"!==m.fieldName.toLowerCase()&&e.push({label:m.label||m.fieldName,value:m.fieldName})});c=(new Q({items:e})).placeAt(c);
c.domNode.title=window.jimuNls.popup.chooseFieldTip;h=f.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",!1,d);var l=u.ignoreCaseToGetFieldObject(a.layerObject,a.layerObject.displayField||a.layerObject.objectIdField),q=P.getInstance().getAppConfig();h?b=h:"2.3"===q.configWabVersion&&l&&l.name?b=l.name:g&&g.title?b="popupTitle":l&&l.name?b=l.name:0<e.length&&(b=e[0].value);b&&(c.setHighlightValue(b),f.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,d));this._temporaryData.dijits.push(c);
a=r(c,"click-item",f.hitch(this,function(m,y){x(".item.record-item",this.contentBox).forEach(f.hitch(this,function(w){f.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",y,d);var B=this._getDisplayTitleOfRelatedRecord(m,w.relatedRecord,y);w.innerHTML=v.sanitizeHTML(B)}))},a));this._temporaryData.eventHandles.push(a);return b}});n.Operation=z([K],{constructor:function(a,b,c){this.operationName=a;this.operationData=b;this.relatedRecordsEditor=c},performUndo:function(){switch(this.operationName){case n.OPERATION_SHOW_RELATED_TABLES:return this.relatedRecordsEditor.showRelatedTables(this.operationData);
case n.OPERATION_SHOW_RELATED_RECORDS:return this.relatedRecordsEditor.showRelatedRecords(this.operationData);case n.OPERATION_SHOW_INSPECTOR:return this.relatedRecordsEditor.showInspector(this.operationData);default:return this.relatedRecordsEditor.showFirstPage(this.operationData,!0)}}});n.ATI=z([M],{constructor:function(){this._aiConnects=[];this._selection=[];this._toolTips=[]},addButton:function(a,b,c){c=c?c:"before";a=new G({label:a,"class":" atiButton "+b},k.create("div"));k.place(a.domNode,
this.deleteBtn.domNode,c);return a},updateCurrentSelectdFeature:function(a,b,c,d){this._selection&&this._selection[0]&&c&&(this._selection[0].attributes[c]=d,b.ownershipBasedAccessControlForFeatures=!0,this.refresh(),b.ownershipBasedAccessControlForFeatures=!1)},_getFields:function(a){return a.fields}});f.mixin(n,{OPERATION_SHOW_RELATED_TABLES:"showRelatedTables",OPERATION_SHOW_RELATED_RECORDS:"showRelatedRecords",OPERATION_SHOW_INSPECTOR:"showInspector",OPERATION_FIRST:"first"});return n});