// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transpar\u00eancia",outline:"Contorno",fill:"Preenchimento (Apenas \u00e9 aplicada cor quando o estilo \u00e9 definido como s\u00f3lido)",style:"Estilo",mandatoryLabel:"Dist\u00e2ncia de evacua\u00e7\u00e3o obrigat\u00f3ria",mandatoryButtonLabel:"Configurar defini\u00e7\u00f5es de dist\u00e2ncia de evacua\u00e7\u00e3o obrigat\u00f3ria",safeLabel:"Dist\u00e2ncia de evacua\u00e7\u00e3o segura",safeButtonLabel:"Configurar defini\u00e7\u00f5es de dist\u00e2ncia de evacua\u00e7\u00e3o segura",
selectOpLayerLabel:"Selecionar uma nova camada operacional para os resultados",selectDefaultMeasurementLabel:"Selecionar a unidade de medida predefinida",helpIconTooltip:"A lista de camadas operacionais \u00e9 preenchida com camadas do mapa web atual do tipo de geometria de pol\u00edgono.",lineStyles:{esriSLSDash:"Tra\u00e7o",esriSLSDashDot:"Tra\u00e7o e Ponto",esriSLSDashDotDot:"Tra\u00e7o, Ponto e Ponto",esriSLSDot:"Ponto",esriSLSLongDash:"Tra\u00e7o Longo",esriSLSLongDashDot:"Tra\u00e7o Longo e Ponto",
esriSLSNull:"Nulo",esriSLSShortDash:"Tra\u00e7o Curto",esriSLSShortDashDot:"Tra\u00e7o Curto e Ponto",esriSLSShortDashDotDot:"Tra\u00e7o Curto, Ponto e Ponto",esriSLSShortDot:"Tra\u00e7o Curto",esriSLSSolid:"S\u00f3lido"},fillStyles:{esriSFSBackwardDiagonal:"Ao Contr\u00e1rio",esriSFSCross:"Cruz",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Para a frente",esriSFSHorizontal:"Horizontal",esriSFSNull:"Nulo",esriSFSSolid:"S\u00f3lido",esriSFSVertical:"Vertical"},threatTypeLabel:"Tipo de amea\u00e7a",
symbologyLabel:"Simbologia",generalLabel:"Geral",addThreatTypesLabel:"Adicionar Tipo de Amea\u00e7a",threatTypeColLabel:"Tipo de Amea\u00e7a Qu\u00edmica",actions:"A\u00e7\u00f5es",newThreatTypePopupLabel:"Novo Tipo de Amea\u00e7a",chooseDefaultThreatTypeIconLabel:"Escolher de predefini\u00e7\u00e3o",mandatoryDistance:"Dist\u00e2ncia de evacua\u00e7\u00e3o obrigat\u00f3ria",safeDistance:"Dist\u00e2ncia de evacua\u00e7\u00e3o segura",units:"Unidades",chooseDefaultThreatLabel:"Selecionar um tipo de amea\u00e7a predefinido",
defaultThreatTypePopUpLabel:"Tipos de Amea\u00e7a Predefinidos",editThreatLabel:"Editar Amea\u00e7a",defaultThreatTypeIconTooltip:"Lista de Tipos de Amea\u00e7a Predefinidos",uniqueThreatTypeMsg:"Introduza um tipo de amea\u00e7a \u00fanico; j\u00e1 existe um tipo de amea\u00e7a com este nome.",requiredThreatTypeMsg:"Este campo \u00e9 necess\u00e1rio",unitMeasureLabel:"As dist\u00e2ncias est\u00e3o em {0}",pipeBombLabel:"Bomba de Tubo",suicideBombLabel:"Bomba Suicida",briefcaseLabel:"Pasta",carLabel:"Carro",
suvVanLabel:"SUV/CARRINHA",smallDeliveryTruckLabel:"Carrinha de Entregas Pequena",containerWaterTruckLabel:"Cami\u00e3o Cisterna/de \u00c1gua",semiTrailerLabel:"Semirreboque",lpgSafeDistanceLable:"Dist\u00e2ncia Segura",fireBallDiameterLable:"Di\u00e2metro de Bola de Fogo",lpgthreatTypeColLabel:"Tipo de Amea\u00e7a GPL",threatTypeCatagoryLabel:"Categoria do Tipo de Amea\u00e7a",chemicalThreatLegendLabel:"Amea\u00e7a Qu\u00edmica",lpgThreatLegendLabel:"Amea\u00e7a GPL",fireballButtonLabel:"Configurar Defini\u00e7\u00f5es de Di\u00e2metro de Bola de Fogo",
safeDistanceButtonLabel:"Configurar Defini\u00e7\u00f5es de Dist\u00e2ncia de Seguran\u00e7a",chemicalThreatCatagoryLabel:"Qu\u00edmica",lpgThreatCatagoryLabel:"GPL",smallLPGTank:"Tanque Pequeno GPL",largeLPGTank:"Tanque Grande GPL",commercialResidentialLPGTank:"Tanque GPL Comercial/Residencial",smallLPGTruck:"Cami\u00e3o Pequeno GPL",semiTankerLPG:"Semirreboque GPL",_localized:{}}});