// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transparenz",outline:"Umrisslinie",fill:"F\u00fcllung (Farbe wird nur angewendet, wenn der Style auf Vollfarbe festgelegt ist)",style:"Style",mandatoryLabel:"Entfernung f\u00fcr obligatorische Evakuierung",mandatoryButtonLabel:"Einstellungen f\u00fcr Entfernung f\u00fcr obligatorische Evakuierung konfigurieren",safeLabel:"Entfernung f\u00fcr sichere Evakuierung",safeButtonLabel:"Einstellungen f\u00fcr Entfernung f\u00fcr sichere Evakuierung konfigurieren",
selectOpLayerLabel:"Operationalen Layer f\u00fcr die Ergebnisse ausw\u00e4hlen",selectDefaultMeasurementLabel:"Standardmesseinheit ausw\u00e4hlen",helpIconTooltip:"Die Liste der operationalen Layer wird mit Layern der aktuellen Webkarte, die einen Polygon-Geometrietyp aufweisen, gef\u00fcllt.",lineStyles:{esriSLSDash:"Strich",esriSLSDashDot:"Strich-Punkt",esriSLSDashDotDot:"Strich-Punkt-Punkt",esriSLSDot:"Punkt",esriSLSLongDash:"Langer Strich",esriSLSLongDashDot:"Langer Strich-Punkt",esriSLSNull:"NULL",
esriSLSShortDash:"Kurzer Strich",esriSLSShortDashDot:"Kurzer Strich-Punkt",esriSLSShortDashDotDot:"Kurzer Strich-Punkt-Punkt",esriSLSShortDot:"Kurzer Punkt",esriSLSSolid:"Durchgezogen"},fillStyles:{esriSFSBackwardDiagonal:"R\u00fcckw\u00e4rts",esriSFSCross:"Kreuzf\u00f6rmig",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Vorw\u00e4rts",esriSFSHorizontal:"Horizontal",esriSFSNull:"NULL",esriSFSSolid:"Vollfarbe",esriSFSVertical:"Vertikal"},threatTypeLabel:"Bedrohungstyp",symbologyLabel:"Symbolisierung",
generalLabel:"Allgemein",addThreatTypesLabel:"Bedrohungstyp hinzuf\u00fcgen",threatTypeColLabel:"Chemischer Bedrohungstyp",actions:"Aktionen",newThreatTypePopupLabel:"Neuer Bedrohungstyp",chooseDefaultThreatTypeIconLabel:"Aus Standard ausw\u00e4hlen",mandatoryDistance:"Entfernung f\u00fcr obligatorische Evakuierung",safeDistance:"Entfernung f\u00fcr sichere Evakuierung",units:"Einheiten",chooseDefaultThreatLabel:"Standardm\u00e4\u00dfigen Bedrohungstyp ausw\u00e4hlen",defaultThreatTypePopUpLabel:"Standardm\u00e4\u00dfige Bedrohungstypen",
editThreatLabel:"Bedrohung bearbeiten",defaultThreatTypeIconTooltip:"Liste der standardm\u00e4\u00dfigen Bedrohungstypen",uniqueThreatTypeMsg:"Geben Sie einen eindeutigen Bedrohungstyp an. Ein Bedrohungstyp mit diesem Namen ist bereits vorhanden.",requiredThreatTypeMsg:"Dies ist ein Pflichtfeld",unitMeasureLabel:"Entfernungen sind in {0} angegeben",pipeBombLabel:"Rohrbombe",suicideBombLabel:"Selbstmordattentat",briefcaseLabel:"Aktenkoffer",carLabel:"Auto",suvVanLabel:"SUV/Van",smallDeliveryTruckLabel:"Kleiner Lieferwagen",
containerWaterTruckLabel:"Container-Lkw/Wassertankwagen",semiTrailerLabel:"Sattelschlepper",lpgSafeDistanceLable:"Sichere Entfernung",fireBallDiameterLable:"Feuerball-Durchmesser",lpgthreatTypeColLabel:"Bedrohungstyp Fl\u00fcssiggas",threatTypeCatagoryLabel:"Bedrohungstyp-Kategorie",chemicalThreatLegendLabel:"Chemische Bedrohung",lpgThreatLegendLabel:"Bedrohung durch Fl\u00fcssiggas",fireballButtonLabel:"Einstellungen f\u00fcr Feuerball-Durchmesser konfigurieren",safeDistanceButtonLabel:"Einstellungen f\u00fcr sichere Entfernung konfigurieren",
chemicalThreatCatagoryLabel:"Chemikalie",lpgThreatCatagoryLabel:"Fl\u00fcssiggas",smallLPGTank:"Kleiner Fl\u00fcssiggastank",largeLPGTank:"Gro\u00dfer Fl\u00fcssiggastank",commercialResidentialLPGTank:"Gewerblicher/privater Fl\u00fcssiggastank",smallLPGTruck:"Kleiner Fl\u00fcssiggas-Lkw",semiTankerLPG:"Fl\u00fcssiggas-Tankauflieger",_localized:{}}});