// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transparencia",outline:"Lista",fill:"Relleno (el color solo se aplica si el estilo es s\u00f3lido)",style:"Estilo",mandatoryLabel:"Distancia de evacuaci\u00f3n obligatoria",mandatoryButtonLabel:"Configurar los ajustes de Distancia de evacuaci\u00f3n obligatoria",safeLabel:"Distancia de evacuaci\u00f3n segura",safeButtonLabel:"Configurar los ajustes de Distancia de evacuaci\u00f3n segura",selectOpLayerLabel:"Seleccionar una capa operativa para los resultados",
selectDefaultMeasurementLabel:"Seleccionar una unidad de medida predeterminada",helpIconTooltip:"La lista de capas operativas se rellena con las capas del mapa web actual que corresponden al tipo de geometr\u00eda de pol\u00edgono.",lineStyles:{esriSLSDash:"Guion",esriSLSDashDot:"Guion Punto",esriSLSDashDotDot:"Guion Punto Punto",esriSLSDot:"Punto",esriSLSLongDash:"Guion largo",esriSLSLongDashDot:"Guion largo, Punto",esriSLSNull:"Nulo",esriSLSShortDash:"Guion corto",esriSLSShortDashDot:"Guion corto Punto",
esriSLSShortDashDotDot:"Guion corto Punto Punto",esriSLSShortDot:"Corto Punto",esriSLSSolid:"S\u00f3lido"},fillStyles:{esriSFSBackwardDiagonal:"Atr\u00e1s",esriSFSCross:"Cruz",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Hacia delante",esriSFSHorizontal:"Horizontal",esriSFSNull:"Nulo",esriSFSSolid:"S\u00f3lido",esriSFSVertical:"Vertical"},threatTypeLabel:"Tipo de amenaza",symbologyLabel:"Simbolog\u00eda",generalLabel:"General",addThreatTypesLabel:"Agregar tipo de amenaza",threatTypeColLabel:"Tipo de amenaza qu\u00edmica",
actions:"Acciones",newThreatTypePopupLabel:"Nuevo tipo de amenaza",chooseDefaultThreatTypeIconLabel:"Elegir de entre los valores predeterminados",mandatoryDistance:"Distancia de evacuaci\u00f3n obligatoria",safeDistance:"Distancia de evacuaci\u00f3n segura",units:"Unidades",chooseDefaultThreatLabel:"Seleccionar un tipo de amenaza predeterminado",defaultThreatTypePopUpLabel:"Tipos de amenaza predeterminados",editThreatLabel:"Editar amenaza",defaultThreatTypeIconTooltip:"Lista de tipos de amenaza predeterminados",
uniqueThreatTypeMsg:"Introduzca un tipo de amenaza \u00fanico; ya existe un tipo de amenaza con este nombre.",requiredThreatTypeMsg:"Este campo es obligatorio.",unitMeasureLabel:"Las distancias est\u00e1n en {0}",pipeBombLabel:"Bomba casera",suicideBombLabel:"Bomba suicida",briefcaseLabel:"Malet\u00edn",carLabel:"Autom\u00f3vil",suvVanLabel:"Todoterreno/furgoneta",smallDeliveryTruckLabel:"Cami\u00f3n de reparto peque\u00f1o",containerWaterTruckLabel:"Contenedor/cami\u00f3n cisterna",semiTrailerLabel:"Semirremolque",
lpgSafeDistanceLable:"Distancia segura",fireBallDiameterLable:"Di\u00e1metro de bola de fuego",lpgthreatTypeColLabel:"Tipo de amenaza de GLP",threatTypeCatagoryLabel:"Categor\u00eda del tipo de amenaza",chemicalThreatLegendLabel:"Amenaza qu\u00edmica",lpgThreatLegendLabel:"Amenaza de GLP",fireballButtonLabel:"Configurar los ajustes de Di\u00e1metro de bola de fuego",safeDistanceButtonLabel:"Configurar los ajustes de Distancia segura",chemicalThreatCatagoryLabel:"Qu\u00edmico",lpgThreatCatagoryLabel:"GLP",
smallLPGTank:"Dep\u00f3sito de GLP peque\u00f1o",largeLPGTank:"Dep\u00f3sito de GLP grande",commercialResidentialLPGTank:"Dep\u00f3sito de GLP comercial/residencial",smallLPGTruck:"Cami\u00f3n cisterna de GLP peque\u00f1o",semiTankerLPG:"Semirremolque cisterna de GLP",_localized:{}}});